#!/usr/bin/env python3
"""Emit a TRUEOS Intel replay artifact module from a replay manifest.

The output is intentionally dumb: it preserves captured BO GPU VAs and emits
`include_bytes!` patches that the baremetal replay harness can apply before
submitting a captured batch through the sparse PPGTT path.
"""

from __future__ import annotations

import argparse
import json
import os
from pathlib import Path


def rust_path(path: Path, out_dir: Path) -> str:
    rel = os.path.relpath(path, out_dir)
    return rel.replace("\\", "/")


def choose_dump(dumps: list[dict]) -> dict | None:
    existing = [d for d in dumps if d.get("exists")]
    if not existing:
        return None
    pre_exec = [d for d in existing if str(d.get("phase") or "").startswith("pre_exec")]
    candidates = pre_exec or existing
    return max(
        candidates,
        key=lambda d: (
            d.get("phase") == "pre_exec_full_object",
            int(d.get("dump_len") or 0),
        ),
    )


def frame_submits(manifest: dict) -> list[dict]:
    return [s for s in manifest["submits"] if int(s.get("buffer_count") or 0) > 1]


def emit(manifest_path: Path, out_path: Path, name: str) -> None:
    manifest = json.loads(manifest_path.read_text())
    root = manifest_path.parent
    frames = frame_submits(manifest)
    if not frames:
        raise SystemExit("manifest contains no frame submits")

    first = frames[0]
    out_dir = out_path.parent
    out_dir.mkdir(parents=True, exist_ok=True)

    lines: list[str] = []
    lines.append("// @generated by tools/intel_userland_oracle/emit_replay_artifact.py")
    lines.append("use crate::intel::replay::{ReplayBoSpec, ReplayPatch, ReplayPresent, ReplaySubmit};")
    lines.append("")
    lines.append(f"pub(crate) const {name.upper()}_BO_SPECS: &[ReplayBoSpec] = &[")
    for obj in first["objects"]:
        lines.append(
            "    ReplayBoSpec { "
            f"handle: {int(obj['handle'])}, "
            f"gpu_va: 0x{int(obj['offset']):016X}, "
            f"size: 0x{int(obj['size']):X}, "
            f"flags: 0x{int(obj['flags']):X} "
            "},"
        )
    lines.append("];")
    lines.append("")

    base_names: list[str] = []
    lines.append(f"pub(crate) const {name.upper()}_BASE_PATCHES: &[ReplayPatch] = &[")
    for obj in first["objects"]:
        dump = choose_dump(obj.get("dumps") or [])
        if dump is None:
            continue
        dump_path = root / dump["file"]
        inc = rust_path(dump_path, out_dir)
        sym = f"{name.upper()}_BASE_H{int(obj['handle'])}"
        base_names.append(sym)
        lines.append(f"    ReplayPatch {{ handle: {int(obj['handle'])}, offset: 0x{int(dump['offset']):X}, bytes: {sym} }},")
        lines.insert(2, f"const {sym}: &[u8] = include_bytes!(\"{inc}\");")
    lines.append("];")
    lines.append("")

    submit_syms: list[str] = []
    for submit in frames:
        seq = int(submit["seq"])
        patch_sym = f"{name.upper()}_SEQ_{seq}_PATCHES"
        submit_syms.append(patch_sym)
        lines.append(f"pub(crate) const {patch_sym}: &[ReplayPatch] = &[")
        for obj in submit["objects"]:
            dump = choose_dump(obj.get("dumps") or [])
            if dump is None:
                continue
            dump_path = root / dump["file"]
            inc = rust_path(dump_path, out_dir)
            bytes_sym = f"{patch_sym}_H{int(obj['handle'])}"
            lines.insert(2, f"const {bytes_sym}: &[u8] = include_bytes!(\"{inc}\");")
            lines.append(
                f"    ReplayPatch {{ handle: {int(obj['handle'])}, "
                f"offset: 0x{int(dump['offset']):X}, bytes: {bytes_sym} }},"
            )
        lines.append("];")
        lines.append("")

    lines.append(f"pub(crate) const {name.upper()}_SUBMITS: &[ReplaySubmit] = &[")
    for submit, patch_sym in zip(frames, submit_syms):
        batch_start = int(submit["batch_start"])
        first_obj_gpu = int(submit["objects"][0]["offset"])
        batch_gpu = first_obj_gpu + batch_start
        lines.append(
            "    ReplaySubmit { "
            f"seq: {int(submit['seq'])}, "
            f"batch_gpu: 0x{batch_gpu:016X}, "
            f"batch_start: 0x{batch_start:X}, "
            f"flags: 0x{int(submit['flags']):X}, "
            f"patches: {patch_sym} "
            "},"
        )
    lines.append("];")
    lines.append("")
    lines.append(f"pub(crate) const {name.upper()}_PRESENT: ReplayPresent = ReplayPresent {{")
    lines.append("    handle: 13,")
    lines.append("    offset: 0,")
    lines.append("    width: 512,")
    lines.append("    height: 512,")
    lines.append("    pitch_bytes: 2048,")
    lines.append("};")
    lines.append("")
    lines.append("// Note: batch_gpu is emitted as exec_object[0].gpu_va + batch_start.")
    lines.append("// If ACTHD says the batch really lives in another BO, regenerate or edit this field.")

    out_path.write_text("\n".join(lines) + "\n")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("manifest", type=Path)
    parser.add_argument("--out", type=Path, required=True)
    parser.add_argument("--name", default="rotating_triangle")
    args = parser.parse_args()
    emit(args.manifest, args.out, args.name)


if __name__ == "__main__":
    main()
