// @generated by tools/maxpix-bake/bake.py; ADL-S native POINTLIST.
use super::{
    DispatchMode, ShaderKernelMetadata, TrianglePipeline, TrianglePixelShader,
    TrianglePixelShaderMetadata, TriangleVertexShader, TriangleVertexShaderMetadata,
};

pub(crate) const VS_URB_READ_LENGTH: u8 = 1;
pub(crate) const VF_COMPONENT_PACKING: u32 = 0x00000A77;
// Base-instance/instance-ID SGVS uses synthetic vertex element 2.
pub(crate) const VF_SGVS_DW1: u32 = 0xE002_4002;
pub(crate) const VF_SGVS_2_DW1: u32 = 0xB002_0002;
pub(crate) const SBE_READ_OFFSET: u8 = 1;
pub(crate) const SBE_READ_LENGTH: u8 = 1;

static MAXPIX_VS_CODE: [u32; 232] = [
    0xA10D0040, 0x08000902, 0x80030061, 0x49054220, 0x00000000, 0x00000000, 0x80000061, 0x4B054660,
    0x00000000, 0x3DCCCCCD, 0x80030061, 0x4A054220, 0x00000000, 0x00000000, 0x00030061, 0x77054220,
    0x00000000, 0x00000000, 0x00030061, 0x78054220, 0x00000000, 0x00000000, 0x00030061, 0x79054220,
    0x00000000, 0x00000000, 0x00030061, 0x7A054220, 0x00000000, 0x00000000, 0x80030061, 0x7F050220,
    0x00460105, 0x00000000, 0x00030769, 0x21058660, 0x02460D05, 0x00000002, 0x80000761, 0x49454620,
    0x00000000, 0x00000128, 0x80000761, 0x4A454620, 0x00000000, 0x00000080, 0x0003B031, 0x220C0000,
    0xCC06210C, 0x001A0000, 0x8003A131, 0x140C0000, 0xA402490C, 0x02100000, 0x80049231, 0x3B140000,
    0xA6024A0C, 0x02100000, 0x80002101, 0x00000000, 0x00000000, 0x00000000, 0x80000701, 0x00000000,
    0x00000000, 0x00000000, 0x2111005B, 0x144B0304, 0x80000061, 0x4B254660, 0x00000000, 0x41100000,
    0x61120243, 0x00101100, 0xE1130141, 0x40201200, 0x00030041, 0x16058AA0, 0x0A461205, 0xBF99999A,
    0xE11C0041, 0x41001200, 0x0003035B, 0x370441A0, 0x0A0A3400, 0x13051205, 0x00030340, 0x17058AA0,
    0x0A461605, 0x40133333, 0xE11D0340, 0xC0801C00, 0xE118025B, 0x17140200, 0x21420240, 0x06001D00,
    0x21400541, 0x04003700, 0x80000301, 0x00000000, 0x00000000, 0x00000000, 0xE119005B, 0x124B1808,
    0x61232041, 0x0D002202, 0x0003A338, 0x1A050AA0, 0x7A461905, 0x00460001, 0x80003301, 0x00000000,
    0x00000000, 0x00000000, 0x00034438, 0x1F050AA0, 0x6A461905, 0x00460001, 0xA1240140, 0x03002303,
    0xA1290040, 0x02002303, 0xA1320040, 0x01002303, 0x00034531, 0x0C240000, 0xC004230C, 0x00180000,
    0xA141E35B, 0x401A0500, 0x0003C631, 0x25240000, 0xC004240C, 0x00180000, 0xA143245B, 0x401F0700,
    0x0003C731, 0x2A240000, 0xC004290C, 0x00180000, 0x0003B831, 0x08240000, 0xC004320C, 0x00180000,
    0x80002701, 0x00000000, 0x00000000, 0x00000000, 0xA12E965B, 0x432A2500, 0x80002701, 0x00000000,
    0x00000000, 0x00000000, 0xA12F265B, 0x432B2600, 0x80002701, 0x00000000, 0x00000000, 0x00000000,
    0xA130265B, 0x432C2700, 0x80002701, 0x00000000, 0x00000000, 0x00000000, 0xA131265B, 0x432D2800,
    0xA133C85B, 0x42082E00, 0xA134C85B, 0x42092F00, 0xA135C85B, 0x420A3000, 0xA136C85B, 0x420B3100,
    0xA110C55B, 0x410C3300, 0xA138C55B, 0x410D3400, 0xA139C55B, 0x410E3500, 0xA13AC55B, 0x410F3600,
    0x80002201, 0x00000000, 0x00000000, 0x00000000, 0x213D0141, 0x3A013C58, 0x213E0041, 0x3A043C70,
    0x213F0041, 0x3A013C68, 0x21150041, 0x3A013C80, 0xE11B045B, 0x393C3D00, 0xA11E045B, 0x393C3E0D,
    0xE120045B, 0x393C3F30, 0xE144045B, 0x393C1528, 0x80002201, 0x00000000, 0x00000000, 0x00000000,
    0xE145045B, 0x383B1B50, 0xA146045B, 0x383B1E1D, 0xE147045B, 0x383B2048, 0xE148045B, 0x383B4458,
    0xE17B045B, 0x103B4500, 0xA17C045B, 0x103B460D, 0xE17D045B, 0x103B4730, 0xE17E045B, 0x103B4828,
    0x80000101, 0x00000000, 0x00000000, 0x00000000, 0x00030131, 0x00000004, 0x600E7F0C, 0x02007744,
];

static MAXPIX_PS_CODE: [u32; 16] = [
    0x00040061, 0x7E054AA0, 0x00000000, 0x3EB33333, 0x00040061, 0x78054AA0, 0x00000000, 0x3F47AE14,
    0xA07A0061, 0x3F810000, 0xA07C0061, 0x3F810000, 0x00040132, 0x00000004, 0x50007E14, 0x00C47834,
];

static MAXPIX_PIPELINE: TrianglePipeline = TrianglePipeline {
    vs: TriangleVertexShader {
        code: &MAXPIX_VS_CODE,
        meta: TriangleVertexShaderMetadata {
            kernel: ShaderKernelMetadata {
                code_offset_bytes: 0,
                code_size_bytes: 928,
                code_alignment_bytes: 64,
                ksp_offset_bytes: 0,
                dispatch_mode: DispatchMode::Simd8,
                grf_start_register: 2,
                grf_used: 128,
                push_constant_bytes: 0,
                binding_table_entry_count: 4,
                sampler_count: 0,
            },
            max_threads: 546,
            urb_entry_output_length: 1,
        },
    },
    ps: TrianglePixelShader {
        code: &MAXPIX_PS_CODE,
        meta: TrianglePixelShaderMetadata {
            kernel: ShaderKernelMetadata {
                code_offset_bytes: 960,
                code_size_bytes: 64,
                code_alignment_bytes: 64,
                ksp_offset_bytes: 0,
                dispatch_mode: DispatchMode::Simd16,
                grf_start_register: 2,
                grf_used: 128,
                push_constant_bytes: 0,
                binding_table_entry_count: 1,
                sampler_count: 0,
            },
            num_varying_inputs: 0,
            uses_vmask: true,
            computed_stencil: false,
            persample_dispatch: false,
            computed_depth_mode: 0,
            flat_inputs: 0,
        },
    },
};

pub(crate) fn pipeline() -> &'static TrianglePipeline {
    &MAXPIX_PIPELINE
}

