#!/usr/bin/env python3
"""Bake GPU fixed-function GL VS/PS for ADL-S through the compile-only Mesa shim."""

from __future__ import annotations

import argparse
import hashlib
import importlib.util
import json
import os
from pathlib import Path
import re
import shutil
import struct
import subprocess
import sys


ROOT = Path(__file__).resolve().parents[2]
HERE = Path(__file__).resolve().parent
DEFAULT_MESA = ROOT / ".codex_tmp/trueos-adj-instrumented-rpls/mesa-build"
OUT = ROOT / "crates/trueos-shader/wc3_fixed"
GENERATED = ROOT / "crates/trueos-shader/generated_wc3_fixed.rs"


def load_baker():
    sys.dont_write_bytecode = True
    spec = importlib.util.spec_from_file_location("trueos_helio_baker", ROOT / "tools/helio-intel-bake/bake.py")
    assert spec is not None and spec.loader is not None
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def decode(binary: Path) -> str:
    result = subprocess.run(
        ["iga64", "-d", "-p=12p1", "-Xprint-pc", str(binary)],
        text=True, stdout=subprocess.PIPE, stderr=subprocess.STDOUT, check=False,
    )
    if result.returncode or "illegal" in result.stdout.lower():
        raise SystemExit(f"invalid ADL-S EU ISA in {binary}:\n{result.stdout}")
    return "\n".join(line.rstrip() for line in result.stdout.splitlines()) + "\n"


def emit_rust(vs: bytes, ps: bytes, state: dict[str, int], ps_state: dict[str, int]) -> None:
    def words(name: str, binary: bytes) -> str:
        values = struct.unpack(f"<{len(binary) // 4}I", binary)
        rows = ["    " + ", ".join(f"0x{word:08X}" for word in values[index:index + 8]) + ","
                for index in range(0, len(values), 8)]
        return f"static {name}: [u32; {len(values)}] = [\n" + "\n".join(rows) + "\n];\n"

    generated = "// @generated by tools/wc3-fixed-bake/bake.py; ADL-S. Compile-only.\n" +         "use super::{DispatchMode, ShaderKernelMetadata, TrianglePipeline, TrianglePixelShader, TrianglePixelShaderMetadata, TriangleVertexShader, TriangleVertexShaderMetadata};\n"
    generated += words("WC3_FIXED_VS_CODE", vs) + "\n"
    generated += words("WC3_FIXED_PS_SIMD16_CODE", ps) + "\n"
    generated += f'''static WC3_FIXED_TEXTURE_PIPELINE: TrianglePipeline = TrianglePipeline {{
    vs: TriangleVertexShader {{
        code: &WC3_FIXED_VS_CODE,
        meta: TriangleVertexShaderMetadata {{
            kernel: ShaderKernelMetadata {{
                code_offset_bytes: 0,
                code_size_bytes: {len(vs)},
                code_alignment_bytes: 64,
                ksp_offset_bytes: 0,
                dispatch_mode: DispatchMode::Simd8,
                grf_start_register: {state["dispatch_grf_start"]},
                grf_used: 128,
                push_constant_bytes: 0,
                binding_table_entry_count: {state["binding_table_entries"]},
                sampler_count: 0,
            }},
            max_threads: {state["max_threads"]},
            urb_entry_output_length: {state["urb_entry_64b"]},
        }},
    }},
    ps: TrianglePixelShader {{
        code: &WC3_FIXED_PS_SIMD16_CODE,
        meta: TrianglePixelShaderMetadata {{
            kernel: ShaderKernelMetadata {{
                code_offset_bytes: {(len(vs) + 63) & ~63},
                code_size_bytes: {len(ps)},
                code_alignment_bytes: 64,
                ksp_offset_bytes: 0,
                dispatch_mode: DispatchMode::Simd16,
                grf_start_register: {ps_state["grf_start16"]},
                grf_used: 128,
                push_constant_bytes: 0,
                binding_table_entry_count: {ps_state["binding_table_entries"]},
                sampler_count: {ps_state["sampler_count"]},
            }},
            num_varying_inputs: {ps_state["num_varying_inputs"]},
            uses_vmask: {str(bool(ps_state["uses_vmask"])).lower()},
            computed_stencil: false,
            persample_dispatch: false,
            computed_depth_mode: 0,
            flat_inputs: 0,
        }},
    }},
}};

pub(crate) fn wc3_fixed_pipeline() -> &'static TrianglePipeline {{
    &WC3_FIXED_TEXTURE_PIPELINE
}}

'''
    GENERATED.write_text(generated)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--mesa-build", type=Path, default=DEFAULT_MESA)
    parser.add_argument("--work-dir", type=Path, default=ROOT / "bld/wc3-fixed-bake")
    args = parser.parse_args()
    mesa = args.mesa_build.resolve()
    shim = mesa / "src/intel/tools/libintel_noop_drm_shim.so"
    driver = mesa / "src/intel/vulkan/libvulkan_intel.so"
    if not shim.is_file() or not driver.is_file():
        raise SystemExit("--mesa-build must contain ANV and libintel_noop_drm_shim.so")
    work = args.work_dir.resolve()
    work.mkdir(parents=True, exist_ok=True)
    baker = load_baker()

    stages = []
    for stage in ("vert", "frag"):
        spv = work / f"fixed.{stage}.spv"
        subprocess.run(["glslc", "--target-env=vulkan1.1", str(HERE / "shaders" / f"fixed.{stage}"), "-o", str(spv)], check=True)
        stages.append(spv)

    source_path = work / "pipeline_dump.c"
    baker.make_churn_compile_only_dumper(source_path)
    source = source_path.read_text()
    source = baker.replace_once(source, '.pName = "vs_main",', '.pName = "main",')
    source = baker.replace_once(source, '.pName = "fs_main",', '.pName = "main",')
    source = baker.replace_once(source, ".stride = 24,", ".stride = 64,")
    source = source.replace("VK_FORMAT_R32G32B32_SFLOAT, .offset = 0", "VK_FORMAT_R32G32B32A32_SFLOAT, .offset = 0")
    source = source.replace("{ .location = 1, .binding = 0, .format = VK_FORMAT_R32G32B32_SFLOAT, .offset = 12 },",
        "{ .location = 1, .binding = 0, .format = VK_FORMAT_R32G32B32A32_SFLOAT, .offset = 16 },"
        "{ .location = 2, .binding = 0, .format = VK_FORMAT_R32G32B32A32_SFLOAT, .offset = 32 },"
        "{ .location = 3, .binding = 0, .format = VK_FORMAT_R32G32B32A32_SFLOAT, .offset = 48 },")
    source = source.replace("attributes[2]", "attributes[4]").replace(".vertexAttributeDescriptionCount = 2", ".vertexAttributeDescriptionCount = 4")
    source = baker.replace_once(source, "const VkDescriptorSetLayoutBinding storage_bindings[3]", "const VkDescriptorSetLayoutBinding storage_bindings[5]")
    source = baker.replace_once(source,
        "{ .binding = 2, .descriptorType = VK_DESCRIPTOR_TYPE_STORAGE_BUFFER,\n          .descriptorCount = 1, .stageFlags = VK_SHADER_STAGE_VERTEX_BIT },",
        "{ .binding = 2, .descriptorType = VK_DESCRIPTOR_TYPE_STORAGE_BUFFER,\n          .descriptorCount = 1, .stageFlags = VK_SHADER_STAGE_VERTEX_BIT },\n"
        "        { .binding = 3, .descriptorType = VK_DESCRIPTOR_TYPE_SAMPLED_IMAGE,\n          .descriptorCount = 1, .stageFlags = VK_SHADER_STAGE_FRAGMENT_BIT },\n"
        "        { .binding = 4, .descriptorType = VK_DESCRIPTOR_TYPE_SAMPLER,\n          .descriptorCount = 1, .stageFlags = VK_SHADER_STAGE_FRAGMENT_BIT },")
    source = baker.replace_once(source, ".bindingCount = 3,", ".bindingCount = 5,")
    source = source.replace(".stageFlags = VK_SHADER_STAGE_VERTEX_BIT", ".stageFlags = VK_SHADER_STAGE_VERTEX_BIT | VK_SHADER_STAGE_FRAGMENT_BIT")
    source_path.write_text(source)
    dumper = work / "pipeline_dump"
    subprocess.run(["cc", str(source_path), "-o", str(dumper), *baker.vulkan_compile_flags()], check=True)
    icd = work / "adls-icd.json"
    icd.write_text(json.dumps({"file_format_version": "1.0.1", "ICD": {"api_version": "1.4.346", "library_path": str(driver)}}))
    executable_dir = work / "intel"
    executable_dir.mkdir(exist_ok=True)
    for filename in ("vertex_TRUEOS_VS_state_v1.txt", "fragment_TRUEOS_PS_state_v1.txt"):
        (executable_dir / filename).unlink(missing_ok=True)
    env = os.environ.copy()
    env.update({
        "LD_PRELOAD": str(shim), "VK_DRIVER_FILES": str(icd),
        "VK_ICD_FILENAMES": str(icd), "INTEL_STUB_GPU_DEVICE_ID": "4680",
        "TRUEOS_VK_DEVICE_ID": "0x4680", "MESA_SHADER_CACHE_DISABLE": "true",
        "TRUEOS_EXECUTABLE_DUMP_DIR": str(executable_dir),
    })
    log = work / "compile.log"
    baker.run([str(dumper), *(str(path) for path in stages)], env=env, log=log)
    log_text = log.read_text()
    device, executables = baker.parse_compile_log(log_text)
    if device["device_id"] != 0x4680 or "helio_pipeline_dump: compiled_only=1" not in log_text:
        raise SystemExit("missing target-matched compile-only proof")
    vs, _, linked_ps16 = baker.extract_native(executable_dir, work / "native")
    ps = linked_ps16
    state_path = executable_dir / "vertex_TRUEOS_VS_state_v1.txt"
    if not state_path.is_file():
        raise SystemExit("Mesa lacks VS metadata capture; apply mesa-vs-capture.patch and rebuild ANV")
    state = {key: int(value, 0) for key, value in re.findall(r"(\w+)=(0x[0-9a-fA-F]+|\d+)", state_path.read_text())}
    ps_state_path = executable_dir / "fragment_TRUEOS_PS_state_v1.txt"
    if not ps_state_path.is_file():
        raise SystemExit("Mesa lacks PS metadata capture; apply mesa-ps-capture.patch and rebuild ANV")
    ps_state = {key: int(value, 0) for key, value in re.findall(r"(\w+)=(0x[0-9a-fA-F]+|\d+)", ps_state_path.read_text())}
    expected_vs = dict(ver=12, verx10=120, dispatch_grf_start=2, urb_read_length=2,
        urb_entry_64b=2, vue_slots=5, position_slot=1, uv_slot=2, vf_packing0=0xffff,
        uses_vertexid=0, uses_instanceid=0, binding_table_entries=2, sampler_count=0)
    expected_ps = dict(ver=12, verx10=120, dispatch16=1, grf_start16=6, num_varying_inputs=3,
        barycentric_interp_modes=1, uses_vmask=1, uses_src_depth=0, uses_src_w=0,
        computed_depth_mode=0, computed_stencil=0, flat_inputs=0, binding_table_entries=4,
        sampler_count=0, push_bytes=0, scratch_bytes=0)
    for captured, expected in [(state, expected_vs), (ps_state, expected_ps)]:
        if any(captured.get(k) != v for k,v in expected.items()):
            raise SystemExit(f"fixed GL compiler contract drift: {captured}")
    if "location0_slot=2 location1_slot=3 location2_slot=4" not in state_path.read_text():
        raise SystemExit("fixed GL VUE routing drift")
    if "location0_attribute=0 location1_attribute=1 location2_attribute=2" not in ps_state_path.read_text():
        raise SystemExit("fixed GL PS routing drift")
    vs_path = work / "fixed.vs.simd8.bin"
    vs_path.write_bytes(vs)
    ps_path = work / "fixed.ps.simd16.bin"
    ps_path.write_bytes(ps)
    vs_isa, ps_isa = decode(vs_path), decode(ps_path)
    for assembly, target, expected in ((vs_isa, 'dc0', 1),
                                       (ps_isa, 'smpl', 2), (ps_isa, 'dc0', 3)):
        descriptors = re.findall(
            rf'send\.{target}\s+[^\n]*?0x[0-9a-fA-F]+\s+0x([0-9a-fA-F]+)', assembly)
        if not descriptors or {int(value, 16) & 0xff for value in descriptors} != {expected}:
            raise SystemExit(f"fixed GL {target} binding drift; expected BTI{expected}")
    vertex_assembly, = executable_dir.glob("*_vertex_*_GEN_Assembly.txt")
    if (len(vs) != baker.assembly_code_size(vertex_assembly)
        or len(re.findall(r"^/\* \[[0-9A-Fa-f]+\]", vs_isa, re.MULTILINE)) != baker.assembly_instruction_count(vertex_assembly)
        or re.search(r"send\.urb.*\{[^}\n]*EOT", vs_isa) is None):
        raise SystemExit("VS cache extraction did not match complete compiler assembly")
    if (re.search(r"send\.smpl\s+\(16\|[^\n]*simd16 (?:sample|ld)", ps_isa, re.IGNORECASE) is None
        or re.search(r"sendc?\.rc\s+\(16\|[^\n]*\{[^}\n]*EOT[^\n]*render target write SIMD16", ps_isa, re.IGNORECASE) is None):
        raise SystemExit("fixed GL PS does not contain SIMD16 sampler and RT EOT messages")

    OUT.mkdir(parents=True, exist_ok=True)
    (OUT / vs_path.name).write_bytes(vs)
    (OUT / ps_path.name).write_bytes(ps)
    (OUT / "fixed.vs.iga.txt").write_text(vs_isa)
    (OUT / "fixed.ps.simd16.iga.txt").write_text(ps_isa)
    shutil.copy2(vertex_assembly, OUT / "fixed.vs.mesa.txt")
    shutil.copy2(state_path, OUT / state_path.name)
    shutil.copy2(ps_state_path, OUT / ps_state_path.name)
    shutil.copy2(log, OUT / "compile.log")
    metadata = {
        "schema": 1, "contract": "wc3-fixed-v1", "device": device,
        "backend": "mesa-anv-noop-drm-shim-compile-only", "iga_platform": "12p1",
        "host_render_verified": False, "baremetal_verified": False,
        "vertex_stride_bytes": 64, "vertex_attributes": ["float32x4@0", "float32x4@16", "float32x4@32", "float32x4@48"],
        "vertex_input_components": "position4,normal4,color4,uv4", "vertex_varyings": ["smooth-vec4-primary@0", "smooth-vec4-uv@1", "smooth-float-fog@2"],
        "vertex_compiler_state": state,
        "fragment_compiler_state": ps_state,
        "sbe": {"read_offset_32b": 1, "read_length_32b": 2, "attributes": 3},
        "state_vec4_count": 96,
        "vs_sha256": hashlib.sha256(vs).hexdigest(), "ps_sha256": hashlib.sha256(ps).hexdigest(),
        "vs_bytes": len(vs), "ps_bytes": len(ps), "executables": list(executables.values()),
    }
    (OUT / "metadata.json").write_text(json.dumps(metadata, indent=2, sort_keys=True) + "\n")
    emit_rust(vs, ps, state, ps_state)
    # The public package identifier hashes source and its state-layout version.
    digest = 0xcbf29ce484222325
    for byte in b"wc3-fixed-v1:state96:vertex4x4" + (HERE / "shaders/fixed.vert").read_bytes() + (HERE / "shaders/fixed.frag").read_bytes():
        digest = ((digest ^ byte) * 0x100000001b3) & 0xffffffffffffffff
    metadata["package_fnv1a64"] = f"0x{digest:016X}"
    (OUT / "metadata.json").write_text(json.dumps(metadata, indent=2, sort_keys=True) + "\n")
    print(json.dumps(metadata, indent=2, sort_keys=True))


if __name__ == "__main__":
    main()
