use std::env;
use std::fs;
use std::path::{Path, PathBuf};

use trueos_limloader::ensure_limine_from_manifest_dir;

fn first_existing(candidates: &[PathBuf]) -> Option<PathBuf> {
    candidates.iter().find(|p| p.is_file()).cloned()
}

fn write_xor_encoded(out_dir: &Path, src: &Path, dst_name: &str, key: u8) {
    println!("cargo:rerun-if-changed={}", src.display());
    fs::create_dir_all(out_dir).expect("create OUT_DIR");

    let mut bytes = fs::read(src).unwrap_or_else(|e| panic!("read {} failed: {e}", src.display()));
    for b in &mut bytes {
        *b ^= key;
    }

    let dst = out_dir.join(dst_name);
    fs::write(&dst, &bytes)
        .unwrap_or_else(|e| panic!("write {} failed: {e}", dst.display()));
}

fn main() {
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR"));
    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR"));

    // Ensure Limine is present/built for both ISO assembly and installer payload embedding.
    ensure_limine_from_manifest_dir(&manifest_dir);

    // These are produced by the Makefile's Limine build (bld/limine-build + bld/limine-prefix).
    // If you invoke cargo directly without running `make iso`, these may not exist.

    let bios_sys_candidates = [
        manifest_dir.join("bld/limine-prefix/share/limine/limine-bios.sys"),
        manifest_dir.join("bld/limine-build/limine-bios.sys"),
    ];

    let hdd_bin_candidates = [
        manifest_dir.join("bld/limine-build/bin/limine-bios-hdd.bin"),
        manifest_dir.join("bld/limine-prefix/share/limine/limine-bios-hdd.bin"),
    ];

    let bios_sys = first_existing(&bios_sys_candidates).unwrap_or_else(|| {
        panic!(
            "Missing limine-bios.sys. Build Limine first (e.g. run `make iso-debug`) and ensure Limine is configured with BIOS enabled. Looked in: {:?}",
            bios_sys_candidates
        )
    });

    let hdd_bin = first_existing(&hdd_bin_candidates).unwrap_or_else(|| {
        panic!(
            "Missing limine-bios-hdd.bin. Build Limine first (e.g. run `make iso-debug`) and ensure Limine is configured with BIOS enabled. Looked in: {:?}",
            hdd_bin_candidates
        )
    });

    // IMPORTANT: Limine scans the *kernel executable image* for request magic.
    // If we embed Limine binaries verbatim, those bytes can contain request magic too,
    // which can cause Limine to refuse to boot with "Conflict detected for request ID".
    // To avoid false positives, we XOR-encode the payload at build time and decode
    // it only when running the in-kernel installer.
    const XOR_KEY: u8 = 0xA5;
    write_xor_encoded(&out_dir, &bios_sys, "limine-bios.sys.xor", XOR_KEY);
    write_xor_encoded(&out_dir, &hdd_bin, "limine-bios-hdd.bin.xor", XOR_KEY);

    // Generate a small Rust module to include these binaries.
    let payload_rs = out_dir.join("install_payload.rs");
    let payload = r#"// @generated by build.rs
pub const INSTALL_XOR_KEY: u8 = 0xA5;
pub static LIMINE_BIOS_SYS_XOR: &[u8] = include_bytes!(concat!(env!("OUT_DIR"), "/limine-bios.sys.xor"));
pub static LIMINE_BIOS_HDD_BIN_XOR: &[u8] = include_bytes!(concat!(env!("OUT_DIR"), "/limine-bios-hdd.bin.xor"));
"#;
    fs::write(&payload_rs, payload).expect("write install_payload.rs");
    println!("cargo:rerun-if-changed=build.rs");
}
