use std::env;
use std::fs;
use std::io::Write;
use std::path::PathBuf;

use trueos_limloader::ensure_limine_from_manifest_dir;

fn write_xor_bytes(out: &mut dyn Write, bytes: &[u8], key: u8) {
    for (i, b) in bytes.iter().enumerate() {
        if i % 32 == 0 {
            let _ = writeln!(out);
            let _ = write!(out, "    ");
        }
        let _ = write!(out, "0x{:02x}, ", b ^ key);
    }
    let _ = writeln!(out);
}

fn main() {
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR"));

    // Keep these as explicit rerun triggers even when Limine is already built.
    // (The helper only prints rerun directives when it actually rebuilds.)
    println!("cargo:rerun-if-env-changed=TRUEOS_LIMINE_REPO");
    println!("cargo:rerun-if-env-changed=TRUEOS_LIMINE_REF");
    println!("cargo:rerun-if-env-changed=TRUEOS_LIMINE_CONFIG_ARGS");
    println!("cargo:rerun-if-env-changed=CARGO_NET_OFFLINE");

    // Ensure Limine is present/built for ISO assembly.
    ensure_limine_from_manifest_dir(&manifest_dir);

    // Build installer payload (Limine BIOS stages), embedded into the kernel.
    // src/install_assets.rs expects this module to exist.
    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR"));
    let limine_share = manifest_dir.join("bld").join("limine-prefix").join("share").join("limine");
    let limine_bios_sys_path = limine_share.join("limine-bios.sys");
    let limine_bios_hdd_bin_path = limine_share.join("limine-bios-hdd.bin");

    println!("cargo:rerun-if-changed={}", limine_bios_sys_path.display());
    println!("cargo:rerun-if-changed={}", limine_bios_hdd_bin_path.display());

    let limine_bios_sys = fs::read(&limine_bios_sys_path).unwrap_or_else(|e| {
        panic!(
            "failed to read Limine BIOS sys at {}: {e}",
            limine_bios_sys_path.display()
        )
    });
    let limine_bios_hdd_bin = fs::read(&limine_bios_hdd_bin_path).unwrap_or_else(|e| {
        panic!(
            "failed to read Limine BIOS HDD bin at {}: {e}\n\n\
Note: trueos-limloader should copy limine-bios-hdd.bin into bld/limine-prefix/share/limine/ \
when building Limine. If it didn't, try `make iso` once or delete bld/limine-build and rebuild.",
            limine_bios_hdd_bin_path.display()
        )
    });

    let install_xor_key: u8 = 0xA5;
    let gen_path = out_dir.join("install_payload.rs");
    let mut f = fs::File::create(&gen_path)
        .unwrap_or_else(|e| panic!("create {} failed: {e}", gen_path.display()));

    writeln!(
        &mut f,
        "// @generated by build.rs\n\
pub const INSTALL_XOR_KEY: u8 = 0x{:02x};\n\
pub static LIMINE_BIOS_SYS_XOR: &[u8] = &[",
        install_xor_key
    )
    .unwrap();
    write_xor_bytes(&mut f, &limine_bios_sys, install_xor_key);
    writeln!(&mut f, "];\n\
pub static LIMINE_BIOS_HDD_BIN_XOR: &[u8] = &[")
        .unwrap();
    write_xor_bytes(&mut f, &limine_bios_hdd_bin, install_xor_key);
    writeln!(&mut f, "];\n")
        .unwrap();

    println!("cargo:rerun-if-changed=build.rs");
}
