timeout: 0
default_entry: 1

/TRUEOS
protocol: limine
kernel_path: boot():/TRUEOS.elf
resolution: 1920x1080x32

# Installer helper modules (so the kernel can copy these bytes to a target disk).
module_path: boot():/TRUEOS.elf
module_string: trueos.install.kernel
module_path: boot():/EFI/BOOT/BOOTX64.EFI
module_string: trueos.install.bootx64
