// @generated by tools/clip-position3-uv-bake/bake.py; target ADL-S 8086:4680.
// VF payload: g2=x, g3=y, g4=z, g5=u, g6=v; no system-generated values.
// VUE: 16-byte header, position at slot 1, UV at slot 2; one 64-byte allocation.
// SBE: read offset 1/read length 1 (32-byte units), one perspective attribute.
// Fragment code is byte-identical to the existing Picasso sampled SIMD16 PS.
use super::{
    DispatchMode, ShaderKernelMetadata, TrianglePipeline, TrianglePixelShader,
    TrianglePixelShaderMetadata, TriangleVertexShader, TriangleVertexShaderMetadata,
};

static CLIP_POSITION3_UV_VS_CODE: [u32; 56] = [
    0x00030061, 0x07054660, 0x00000000, 0x00000000, 0x00030061, 0x08054660, 0x00000000, 0x00000000,
    0x00030061, 0x09054660, 0x00000000, 0x00000000, 0x00030061, 0x0A054660, 0x00000000, 0x00000000,
    0x00030061, 0x0B050660, 0x00460205, 0x00000000, 0x00030061, 0x0C050660, 0x00460305, 0x00000000,
    0x00030061, 0x0D050660, 0x00460405, 0x00000000, 0x00030061, 0x0E054660, 0x00000000, 0x3F800000,
    0x00039031, 0x00000000, 0x600E010C, 0x02000744, 0x00030061, 0x7B050220, 0x00460505, 0x00000000,
    0x00030061, 0x7C050220, 0x00460605, 0x00000000, 0x80033061, 0x7F050220, 0x00460105, 0x00000000,
    0x80000101, 0x00000000, 0x00000000, 0x00000000, 0x00030131, 0x00000004, 0x604E7F0C, 0x02007B24,
];

static SAMPLED_TEXTURE_PS_SIMD16_CODE: [u32; 40] = [
    0x640B0061, 0x00100200, 0x640C0061, 0x00100400, 0x64000061, 0x00100300, 0x64010061, 0x00100500,
    0x80000101, 0x00000000, 0x00000000, 0x00000000, 0x0004005B, 0x020402A0, 0x02020664, 0x00050624,
    0x0004005B, 0x070402A0, 0x020206E4, 0x000506A4, 0x80000201, 0x00000000, 0x00000000, 0x00000000,
    0x2004005B, 0x060B0201, 0x2009025B, 0x060B0771, 0x00049031, 0x78440000, 0x20040414, 0x01000914,
    0x80002001, 0x00000000, 0x00000000, 0x00000000, 0x00040132, 0x00000004, 0x50007844, 0x00C40000,
];

static CLIP_POSITION3_UV_TEXTURE_PIPELINE: TrianglePipeline = TrianglePipeline {
    vs: TriangleVertexShader {
        code: &CLIP_POSITION3_UV_VS_CODE,
        meta: TriangleVertexShaderMetadata {
            kernel: ShaderKernelMetadata {
                code_offset_bytes: 0,
                code_size_bytes: 224,
                code_alignment_bytes: 64,
                ksp_offset_bytes: 0,
                dispatch_mode: DispatchMode::Simd8,
                grf_start_register: 2,
                grf_used: 128,
                push_constant_bytes: 0,
                binding_table_entry_count: 0,
                sampler_count: 0,
            },
            max_threads: 546,
            urb_entry_output_length: 1,
        },
    },
    ps: TrianglePixelShader {
        code: &SAMPLED_TEXTURE_PS_SIMD16_CODE,
        meta: TrianglePixelShaderMetadata {
            kernel: ShaderKernelMetadata {
                code_offset_bytes: 256,
                code_size_bytes: 160,
                code_alignment_bytes: 64,
                ksp_offset_bytes: 0,
                dispatch_mode: DispatchMode::Simd16,
                grf_start_register: 2,
                grf_used: 128,
                push_constant_bytes: 0,
                binding_table_entry_count: 3,
                sampler_count: 1,
            },
            num_varying_inputs: 1,
            uses_vmask: true,
            computed_stencil: false,
            persample_dispatch: false,
            computed_depth_mode: 0,
            flat_inputs: 0,
        },
    },
};

pub(crate) fn clip_position3_uv_texture_pipeline() -> &'static TrianglePipeline {
    &CLIP_POSITION3_UV_TEXTURE_PIPELINE
}
