pub const D3D_COLOR_BUFFER_BLEND_FACTOR: [Option<&str>; 32] = [
    None,
    Some("BLENDFACTOR_ONE"),
    Some("BLENDFACTOR_SRC_COLOR"),
    Some("BLENDFACTOR_SRC_ALPHA"),
    Some("BLENDFACTOR_DST_ALPHA"),
    Some("BLENDFACTOR_DST_COLOR"),
    Some("BLENDFACTOR_SRC_ALPHA_SATURATE"),
    Some("BLENDFACTOR_CONST_COLOR"),
    Some("BLENDFACTOR_CONST_ALPHA"),
    Some("BLENDFACTOR_SRC1_COLOR"),
    Some("BLENDFACTOR_SRC1_ALPHA"),
    None,
    None,
    None,
    None,
    None,
    None,
    Some("BLENDFACTOR_ZERO"),
    Some("BLENDFACTOR_INV_SRC_COLOR"),
    Some("BLENDFACTOR_INV_SRC_ALPHA"),
    Some("BLENDFACTOR_INV_DST_ALPHA"),
    Some("BLENDFACTOR_INV_DST_COLOR"),
    None,
    Some("BLENDFACTOR_INV_CONST_COLOR"),
    Some("BLENDFACTOR_INV_CONST_ALPHA"),
    Some("BLENDFACTOR_INV_SRC1_COLOR"),
    Some("BLENDFACTOR_INV_SRC1_ALPHA"),
    None,
    None,
    None,
    None,
    None,
];

pub fn d3d_color_buffer_blend_factor(value: u8) -> Option<&'static str> {
    D3D_COLOR_BUFFER_BLEND_FACTOR
        .get(value as usize)
        .copied()
        .flatten()
}

/*
3D_Color_Buffer_Blend_Function
3D_Compare_Function
3D_Logic_Op_Function
3D_Prim_Topo_Type
3D_Stencil_Operation
3D_Vertex_Component_Control
AccWrCtrl
AddrMode
AtomicCtrl
Attribute_Component_Format
ChanOff
COMPONENT_ENABLES
DPASOperandPrecision
EU_OPCODE
ExecSize
Fixed_Function_ID
FlagModifier
GW_FENCE_PORTS
HorzStride
ImmDataType
MathFC
MediaCompressionFormat
Performance_Counter_Report_Formats
PredCtrl
PREFERRED_SLM_SIZE
RegDataType
Registers_Per_Thread
RENDER_BARRIER_STAGE
RENDER_BARRIER_TYPE
RenderCompressionFormat
Saturate
SFID
Shader_Channel_Select
SIMD_Mode
Slice_Hash_Control
SrcMod
SURFACE_FORMAT
SyncFC
TernaryDataType
TernaryVertStride
Texture_Coordinate_Mode
VertStride
Width
WRAP_SHORTEST_ENABLE
*/
