const COPY_RECT_RGBA8_ADLS_GPU: u64 = 0x0D20_0000;
const SPRITE_QUAD_WORKLIST_RGBA8_ADLS_GPU: u64 = 0x0D37_0000;
const UI4_COMPOSE_LAYERS_RGBA8_ADLS_GPU: u64 = 0x0D3E_0000;
const MANDEL64_WORKLIST_RGBA8_ADLS_GPU: u64 = 0x0D36_0000;
const FILL_RECT_RGBA8_ADLS_GPU: u64 = 0x0D2B_0000;

const GLYPH_MASK_RGBA8_ADLS_GPU: u64 = 0x0D2D_0000;
const FILL_RECT_WORKLIST_RGBA8_ADLS_GPU: u64 = 0x0D2F_0000;
const ALPHA_BLEND_WORKLIST_RGBA8_ADLS_GPU: u64 = 0x0D30_0000;
const GRADIENT_RECT_WORKLIST_RGBA8_ADLS_GPU: u64 = 0x0D31_0000;
const SKYBOX_SAMPLE_RGB565_ADLS_GPU: u64 = 0x0D38_0000;
const CHART_SINE_RGBA8_ADLS_GPU: u64 = 0x0D39_0000;
const PIXEL_PLASMA_RGBA8_ADLS_GPU: u64 = 0x0D3A_0000;
const FONT_OUTLINE_COVERAGE_R8_ADLS_GPU: u64 = 0x0D3D_0000;
const UI4_NV12_TILE64_TO_RGBA8_FRAME_ADLS_GPU: u64 = 0x0D40_0000;
const UI4_RGBA8_TO_NV12_LINEAR_ADLS_GPU: u64 = 0x0D41_8000;
const LAB256_MULTIPHASE_ADLS_GPU: u64 = 0x0D42_0000;
const SPIRIT_VFX_BACKGROUND_RGBA8_ADLS_GPU: u64 = 0x0D43_0000;
// Give both Spirit images dedicated, non-overlapping instruction windows.
const SPIRIT_VFX_SPRITE_RGBA8_ADLS_GPU: u64 = 0x0D45_0000;
const FONT_INSTANCE_RGBA8_ADLS_GPU: u64 = 0x0D50_0000;
// The C++ Spirit sprite image extends through 0x0D4F_xxxx. Keep the standalone
// demo comfortably outside Spirit's shared instruction-base window.
const CPP_DEMO_RGBA8_ADLS_GPU: u64 = 0x0D60_0000;
const CPP_AUDIO_VISUALIZER_RGBA8_ADLS_GPU: u64 = 0x0D70_0000;
const PARTICLE_CRAFT_ADLS_GPU: u64 = 0x0D78_0000;
const LFM25_Q8_PROJECT_PACKED_ADLS_GPU: u64 = 0x0D80_0000;
const KOKORO_QGEMM_U8_I8_ADLS_GPU: u64 = 0x0D90_0000;
const KOKORO_CONV1D_U8_U8_ADLS_GPU: u64 = 0x0DA0_0000;
const HELIO_RETAINED_TRANSFORM_ADLS_GPU: u64 = 0x0DB0_0000;
const SHADERTOY_MANDELBROT_ADLS_GPU: u64 = 0x0DC0_0000;
const SHADERTOY_CUBE_FIELD_ADLS_GPU: u64 = 0x0DD0_0000;
const SHADERTOY_NGUYEN_ADLS_GPU: u64 = 0x0DE0_0000;
const _: () = {
    assert!(
        SPIRIT_VFX_BACKGROUND_RGBA8_ADLS_GPU + SPIRIT_VFX_BACKGROUND_RGBA8_ADLS_BIN.len() as u64
            <= SPIRIT_VFX_SPRITE_RGBA8_ADLS_GPU
    );
    assert!(
        SPIRIT_VFX_SPRITE_RGBA8_ADLS_GPU + SPIRIT_VFX_SPRITE_RGBA8_ADLS_BIN.len() as u64
            <= FONT_INSTANCE_RGBA8_ADLS_GPU
    );
    assert!(
        FONT_INSTANCE_RGBA8_ADLS_GPU + FONT_INSTANCE_RGBA8_ADLS_BIN.len() as u64
            <= CPP_DEMO_RGBA8_ADLS_GPU
    );
    assert!(
        CPP_DEMO_RGBA8_ADLS_GPU + CPP_DEMO_RGBA8_ADLS_BIN.len() as u64
            <= CPP_AUDIO_VISUALIZER_RGBA8_ADLS_GPU
    );
    assert!(
        CPP_AUDIO_VISUALIZER_RGBA8_ADLS_GPU + CPP_AUDIO_VISUALIZER_RGBA8_ADLS_BIN.len() as u64
            <= PARTICLE_CRAFT_ADLS_GPU
    );
    assert!(
        PARTICLE_CRAFT_ADLS_GPU + PARTICLE_CRAFT_ADLS_BIN.len() as u64
            <= LFM25_Q8_PROJECT_PACKED_ADLS_GPU
    );
    assert!(
        LFM25_Q8_PROJECT_PACKED_ADLS_GPU
            + ((LFM25_Q8_PROJECT_PACKED_ADLS_BIN.len() as u64 + 4095) & !4095)
            <= KOKORO_QGEMM_U8_I8_ADLS_GPU
    );
    assert!(
        KOKORO_QGEMM_U8_I8_ADLS_GPU + ((KOKORO_QGEMM_U8_I8_ADLS_BIN.len() as u64 + 4095) & !4095)
            <= KOKORO_CONV1D_U8_U8_ADLS_GPU
    );
    assert!(
        KOKORO_CONV1D_U8_U8_ADLS_GPU + ((KOKORO_CONV1D_U8_U8_ADLS_BIN.len() as u64 + 4095) & !4095)
            <= HELIO_RETAINED_TRANSFORM_ADLS_GPU
    );
    assert!(
        HELIO_RETAINED_TRANSFORM_ADLS_GPU
            + ((HELIO_RETAINED_TRANSFORM_ADLS_BIN.len() as u64 + 4095) & !4095)
            <= SHADERTOY_MANDELBROT_ADLS_GPU
    );
    assert!(
        SHADERTOY_MANDELBROT_ADLS_GPU
            + ((SHADERTOY_MANDELBROT_ADLS_BIN.len() as u64 + 4095) & !4095)
            <= SHADERTOY_CUBE_FIELD_ADLS_GPU
    );
    assert!(
        SHADERTOY_CUBE_FIELD_ADLS_GPU
            + ((SHADERTOY_CUBE_FIELD_ADLS_BIN.len() as u64 + 4095) & !4095)
            <= SHADERTOY_NGUYEN_ADLS_GPU
    );
    assert!(
        SHADERTOY_NGUYEN_ADLS_GPU + ((SHADERTOY_NGUYEN_ADLS_BIN.len() as u64 + 4095) & !4095)
            <= LFM25_Q8_MODEL_MAPPING_GPU_BASE
    );
};
pub(crate) const COPY_RECT_RGBA8_TEXT_OFFSET_BYTES: u64 =
    COPY_RECT_RGBA8_ADLS_CPP_ABI_CONTRACT.entry_offset;
const FONT_OUTLINE_COVERAGE_R8_TEXT_OFFSET_BYTES: u64 =
    FONT_OUTLINE_COVERAGE_R8_ADLS_CPP_ABI_CONTRACT.entry_offset;
const UI4_NV12_TILE64_TO_RGBA8_FRAME_TEXT_OFFSET_BYTES: u64 =
    UI4_NV12_TILE64_TO_RGBA8_FRAME_ADLS_CPP_ABI_CONTRACT.entry_offset;
const UI4_RGBA8_TO_NV12_LINEAR_TEXT_OFFSET_BYTES: u64 =
    UI4_RGBA8_TO_NV12_LINEAR_ADLS_CPP_ABI_CONTRACT.entry_offset;
const FILL_RECT_RGBA8_TEXT_OFFSET_BYTES: u64 = FILL_RECT_RGBA8_ADLS_CPP_ABI_CONTRACT.entry_offset;
const FILL_RECT_WORKLIST_RGBA8_TEXT_OFFSET_BYTES: u64 =
    FILL_RECT_WORKLIST_RGBA8_ADLS_CPP_ABI_CONTRACT.entry_offset;
const ALPHA_BLEND_WORKLIST_RGBA8_TEXT_OFFSET_BYTES: u64 =
    ALPHA_BLEND_WORKLIST_RGBA8_ADLS_CPP_ABI_CONTRACT.entry_offset;

const SPRITE_QUAD_WORKLIST_RGBA8_TEXT_OFFSET_BYTES: u64 =
    SPRITE_QUAD_WORKLIST_RGBA8_ADLS_CPP_ABI_CONTRACT.entry_offset;
const UI4_COMPOSE_LAYERS_RGBA8_TEXT_OFFSET_BYTES: u64 =
    UI4_COMPOSE_LAYERS_RGBA8_ADLS_CPP_ABI_CONTRACT.entry_offset;
const MANDEL64_WORKLIST_RGBA8_TEXT_OFFSET_BYTES: u64 =
    MANDEL64_WORKLIST_RGBA8_ADLS_CPP_ABI_CONTRACT.entry_offset;

const GLYPH_MASK_RGBA8_TEXT_OFFSET_BYTES: u64 = GLYPH_MASK_RGBA8_ADLS_CPP_ABI_CONTRACT.entry_offset;

const SKYBOX_SAMPLE_RGB565_TEXT_OFFSET_BYTES: u64 =
    SKYBOX_SAMPLE_RGB565_ADLS_CPP_ABI_CONTRACT.entry_offset;
const CHART_SINE_RGBA8_TEXT_OFFSET_BYTES: u64 = CHART_SINE_RGBA8_ADLS_CPP_ABI_CONTRACT.entry_offset;
const PIXEL_PLASMA_RGBA8_TEXT_OFFSET_BYTES: u64 =
    PIXEL_PLASMA_RGBA8_ADLS_CPP_ABI_CONTRACT.entry_offset;
const CPP_DEMO_RGBA8_TEXT_OFFSET_BYTES: u64 = CPP_DEMO_RGBA8_ADLS_CPP_ABI_CONTRACT.entry_offset;
const SHADERTOY_MANDELBROT_TEXT_OFFSET_BYTES: u64 =
    SHADERTOY_MANDELBROT_ADLS_CPP_ABI_CONTRACT.entry_offset;
const SHADERTOY_CUBE_FIELD_TEXT_OFFSET_BYTES: u64 =
    SHADERTOY_CUBE_FIELD_ADLS_CPP_ABI_CONTRACT.entry_offset;
const SHADERTOY_NGUYEN_TEXT_OFFSET_BYTES: u64 = SHADERTOY_NGUYEN_ADLS_CPP_ABI_CONTRACT.entry_offset;
const CPP_AUDIO_VISUALIZER_RGBA8_TEXT_OFFSET_BYTES: u64 =
    CPP_AUDIO_VISUALIZER_RGBA8_ADLS_CPP_ABI_CONTRACT.entry_offset;
const PARTICLE_CRAFT_STEP_TEXT_OFFSET_BYTES: u64 =
    PARTICLE_CRAFT_STEP_ADLS_CPP_ABI_CONTRACT.entry_offset;
const PARTICLE_CRAFT_BIN_TILES_TEXT_OFFSET_BYTES: u64 =
    PARTICLE_CRAFT_BIN_TILES_ADLS_CPP_ABI_CONTRACT.entry_offset;
const PARTICLE_CRAFT_RENDER_RGBA8_TEXT_OFFSET_BYTES: u64 =
    PARTICLE_CRAFT_RENDER_RGBA8_ADLS_CPP_ABI_CONTRACT.entry_offset;
const FONT_INSTANCE_RGBA8_TEXT_OFFSET_BYTES: u64 =
    FONT_INSTANCE_RGBA8_ADLS_CPP_ABI_CONTRACT.entry_offset;
const LFM25_Q8_PROJECT_PACKED_TEXT_OFFSET_BYTES: u64 =
    LFM25_Q8_PROJECT_PACKED_ADLS_CPP_ABI_CONTRACT.entry_offset;
const KOKORO_QGEMM_U8_I8_TEXT_OFFSET_BYTES: u64 =
    KOKORO_QGEMM_U8_I8_ADLS_CPP_ABI_CONTRACT.entry_offset;
const KOKORO_CONV1D_U8_U8_TEXT_OFFSET_BYTES: u64 =
    KOKORO_CONV1D_U8_U8_ADLS_CPP_ABI_CONTRACT.entry_offset;
const LAB256_STEP_TEXT_OFFSET_BYTES: u64 = LAB256_STEP_ADLS_CPP_ABI_CONTRACT.entry_offset;
const LAB256_REDUCE_TEXT_OFFSET_BYTES: u64 = LAB256_REDUCE_ADLS_CPP_ABI_CONTRACT.entry_offset;
const LAB256_COMPOSITE_TEXT_OFFSET_BYTES: u64 = LAB256_COMPOSITE_ADLS_CPP_ABI_CONTRACT.entry_offset;
const _: () = assert!(LAB256_STEP_TEXT_OFFSET_BYTES < LAB256_REDUCE_TEXT_OFFSET_BYTES);
const _: () = assert!(LAB256_REDUCE_TEXT_OFFSET_BYTES < LAB256_COMPOSITE_TEXT_OFFSET_BYTES);
const SPIRIT_VFX_BACKGROUND_TEXT_OFFSET_BYTES: u64 =
    SPIRIT_VFX_BACKGROUND_RGBA8_ADLS_CPP_ABI_CONTRACT.entry_offset;
// Both artifacts share one instruction-base window in the two-walker batch.
const SPIRIT_VFX_SPRITE_TEXT_OFFSET_BYTES: u64 = SPIRIT_VFX_SPRITE_RGBA8_ADLS_GPU
    - SPIRIT_VFX_BACKGROUND_RGBA8_ADLS_GPU
    + SPIRIT_VFX_SPRITE_RGBA8_ADLS_CPP_ABI_CONTRACT.entry_offset;

const RCS_RING_BASE: usize = 0x0000_2000;
const RCS_RING_TAIL: usize = RCS_RING_BASE + 0x30;
const RCS_RING_HEAD: usize = RCS_RING_BASE + 0x34;
const RCS_RING_START: usize = RCS_RING_BASE + 0x38;
const RCS_RING_CTL: usize = RCS_RING_BASE + 0x3C;
const RCS_RING_ACTHD: usize = RCS_RING_BASE + 0x74;
const RCS_RING_IPEIR: usize = RCS_RING_BASE + 0x64;
const RCS_RING_IPEHR: usize = RCS_RING_BASE + 0x68;
const RCS_RING_INSTDONE: usize = RCS_RING_BASE + 0x6C;
const RCS_RING_INSTPS: usize = RCS_RING_BASE + 0x70;
const RCS_RING_EIR: usize = RCS_RING_BASE + 0xB0;
const RCS_RING_MI_MODE: usize = RCS_RING_BASE + 0x9C;
const RCS_RING_MODE_GEN7: usize = RCS_RING_BASE + 0x29C;
const RCS_RING_CONTEXT_CONTROL: usize = RCS_RING_BASE + 0x244;
const RCS_RING_EXECLIST_CONTROL: usize = RCS_RING_BASE + 0x550;
const RCS_RING_EXECLIST_STATUS_LO: usize = RCS_RING_BASE + 0x234;
const RCS_RING_EXECLIST_STATUS_HI: usize = RCS_RING_BASE + 0x238;

const RCS_CS_DEBUG_MODE1: usize = RCS_RING_BASE + 0xEC;

const FORCEWAKE_RENDER: usize = 0x0A278;
const FORCEWAKE_GT: usize = 0x0A188;
const FORCEWAKE_ACK_RENDER: usize = 0x0D84;
const FORCEWAKE_ACK_GT: usize = 0x130044;
const FORCEWAKE_KERNEL: u32 = 1 << 0;
const FORCEWAKE_FALLBACK: u32 = 1 << 15;
const FORCEWAKE_POLL_ITERS: usize = 20_000;
const FF_DOP_CLOCK_GATE_DISABLE: u32 = 1 << 1;
const RING_VALID: u32 = 1;

const CTX_CTRL_ENGINE_CTX_RESTORE_INHIBIT: u32 = 1 << 0;
const CTX_CTRL_INHIBIT_SYN_CTX_SWITCH: u32 = 1 << 3;

const RING_MI_MODE_STOP_RING: u32 = 1 << 8;
const MI_BATCH_BUFFER_START_GEN8: u32 = (0x31 << 23) | 1;
const _: () = assert!(MI_BATCH_BUFFER_START_GEN8 == 0x1880_0001);
const MI_STORE_DATA_IMM_GGTT_DW1: u32 = 0x1040_0002;
const MI_LOAD_REGISTER_IMM: u32 = 0x1100_0000;
const MI_LRI_CS_MMIO: u32 = 1 << 19;
const MI_LRI_FORCE_POSTED: u32 = 1 << 12;
const MI_BATCH_BUFFER_END: u32 = 0x0500_0000;
const MI_NOOP: u32 = 0;
const INTEL_LEGACY_64B_CONTEXT: u32 = 3;
const GEN8_PAGE_RW: u64 = 1 << 1;
const GEN8_PAGE_PWT: u64 = 1 << 3;
const GEN8_PAGE_PCD: u64 = 1 << 4;
const GEN8_CTX_VALID: u32 = 1 << 0;

const GEN8_CTX_PRIVILEGE: u32 = 1 << 8;

const GEN8_CTX_ADDRESSING_MODE_SHIFT: u32 = 3;
const RENDER_MOCS_INDEX: u32 = 4;
const LFM25_RENDER_MOCS_INDEX: u32 = super::GEN12_LUMEN_MOCS_INDEX;
const RENDER_MOCS_TABLE_INDEX_MASK: u32 = 0x3F;
const RENDER_MOCS_COMMAND_VALUE_MASK: u32 = 0x7F;

// Gen12 command fields expose a reserved bit followed by the six-bit MOCS
// table index. Command builders conventionally represent that field as
// `table_index << 1`, keeping the reserved bit clear.
const fn direct_rcs_encode_mocs_index(index: u32) -> u32 {
    index << 1
}

const _: () = {
    assert!(RENDER_MOCS_INDEX <= RENDER_MOCS_TABLE_INDEX_MASK);
    assert!(LFM25_RENDER_MOCS_INDEX <= RENDER_MOCS_TABLE_INDEX_MASK);
    assert!(LFM25_RENDER_MOCS_INDEX >= 32);
    assert!(direct_rcs_encode_mocs_index(RENDER_MOCS_INDEX) == 8);
    assert!(direct_rcs_encode_mocs_index(LFM25_RENDER_MOCS_INDEX) == 98);
    assert!(
        direct_rcs_encode_mocs_index(LFM25_RENDER_MOCS_INDEX) <= RENDER_MOCS_COMMAND_VALUE_MASK
    );
};

// The dominant ConvInteger lane keeps one maximum MCK image, per-tap sums,
// one NCW halo tile, and one time-major output tile in a persistent arena.
// An 8,192-time tile covers the measured 6,361-time family in one dispatch
// and the 8,281-time ORT oracle in exactly two bounded dispatches.
const KOKORO_CONV1D_MAX_INPUT_TIMES: usize = 1 << 20;
const KOKORO_CONV1D_MAX_TILE_TIMES: usize = 8_192;
const KOKORO_CONV1D_MAX_CHANNELS: usize = 256;
const KOKORO_CONV1D_MAX_KERNEL_SIZE: usize = 11;
const KOKORO_CONV1D_MAX_RADIUS: usize = 25;
const KOKORO_CONV1D_PACKED_WEIGHTS_ALLOC_BYTES: usize = 0x000B_0000;
const KOKORO_CONV1D_WEIGHT_TAP_SUMS_ALLOC_BYTES: usize = 0x0000_3000;
const KOKORO_CONV1D_ACTIVATIONS_ALLOC_BYTES: usize = 0x0020_4000;
const KOKORO_CONV1D_OUTPUT_ALLOC_BYTES: usize = 0x0080_0000;
const KOKORO_CONV1D_PACKED_WEIGHTS_OFFSET_BYTES: usize = 0;
const KOKORO_CONV1D_WEIGHT_TAP_SUMS_OFFSET_BYTES: usize =
    KOKORO_CONV1D_PACKED_WEIGHTS_OFFSET_BYTES + KOKORO_CONV1D_PACKED_WEIGHTS_ALLOC_BYTES;
const KOKORO_CONV1D_ACTIVATIONS_OFFSET_BYTES: usize =
    KOKORO_CONV1D_WEIGHT_TAP_SUMS_OFFSET_BYTES + KOKORO_CONV1D_WEIGHT_TAP_SUMS_ALLOC_BYTES;
const KOKORO_CONV1D_OUTPUT_OFFSET_BYTES: usize =
    KOKORO_CONV1D_ACTIVATIONS_OFFSET_BYTES + KOKORO_CONV1D_ACTIVATIONS_ALLOC_BYTES;
const KOKORO_CONV1D_ARENA_BYTES: usize =
    KOKORO_CONV1D_OUTPUT_OFFSET_BYTES + KOKORO_CONV1D_OUTPUT_ALLOC_BYTES;
const KOKORO_CONV1D_ARENA_GPU: u64 = 0x2200_0000;
const KOKORO_CONV1D_ARENA_GPU_LIMIT: u64 = 0x2300_0000;

const KOKORO_CONV1D_IDD_OFFSET_BYTES: usize = 0x7800;
const KOKORO_CONV1D_BINDING_TABLE_OFFSET_BYTES: usize = 0x7840;
const KOKORO_CONV1D_PACKED_WEIGHTS_SURFACE_OFFSET_BYTES: usize = 0x7880;
const KOKORO_CONV1D_WEIGHT_TAP_SUMS_SURFACE_OFFSET_BYTES: usize = 0x78C0;
const KOKORO_CONV1D_ACTIVATIONS_SURFACE_OFFSET_BYTES: usize = 0x7900;
const KOKORO_CONV1D_OUTPUT_SURFACE_OFFSET_BYTES: usize = 0x7940;
const KOKORO_CONV1D_PAYLOAD_OFFSET_BYTES: usize = 0x7C00;
const KOKORO_CONV1D_IDD_BYTES: usize = 8 * core::mem::size_of::<u32>();
const KOKORO_CONV1D_CROSS_THREAD_BYTES: usize =
    KOKORO_CONV1D_U8_U8_ADLS_CPP_ABI_CONTRACT.cross_thread_data_bytes as usize;
const KOKORO_CONV1D_PER_THREAD_BYTES: usize =
    KOKORO_CONV1D_U8_U8_ADLS_CPP_ABI_CONTRACT.per_thread_data_bytes as usize;
const KOKORO_CONV1D_INDIRECT_BYTES: usize =
    KOKORO_CONV1D_CROSS_THREAD_BYTES + KOKORO_CONV1D_PER_THREAD_BYTES;
const KOKORO_CONV1D_POST_MARKER_SLOT: usize = 60;
const KOKORO_CONV1D_PRE_MARKER_SLOT: usize = 62;
const KOKORO_CONV1D_POST_MARKER: u32 = 0xC0DE_7C02;
const KOKORO_CONV1D_PRE_MARKER: u32 = 0xC0DE_7C01;
const KOKORO_CONV1D_COMPLETION_TIMEOUT_MS: u64 = 5_000;

const _: () = {
    assert!(KOKORO_CONV1D_U8_U8_ADLS_CPP_ABI_CONTRACT.simd_width == 16);
    assert!(KOKORO_CONV1D_CROSS_THREAD_BYTES == 128);
    assert!(KOKORO_CONV1D_PER_THREAD_BYTES == 96);
    assert!(KOKORO_CONV1D_U8_U8_ADLS_CPP_ABI_CONTRACT.bindings.len() == 4);
    assert!(
        KOKORO_CONV1D_MAX_CHANNELS * KOKORO_CONV1D_MAX_CHANNELS * KOKORO_CONV1D_MAX_KERNEL_SIZE
            == KOKORO_CONV1D_PACKED_WEIGHTS_ALLOC_BYTES
    );
    assert!(
        KOKORO_CONV1D_MAX_CHANNELS * KOKORO_CONV1D_MAX_KERNEL_SIZE * core::mem::size_of::<u32>()
            <= KOKORO_CONV1D_WEIGHT_TAP_SUMS_ALLOC_BYTES
    );
    assert!(
        (KOKORO_CONV1D_MAX_TILE_TIMES + 2 * KOKORO_CONV1D_MAX_RADIUS) * KOKORO_CONV1D_MAX_CHANNELS
            <= KOKORO_CONV1D_ACTIVATIONS_ALLOC_BYTES
    );
    assert!(
        KOKORO_CONV1D_MAX_TILE_TIMES * KOKORO_CONV1D_MAX_CHANNELS * core::mem::size_of::<i32>()
            == KOKORO_CONV1D_OUTPUT_ALLOC_BYTES
    );
    assert!(KOKORO_CONV1D_ARENA_GPU.is_multiple_of(4096));
    assert!(KOKORO_CONV1D_ARENA_BYTES.is_multiple_of(4096));
    assert!(
        KOKORO_CONV1D_ARENA_GPU + KOKORO_CONV1D_ARENA_BYTES as u64 <= KOKORO_CONV1D_ARENA_GPU_LIMIT
    );
    assert!(KOKORO_CONV1D_ARENA_GPU_LIMIT <= DIRECT_RCS_PPGTT_LIMIT_BYTES);
    assert!(
        KOKORO_CONV1D_IDD_OFFSET_BYTES + KOKORO_CONV1D_IDD_BYTES
            <= KOKORO_CONV1D_BINDING_TABLE_OFFSET_BYTES
    );
    assert!(
        KOKORO_CONV1D_OUTPUT_SURFACE_OFFSET_BYTES
            + COPY_RECT_SURFACE_STATE_DWORDS * core::mem::size_of::<u32>()
            <= KOKORO_CONV1D_PAYLOAD_OFFSET_BYTES
    );
    assert!(
        KOKORO_CONV1D_PAYLOAD_OFFSET_BYTES + KOKORO_CONV1D_INDIRECT_BYTES <= DIRECT_RCS_BATCH_BYTES
    );
    assert!(
        KOKORO_CONV1D_PAYLOAD_OFFSET_BYTES.is_multiple_of(GPGPU_WALKER_INDIRECT_ALIGNMENT_BYTES)
    );
    assert!(KOKORO_CONV1D_POST_MARKER_SLOT.is_multiple_of(2));
    assert!(KOKORO_CONV1D_POST_MARKER_SLOT + 1 != KOKORO_CONV1D_PRE_MARKER_SLOT);
    assert!(
        (KOKORO_CONV1D_PRE_MARKER_SLOT + 1) * core::mem::size_of::<u32>()
            <= DIRECT_RCS_RESULT_BYTES
    );
};
const PIPE_CONTROL_CMD: u32 = 4 | (2 << 24) | (3 << 27) | (3 << 29);
const STATE_BASE_ADDRESS_CMD: u32 = 20 | (1 << 16) | (1 << 24) | (3 << 29);
const PIPE_CONTROL_DC_FLUSH_ENABLE: u32 = 1 << 5;
const PIPE_CONTROL_FLUSH_ENABLE: u32 = 1 << 7;
const PIPE_CONTROL_RENDER_TARGET_CACHE_FLUSH: u32 = 1 << 12;
const PIPE_CONTROL_DEPTH_CACHE_FLUSH: u32 = 1 << 0;
const PIPE_CONTROL_DEPTH_STALL: u32 = 1 << 13;
// Gen12 PIPE_CONTROL splits HDC pipeline drain from the DW1 cache controls:
// HDC Pipeline Flush is DW0 bit 9.  DW1 bit 26 is Flush LLC and is only legal
// with a post-sync immediate write; treating it as HDC allowed the completion
// marker to retire while data-port writes were still only partially visible to
// the next GuC context.
const PIPE_CONTROL_HDC_PIPELINE_FLUSH: u32 = 1 << 9;
const PIPE_CONTROL_POST_SYNC_WRITE_IMMEDIATE: u32 = 1 << 14;
const PIPE_CONTROL_POST_SYNC_WRITE_TIMESTAMP: u32 = 3 << 14;
const PIPE_CONTROL_CS_STALL: u32 = 1 << 20;
const PIPE_CONTROL_L3_FABRIC_FLUSH: u32 = 1 << 30;
const PIPE_CONTROL_TLB_INVALIDATE: u32 = 1 << 18;
const PIPE_CONTROL_STATE_CACHE_INVALIDATE: u32 = 1 << 2;
const PIPE_CONTROL_CONSTANT_CACHE_INVALIDATE: u32 = 1 << 3;
const PIPE_CONTROL_TEXTURE_CACHE_INVALIDATE: u32 = 1 << 10;
const PIPE_CONTROL_INSTRUCTION_CACHE_INVALIDATE: u32 = 1 << 11;
const PIPE_CONTROL_COMMAND_CACHE_INVALIDATE: u32 = 1 << 29;
const PIPE_CONTROL_FLUSH_BITS: u32 = PIPE_CONTROL_DC_FLUSH_ENABLE
    | PIPE_CONTROL_FLUSH_ENABLE
    | PIPE_CONTROL_CS_STALL
    // HDC drains data-port writes into L3. Scanout is a separate observer, so
    // force the stalling flush to carry every pending L3 transaction to the
    // global observation point before the completion marker can retire.
    | PIPE_CONTROL_L3_FABRIC_FLUSH;
const PIPE_CONTROL_INVALIDATE_BITS: u32 = PIPE_CONTROL_FLUSH_BITS
    | PIPE_CONTROL_TLB_INVALIDATE
    | PIPE_CONTROL_STATE_CACHE_INVALIDATE
    | PIPE_CONTROL_CONSTANT_CACHE_INVALIDATE
    | PIPE_CONTROL_TEXTURE_CACHE_INVALIDATE
    | PIPE_CONTROL_INSTRUCTION_CACHE_INVALIDATE
    | PIPE_CONTROL_COMMAND_CACHE_INVALIDATE;
const _: () = {
    // RCS GPGPU mode must not carry 3D-only RT/depth cache controls
    // (Wa_1606932921). The 3D->GPGPU prologue owns those flushes instead.
    assert!(PIPE_CONTROL_FLUSH_BITS == 0x4010_00A0);
    assert!(PIPE_CONTROL_FLUSH_BITS & PIPE_CONTROL_RENDER_TARGET_CACHE_FLUSH == 0);
    assert!(PIPE_CONTROL_FLUSH_BITS & PIPE_CONTROL_DEPTH_CACHE_FLUSH == 0);
};
const MEDIA_VFE_STATE_CMD: u32 = (3 << 29) | (2 << 27) | 7;
const MEDIA_INTERFACE_DESCRIPTOR_LOAD_CMD: u32 = (3 << 29) | (2 << 27) | (2 << 16) | 2;
const GPGPU_WALKER_CMD: u32 = (3 << 29) | (2 << 27) | (1 << 24) | (5 << 16) | 13;
const MEDIA_STATE_FLUSH_CMD: u32 = (3 << 29) | (2 << 27) | (4 << 16);
const PIPELINE_SELECT_BASE: u32 = (3 << 29) | (1 << 27) | (1 << 24) | (4 << 16);
const PIPELINE_SELECT_GFX12_MASK: u32 = 0x13 << 8;
const PIPELINE_SELECT_MEDIA_SAMPLER_DOP_CG_ENABLE: u32 = 1 << 4;
const PIPELINE_SELECT_3D: u32 =
    PIPELINE_SELECT_BASE | PIPELINE_SELECT_GFX12_MASK | PIPELINE_SELECT_MEDIA_SAMPLER_DOP_CG_ENABLE;
const PIPELINE_SELECT_GPGPU: u32 = PIPELINE_SELECT_3D | 2;
const IDD_THREAD_PREEMPTION_DISABLE: u32 = 1 << 20;
const GPGPU_VFE_DW3_UOS: u32 = 0x00A7_0100;
const GPGPU_VFE_DW5_UOS: u32 = 0x0782_0000;
const GPGPU_WALKER_GROUP_THREADS: u32 = 1;
const GPGPU_WALKER_SIMD16_SELECT: u32 = 1;
const FILL_RECT_PIXELS_PER_GROUP_X: u32 = 16;
const COPY_RECT_2D_COMPLETION_TIMEOUT_MS: u64 = 250;
const FILL_RECT_2D_COMPLETION_TIMEOUT_MS: u64 = 250;

const DIRECT_RCS_2D_COMPLETION_TIMEOUT_MS: u64 = 250;
const FONT_OUTLINE_COVERAGE_R8_COMPLETION_TIMEOUT_MS: u64 = 500;
const GPGPU_WALKER_GROUP_Z_DIM: u32 = 1;
const GPGPU_WALKER_SIMD16_MASK: u32 = 0x0000_FFFF;
const GPGPU_WALKER_BOTTOM_MASK: u32 = 0xFFFF_FFFF;

const COPY_RECT_BATCH_IDD_OFFSET_BYTES: usize = 0x1000;
const COPY_RECT_BATCH_BINDING_TABLE_OFFSET_BYTES: usize = 0x1040;
const COPY_RECT_BATCH_SRC_SURFACE_STATE_OFFSET_BYTES: usize = 0x1080;
const COPY_RECT_BATCH_DST_SURFACE_STATE_OFFSET_BYTES: usize = 0x10C0;
const COPY_RECT_BATCH_PAYLOAD_BASE_OFFSET_BYTES: usize = 0x1200;
const COPY_RECT_PIXELS_PER_LANE: u32 = 2;

// Native video uses either the proven three-surface primary conversion
// (source/base/destination) or the parked two-surface exact-Frame experiment.
const UI4_NV12_PRIMARY_IDD_OFFSET_BYTES: usize = 0x1000;
const UI4_NV12_PRIMARY_BINDING_TABLE_OFFSET_BYTES: usize = 0x1040;
const UI4_NV12_PRIMARY_SRC_SURFACE_STATE_OFFSET_BYTES: usize = 0x1080;
const UI4_NV12_PRIMARY_BASE_SURFACE_STATE_OFFSET_BYTES: usize = 0x10C0;
const UI4_NV12_PRIMARY_DST_SURFACE_STATE_OFFSET_BYTES: usize = 0x1100;
const UI4_NV12_PRIMARY_PAYLOAD_OFFSET_BYTES: usize = 0x1200;
const UI4_NV12_PRIMARY_CROSS_THREAD_GRFS: u32 = 4;
const UI4_NV12_PRIMARY_CROSS_THREAD_BYTES: usize = UI4_NV12_PRIMARY_CROSS_THREAD_GRFS as usize * 32;
const UI4_NV12_PRIMARY_PER_THREAD_BYTES: usize = 96;
const UI4_NV12_PRIMARY_INDIRECT_BYTES: usize =
    UI4_NV12_PRIMARY_CROSS_THREAD_BYTES + UI4_NV12_PRIMARY_PER_THREAD_BYTES;
const UI4_RGBA8_TO_NV12_CROSS_THREAD_BYTES: usize =
    UI4_RGBA8_TO_NV12_LINEAR_ADLS_CPP_ABI_CONTRACT.cross_thread_data_bytes as usize;
const UI4_RGBA8_TO_NV12_CROSS_THREAD_GRFS: u32 = (UI4_RGBA8_TO_NV12_CROSS_THREAD_BYTES / 32) as u32;
const UI4_RGBA8_TO_NV12_PER_THREAD_BYTES: usize =
    UI4_RGBA8_TO_NV12_LINEAR_ADLS_CPP_ABI_CONTRACT.per_thread_data_bytes as usize;
const UI4_RGBA8_TO_NV12_INDIRECT_BYTES: usize =
    UI4_RGBA8_TO_NV12_CROSS_THREAD_BYTES + UI4_RGBA8_TO_NV12_PER_THREAD_BYTES;
const _: () = {
    assert!(matches!(UI4_RGBA8_TO_NV12_LINEAR_ADLS_CPP_ABI_CONTRACT.validate(), Ok(())));
    assert!(UI4_RGBA8_TO_NV12_CROSS_THREAD_BYTES == 96);
    assert!(UI4_RGBA8_TO_NV12_CROSS_THREAD_GRFS == 3);
    assert!(UI4_RGBA8_TO_NV12_PER_THREAD_BYTES == 96);
};
const _: () = assert!(
    UI4_RGBA8_TO_NV12_LINEAR_ADLS_GPU + UI4_RGBA8_TO_NV12_LINEAR_ADLS_BIN.len() as u64
        <= LAB256_MULTIPHASE_ADLS_GPU
);

// GridPaper can retain 17 independently colored layers for each of its three
// font faces (51 total). Keep enough room to submit the complete scene once.
pub(crate) const GLYPH_MASK_BATCH_MAX_LAYERS: usize = 64;
const GLYPH_MASK_BATCH_STATE_BASE_OFFSET_BYTES: usize = 0x3000;
const GLYPH_MASK_BATCH_STATE_BLOCK_BYTES: usize = 0x100;
const GLYPH_MASK_BATCH_IDD_OFFSET_IN_BLOCK_BYTES: usize = 0x00;
const GLYPH_MASK_BATCH_BINDING_TABLE_OFFSET_IN_BLOCK_BYTES: usize = 0x40;
const GLYPH_MASK_BATCH_SRC_SURFACE_OFFSET_IN_BLOCK_BYTES: usize = 0x80;
const GLYPH_MASK_BATCH_DST_SURFACE_OFFSET_IN_BLOCK_BYTES: usize = 0xC0;
const GLYPH_MASK_BATCH_PAYLOAD_BASE_OFFSET_BYTES: usize = 0x8000;
const COPY_RECT_IDD_BYTES: usize = 8 * core::mem::size_of::<u32>();
const COPY_RECT_SURFACE_STATE_DWORDS: usize = 16;
const COPY_RECT_CROSS_THREAD_BYTES: usize = 96;
const COPY_RECT_PER_THREAD_BYTES: usize = 96;
const COPY_RECT_INDIRECT_BYTES: usize = COPY_RECT_CROSS_THREAD_BYTES + COPY_RECT_PER_THREAD_BYTES;

const GLYPH_MASK_CROSS_THREAD_BYTES: usize = 128;
const GLYPH_MASK_PER_THREAD_BYTES: usize = 96;
const GLYPH_MASK_INDIRECT_BYTES: usize =
    GLYPH_MASK_CROSS_THREAD_BYTES + GLYPH_MASK_PER_THREAD_BYTES;
// GPGPU_WALKER encodes the indirect-data start address at 64-byte
// granularity. The 224-byte payload itself is valid, but consecutive walkers
// must advance through aligned slots rather than using that raw byte count as
// the next start address.
const GPGPU_WALKER_INDIRECT_ALIGNMENT_BYTES: usize = 64;
const GLYPH_MASK_PAYLOAD_STRIDE_BYTES: usize =
    (GLYPH_MASK_INDIRECT_BYTES + GPGPU_WALKER_INDIRECT_ALIGNMENT_BYTES - 1)
        & !(GPGPU_WALKER_INDIRECT_ALIGNMENT_BYTES - 1);

const FONT_INSTANCE_BATCH_MAX_LAYERS: usize = GPGPU_FONT_INSTANCE_MAX_LAYERS;
const FONT_INSTANCE_BATCH_STATE_BASE_OFFSET_BYTES: usize = 0x3000;
const FONT_INSTANCE_BATCH_STATE_BLOCK_BYTES: usize = 0x140;
const FONT_INSTANCE_BATCH_IDD_OFFSET_IN_BLOCK_BYTES: usize = 0x00;
const FONT_INSTANCE_BATCH_BINDING_TABLE_OFFSET_IN_BLOCK_BYTES: usize = 0x40;
const FONT_INSTANCE_BATCH_MASK_SURFACE_OFFSET_IN_BLOCK_BYTES: usize = 0x80;
const FONT_INSTANCE_BATCH_DST_SURFACE_OFFSET_IN_BLOCK_BYTES: usize = 0xC0;
const FONT_INSTANCE_BATCH_DESC_SURFACE_OFFSET_IN_BLOCK_BYTES: usize = 0x100;
const FONT_INSTANCE_BATCH_PAYLOAD_BASE_OFFSET_BYTES: usize = 0x9000;
const FONT_INSTANCE_CROSS_THREAD_BYTES: usize =
    FONT_INSTANCE_RGBA8_ADLS_CPP_ABI_CONTRACT.cross_thread_data_bytes as usize;
const FONT_INSTANCE_PER_THREAD_BYTES: usize =
    FONT_INSTANCE_RGBA8_ADLS_CPP_ABI_CONTRACT.per_thread_data_bytes as usize;
const FONT_INSTANCE_INDIRECT_BYTES: usize =
    FONT_INSTANCE_CROSS_THREAD_BYTES + FONT_INSTANCE_PER_THREAD_BYTES;
const FONT_INSTANCE_PAYLOAD_STRIDE_BYTES: usize =
    (FONT_INSTANCE_INDIRECT_BYTES + GPGPU_WALKER_INDIRECT_ALIGNMENT_BYTES - 1)
        & !(GPGPU_WALKER_INDIRECT_ALIGNMENT_BYTES - 1);

const RECT_WORKLIST_IDD_OFFSET_BYTES: usize = 0x1400;
const RECT_WORKLIST_BINDING_TABLE_OFFSET_BYTES: usize = 0x1440;
const RECT_WORKLIST_SRC_SURFACE_STATE_OFFSET_BYTES: usize = 0x1480;
const RECT_WORKLIST_DST_SURFACE_STATE_OFFSET_BYTES: usize = 0x14C0;
const RECT_WORKLIST_DESC_SURFACE_STATE_OFFSET_BYTES: usize = 0x1500;
const RECT_WORKLIST_PAYLOAD_OFFSET_BYTES: usize = 0x1600;
const RECT_WORKLIST_IDD_BYTES: usize = 8 * core::mem::size_of::<u32>();
const RECT_WORKLIST_CROSS_THREAD_GRFS: u32 = 3;
const RECT_WORKLIST_CROSS_THREAD_BYTES: usize = RECT_WORKLIST_CROSS_THREAD_GRFS as usize * 32;
const FILL_RECT_WORKLIST_CROSS_THREAD_GRFS: u32 = 2;
const FILL_RECT_WORKLIST_CROSS_THREAD_BYTES: usize =
    FILL_RECT_WORKLIST_CROSS_THREAD_GRFS as usize * 32;
const RECT_WORKLIST_PER_THREAD_BYTES: usize = 96;
const RECT_WORKLIST_INDIRECT_BYTES: usize =
    RECT_WORKLIST_CROSS_THREAD_BYTES + RECT_WORKLIST_PER_THREAD_BYTES;
const ALPHA_BLEND_WORKLIST_CROSS_THREAD_GRFS: u32 = 3;
const ALPHA_BLEND_WORKLIST_CROSS_THREAD_BYTES: usize =
    ALPHA_BLEND_WORKLIST_CROSS_THREAD_GRFS as usize * 32;
const ALPHA_BLEND_WORKLIST_INDIRECT_BYTES: usize =
    ALPHA_BLEND_WORKLIST_CROSS_THREAD_BYTES + RECT_WORKLIST_PER_THREAD_BYTES;
const _: () = assert!(ALPHA_BLEND_WORKLIST_INDIRECT_BYTES == RECT_WORKLIST_INDIRECT_BYTES);
// The 2D kernel consumes global/local/enqueued-local payload fields before its
// three pointers and scalar arguments.  The baked ADL-S artifact therefore
// declares 104 bytes of cross-thread data, rounded to four 32-byte GRFs.
const SPRITE_QUAD_WORKLIST_CROSS_THREAD_GRFS: u32 = 4;
const SPRITE_QUAD_WORKLIST_CROSS_THREAD_BYTES: usize =
    SPRITE_QUAD_WORKLIST_CROSS_THREAD_GRFS as usize * 32;
const SPRITE_QUAD_WORKLIST_PER_THREAD_BYTES: usize = 96;
const SPRITE_QUAD_WORKLIST_INDIRECT_BYTES: usize =
    SPRITE_QUAD_WORKLIST_CROSS_THREAD_BYTES + SPRITE_QUAD_WORKLIST_PER_THREAD_BYTES;
const UI4_COMPOSE_LAYERS_CROSS_THREAD_GRFS: u32 = 4;
const UI4_COMPOSE_LAYERS_CROSS_THREAD_BYTES: usize =
    UI4_COMPOSE_LAYERS_CROSS_THREAD_GRFS as usize * 32;
const UI4_COMPOSE_LAYERS_PER_THREAD_BYTES: usize = 96;
const UI4_COMPOSE_LAYERS_INDIRECT_BYTES: usize =
    UI4_COMPOSE_LAYERS_CROSS_THREAD_BYTES + UI4_COMPOSE_LAYERS_PER_THREAD_BYTES;
const SPRITE_QUAD_WORKLIST_RUN_STATE_BLOCK_BYTES: usize = 0x140;
// The sprite path can emit one walker plus an ordering flush per descriptor.
// Its maximum command stream is therefore much larger than the older rect
// worklists and must not share their 0x1400 state offset.  Keep the first 32
// KiB exclusively for commands, followed by texture/run state and payloads.
const SPRITE_QUAD_WORKLIST_STATE_BASE_OFFSET_BYTES: usize = 0x8000;
const SPRITE_QUAD_WORKLIST_SINGLE_PAYLOAD_BASE_OFFSET_BYTES: usize =
    SPRITE_QUAD_WORKLIST_STATE_BASE_OFFSET_BYTES + SPRITE_QUAD_WORKLIST_RUN_STATE_BLOCK_BYTES;
const SPRITE_QUAD_WORKLIST_RUN_IDD_REL: usize = 0x00;
const SPRITE_QUAD_WORKLIST_RUN_BINDING_REL: usize = 0x40;
const SPRITE_QUAD_WORKLIST_RUN_SRC_SURFACE_REL: usize = 0x80;
const SPRITE_QUAD_WORKLIST_RUN_DST_SURFACE_REL: usize = 0xC0;
const SPRITE_QUAD_WORKLIST_RUN_DESC_SURFACE_REL: usize = 0x100;
const RECT_WORKLIST_PRE_MARKER_SLOT: usize = 15;
const RECT_WORKLIST_POST_MARKER_SLOT: usize = 14;
const FILL_RECT_WORKLIST_PRE_MARKER: u32 = 0xC0DE_5801;
const FILL_RECT_WORKLIST_POST_MARKER: u32 = 0xC0DE_5802;
const ALPHA_BLEND_WORKLIST_PRE_MARKER: u32 = 0xC0DE_5A01;
const ALPHA_BLEND_WORKLIST_POST_MARKER: u32 = 0xC0DE_5A02;

const SPRITE_QUAD_WORKLIST_PRE_MARKER_SLOT: usize = 25;
const SPRITE_QUAD_WORKLIST_POST_MARKER_SLOT: usize = 24;
const SPRITE_QUAD_WORKLIST_PRE_MARKER: u32 = 0xC0DE_5B01;
const SPRITE_QUAD_WORKLIST_POST_MARKER: u32 = 0xC0DE_5B02;
const UI4_COMPOSE_LAYERS_PRE_MARKER: u32 = 0xC0DE_4C01;
const UI4_COMPOSE_LAYERS_POST_MARKER: u32 = 0xC0DE_4C02;

const MANDEL64_WORKLIST_PRE_MARKER: u32 = 0xC0DE_6401;
const MANDEL64_WORKLIST_POST_MARKER: u32 = 0xC0DE_6402;
const RECT_WORKLIST_DESC_GPU: u64 = 0x05A0_0000;
const MANDEL64_WORKLIST_DESC_GPU: u64 = 0x05B0_0000;
const SPRITE_QUAD_WORKLIST_DESC_GPU: u64 = 0x05C0_0000;
const RECT_WORKLIST_MAX_DESCS: usize = 256;
const RECT_WORKLIST_DESCS_PER_WALKER: usize = 16;
const RECT_WORKLIST_MAX_WALKERS: usize = RECT_WORKLIST_MAX_DESCS / RECT_WORKLIST_DESCS_PER_WALKER;
const RECT_WORKLIST_DESC_BYTES: usize = 8192;
const ALPHA_BLEND_WORKLIST_MAX_DESCS: usize = RECT_WORKLIST_MAX_DESCS;
const ALPHA_BLEND_WORKLIST_DESC_BYTES: usize =
    ALPHA_BLEND_WORKLIST_MAX_DESCS * core::mem::size_of::<GpgpuAlphaBlendWorklistDesc>();
const SPRITE_QUAD_WORKLIST_MAX_DESCS: usize = 256;
const SPRITE_QUAD_WORKLIST_DESCS_PER_WALKER: usize = 1;
const SPRITE_QUAD_WORKLIST_MAX_WALKERS: usize = SPRITE_QUAD_WORKLIST_MAX_DESCS;
const SPRITE_QUAD_WORKLIST_DESC_BYTES: usize =
    SPRITE_QUAD_WORKLIST_MAX_DESCS * core::mem::size_of::<GpgpuSpriteQuadWorklistDesc>();
const SPRITE_QUAD_WORKLIST_MAX_GROUPS_PER_WALKER: usize = SPRITE_QUAD_WORKLIST_MAX_DESCS;
const UI4_COMPOSE_LAYERS_MAX_LAYERS: usize = 32;
// Match the shader's one-work-item-per-pixel contract. A previous 64-row
// serial lane tile was the source of partial horizontal compositor strips.
const SPRITE_QUAD_WORKLIST_TILE_ROWS: u32 = 1;
const MANDEL64_WORKLIST_CELL_PIXELS: u32 = 64;
const MANDEL64_WORKLIST_BAND_ROWS: u32 = 4;
const MANDEL64_WORKLIST_BANDS_PER_TILE: usize =
    (MANDEL64_WORKLIST_CELL_PIXELS / MANDEL64_WORKLIST_BAND_ROWS) as usize;
const MANDEL64_WORKLIST_MAX_DESCS: usize = 512;
const MANDEL64_WORKLIST_DESCS_PER_WALKER: usize = RECT_WORKLIST_DESCS_PER_WALKER;
const MANDEL64_WORKLIST_MAX_WALKERS: usize =
    MANDEL64_WORKLIST_MAX_DESCS / MANDEL64_WORKLIST_DESCS_PER_WALKER;
const MANDEL64_WORKLIST_FLAG_ROWS_MASK: u32 = 0x0000_007F;
const MANDEL64_WORKLIST_FLAG_NO_MIRROR: u32 = 1 << 7;
const MANDEL64_WORKLIST_FLAG_COLS_SHIFT: u32 = 8;
const MANDEL64_WORKLIST_FLAG_VIEW_HEIGHT_SHIFT: u32 = 16;

pub(crate) const MANDEL64_WORKLIST_MAX_ITERATIONS: u32 = 512;

fn pack_mandel64_iterations(iterations: u32) -> u32 {
    let max_iter = iterations.clamp(1, MANDEL64_WORKLIST_MAX_ITERATIONS);
    let gray_scale = (255u32 * 256u32) / max_iter;
    max_iter | (gray_scale << 16)
}

const SKYBOX_SAMPLE_IDD_OFFSET_BYTES: usize = 0x4200;
const SKYBOX_SAMPLE_BINDING_TABLE_OFFSET_BYTES: usize = 0x4240;
const SKYBOX_SAMPLE_SRC_SURFACE_STATE_OFFSET_BYTES: usize = 0x4280;
const SKYBOX_SAMPLE_DST_SURFACE_STATE_OFFSET_BYTES: usize = 0x42C0;
const SKYBOX_SAMPLE_PAYLOAD_OFFSET_BYTES: usize = 0x4400;
const SKYBOX_SAMPLE_IDD_BYTES: usize = 8 * core::mem::size_of::<u32>();
const SKYBOX_SAMPLE_CROSS_THREAD_BYTES: usize = 160;
const SKYBOX_SAMPLE_PER_THREAD_BYTES: usize = 96;
const SKYBOX_SAMPLE_INDIRECT_BYTES: usize =
    SKYBOX_SAMPLE_CROSS_THREAD_BYTES + SKYBOX_SAMPLE_PER_THREAD_BYTES;
const SKYBOX_SAMPLE_PRE_MARKER_SLOT: usize = 27;
const SKYBOX_SAMPLE_POST_MARKER_SLOT: usize = 26;
const SKYBOX_SAMPLE_PRE_MARKER: u32 = 0xC0DE_5C01;
const SKYBOX_SAMPLE_POST_MARKER: u32 = 0xC0DE_5C02;
const CHART_SINE_IDD_OFFSET_BYTES: usize = 0x4600;
const CHART_SINE_BINDING_TABLE_OFFSET_BYTES: usize = 0x4640;
const CHART_SINE_DST_SURFACE_STATE_OFFSET_BYTES: usize = 0x4680;
const CHART_SINE_PAYLOAD_OFFSET_BYTES: usize = 0x4800;
const CHART_SINE_IDD_BYTES: usize = 8 * core::mem::size_of::<u32>();
const CHART_SINE_CROSS_THREAD_BYTES: usize = 128;
const CHART_SINE_PER_THREAD_BYTES: usize = 96;
const CHART_SINE_INDIRECT_BYTES: usize =
    CHART_SINE_CROSS_THREAD_BYTES + CHART_SINE_PER_THREAD_BYTES;
const CHART_SINE_PRE_MARKER_SLOT: usize = 29;
const CHART_SINE_POST_MARKER_SLOT: usize = 28;
const CHART_SINE_PRE_MARKER: u32 = 0xC0DE_C701;
const CHART_SINE_POST_MARKER: u32 = 0xC0DE_C702;
pub(crate) const CHART_SINE_FLAG_GRID: u32 = 1 << 0;
pub(crate) const CHART_SINE_FLAG_AXES: u32 = 1 << 1;
pub(crate) const CHART_SINE_FLAG_GLOW: u32 = 1 << 2;
pub(crate) const CHART_SINE_FLAG_BORDER: u32 = 1 << 3;
const PIXEL_PLASMA_IDD_OFFSET_BYTES: usize = 0x4A00;
const PIXEL_PLASMA_BINDING_TABLE_OFFSET_BYTES: usize = 0x4A40;
const PIXEL_PLASMA_DST_SURFACE_STATE_OFFSET_BYTES: usize = 0x4A80;
const PIXEL_PLASMA_PAYLOAD_OFFSET_BYTES: usize = 0x4C00;
const PIXEL_PLASMA_IDD_BYTES: usize = 8 * core::mem::size_of::<u32>();
const PIXEL_PLASMA_CROSS_THREAD_BYTES: usize = 128;
const PIXEL_PLASMA_PER_THREAD_BYTES: usize = 96;
const PIXEL_PLASMA_INDIRECT_BYTES: usize =
    PIXEL_PLASMA_CROSS_THREAD_BYTES + PIXEL_PLASMA_PER_THREAD_BYTES;
const PIXEL_PLASMA_PRE_MARKER_SLOT: usize = 31;
const PIXEL_PLASMA_POST_MARKER_SLOT: usize = 30;
const PIXEL_PLASMA_PRE_MARKER: u32 = 0xC0DE_A801;
const PIXEL_PLASMA_POST_MARKER: u32 = 0xC0DE_A802;
const CPP_DEMO_IDD_OFFSET_BYTES: usize = 0x6800;
const CPP_DEMO_BINDING_TABLE_OFFSET_BYTES: usize = 0x6840;
const CPP_DEMO_DST_SURFACE_STATE_OFFSET_BYTES: usize = 0x6880;
const CPP_DEMO_PAYLOAD_OFFSET_BYTES: usize = 0x6A00;
const CPP_DEMO_IDD_BYTES: usize = 8 * core::mem::size_of::<u32>();
const CPP_DEMO_CROSS_THREAD_BYTES: usize =
    CPP_DEMO_RGBA8_ADLS_CPP_ABI_CONTRACT.cross_thread_data_bytes as usize;
const CPP_DEMO_PER_THREAD_BYTES: usize =
    CPP_DEMO_RGBA8_ADLS_CPP_ABI_CONTRACT.per_thread_data_bytes as usize;
const CPP_DEMO_INDIRECT_BYTES: usize = CPP_DEMO_CROSS_THREAD_BYTES + CPP_DEMO_PER_THREAD_BYTES;
const CPP_DEMO_PRE_MARKER_SLOT: usize = 41;
const CPP_DEMO_POST_MARKER_SLOT: usize = 40;
const CPP_DEMO_PRE_MARKER: u32 = 0xC0DE_C901;
const CPP_DEMO_POST_MARKER: u32 = 0xC0DE_C902;
const CPP_AUDIO_VISUALIZER_IDD_OFFSET_BYTES: usize = 0x6C00;
const CPP_AUDIO_VISUALIZER_BINDING_TABLE_OFFSET_BYTES: usize = 0x6C40;
const CPP_AUDIO_VISUALIZER_AUDIO_SURFACE_STATE_OFFSET_BYTES: usize = 0x6C80;
const CPP_AUDIO_VISUALIZER_DST_SURFACE_STATE_OFFSET_BYTES: usize = 0x6CC0;
const CPP_AUDIO_VISUALIZER_PAYLOAD_OFFSET_BYTES: usize = 0x6E00;
const CPP_AUDIO_VISUALIZER_IDD_BYTES: usize = 8 * core::mem::size_of::<u32>();
const CPP_AUDIO_VISUALIZER_CROSS_THREAD_BYTES: usize =
    CPP_AUDIO_VISUALIZER_RGBA8_ADLS_CPP_ABI_CONTRACT.cross_thread_data_bytes as usize;
const CPP_AUDIO_VISUALIZER_PER_THREAD_BYTES: usize =
    CPP_AUDIO_VISUALIZER_RGBA8_ADLS_CPP_ABI_CONTRACT.per_thread_data_bytes as usize;
const CPP_AUDIO_VISUALIZER_INDIRECT_BYTES: usize =
    CPP_AUDIO_VISUALIZER_CROSS_THREAD_BYTES + CPP_AUDIO_VISUALIZER_PER_THREAD_BYTES;
const CPP_AUDIO_VISUALIZER_PRE_MARKER_SLOT: usize = 43;
const CPP_AUDIO_VISUALIZER_POST_MARKER_SLOT: usize = 42;
const CPP_AUDIO_VISUALIZER_PRE_MARKER: u32 = 0xC0DE_A901;
const CPP_AUDIO_VISUALIZER_POST_MARKER: u32 = 0xC0DE_A902;
const PARTICLE_CRAFT_STEP_IDD_OFFSET_BYTES: usize = 0x7000;
const PARTICLE_CRAFT_STEP_BINDING_TABLE_OFFSET_BYTES: usize = 0x7040;
const PARTICLE_CRAFT_STEP_STATE_SURFACE_OFFSET_BYTES: usize = 0x7080;
const PARTICLE_CRAFT_STEP_PARAMS_SURFACE_OFFSET_BYTES: usize = 0x70C0;
const PARTICLE_CRAFT_STEP_PAYLOAD_OFFSET_BYTES: usize = 0x7200;
const PARTICLE_CRAFT_BIN_IDD_OFFSET_BYTES: usize = 0x7400;
const PARTICLE_CRAFT_BIN_BINDING_TABLE_OFFSET_BYTES: usize = 0x7440;
const PARTICLE_CRAFT_BIN_STATE_SURFACE_OFFSET_BYTES: usize = 0x7480;
const PARTICLE_CRAFT_BIN_PARAMS_SURFACE_OFFSET_BYTES: usize = 0x74C0;
const PARTICLE_CRAFT_BIN_MASKS_SURFACE_OFFSET_BYTES: usize = 0x7500;
const PARTICLE_CRAFT_BIN_PAYLOAD_OFFSET_BYTES: usize = 0x7600;
const PARTICLE_CRAFT_RENDER_IDD_OFFSET_BYTES: usize = 0x7800;
const PARTICLE_CRAFT_RENDER_BINDING_TABLE_OFFSET_BYTES: usize = 0x7840;
const PARTICLE_CRAFT_RENDER_STATE_SURFACE_OFFSET_BYTES: usize = 0x7880;
const PARTICLE_CRAFT_RENDER_PARAMS_SURFACE_OFFSET_BYTES: usize = 0x78C0;
const PARTICLE_CRAFT_RENDER_MASKS_SURFACE_OFFSET_BYTES: usize = 0x7900;
const PARTICLE_CRAFT_RENDER_DST_SURFACE_OFFSET_BYTES: usize = 0x7940;
const PARTICLE_CRAFT_RENDER_PAYLOAD_OFFSET_BYTES: usize = 0x7A00;
const PARTICLE_CRAFT_IDD_BYTES: usize = 8 * core::mem::size_of::<u32>();
const PARTICLE_CRAFT_STEP_CROSS_THREAD_BYTES: usize =
    PARTICLE_CRAFT_STEP_ADLS_CPP_ABI_CONTRACT.cross_thread_data_bytes as usize;
const PARTICLE_CRAFT_BIN_CROSS_THREAD_BYTES: usize =
    PARTICLE_CRAFT_BIN_TILES_ADLS_CPP_ABI_CONTRACT.cross_thread_data_bytes as usize;
const PARTICLE_CRAFT_RENDER_CROSS_THREAD_BYTES: usize =
    PARTICLE_CRAFT_RENDER_RGBA8_ADLS_CPP_ABI_CONTRACT.cross_thread_data_bytes as usize;
const PARTICLE_CRAFT_PER_THREAD_BYTES: usize =
    PARTICLE_CRAFT_STEP_ADLS_CPP_ABI_CONTRACT.per_thread_data_bytes as usize;
const PARTICLE_CRAFT_STEP_INDIRECT_BYTES: usize =
    PARTICLE_CRAFT_STEP_CROSS_THREAD_BYTES + PARTICLE_CRAFT_PER_THREAD_BYTES;
const PARTICLE_CRAFT_BIN_INDIRECT_BYTES: usize =
    PARTICLE_CRAFT_BIN_CROSS_THREAD_BYTES + PARTICLE_CRAFT_PER_THREAD_BYTES;
const PARTICLE_CRAFT_RENDER_INDIRECT_BYTES: usize =
    PARTICLE_CRAFT_RENDER_CROSS_THREAD_BYTES + PARTICLE_CRAFT_PER_THREAD_BYTES;
const PARTICLE_CRAFT_PRE_MARKER_SLOT: usize = 47;
const PARTICLE_CRAFT_POST_MARKER_SLOT: usize = 46;
const PARTICLE_CRAFT_PRE_MARKER: u32 = 0xC0DE_C701;
const PARTICLE_CRAFT_POST_MARKER: u32 = 0xC0DE_C702;
const PARTICLE_CRAFT_COMPLETION_TIMEOUT_MS: u64 = 1_000;
const _: () = {
    assert!(
        PARTICLE_CRAFT_STEP_ADLS_CPP_ABI_CONTRACT.per_thread_data_bytes
            == PARTICLE_CRAFT_BIN_TILES_ADLS_CPP_ABI_CONTRACT.per_thread_data_bytes
    );
    assert!(
        PARTICLE_CRAFT_STEP_ADLS_CPP_ABI_CONTRACT.per_thread_data_bytes
            == PARTICLE_CRAFT_RENDER_RGBA8_ADLS_CPP_ABI_CONTRACT.per_thread_data_bytes
    );
    assert!(
        PARTICLE_CRAFT_STEP_PAYLOAD_OFFSET_BYTES + PARTICLE_CRAFT_STEP_INDIRECT_BYTES
            <= PARTICLE_CRAFT_BIN_IDD_OFFSET_BYTES
    );
    assert!(
        PARTICLE_CRAFT_BIN_PAYLOAD_OFFSET_BYTES + PARTICLE_CRAFT_BIN_INDIRECT_BYTES
            <= PARTICLE_CRAFT_RENDER_IDD_OFFSET_BYTES
    );
    assert!(
        PARTICLE_CRAFT_RENDER_PAYLOAD_OFFSET_BYTES + PARTICLE_CRAFT_RENDER_INDIRECT_BYTES
            <= DIRECT_RCS_BATCH_BYTES
    );
    assert!(
        PARTICLE_CRAFT_STEP_PAYLOAD_OFFSET_BYTES
            .is_multiple_of(GPGPU_WALKER_INDIRECT_ALIGNMENT_BYTES)
    );
    assert!(
        PARTICLE_CRAFT_BIN_PAYLOAD_OFFSET_BYTES
            .is_multiple_of(GPGPU_WALKER_INDIRECT_ALIGNMENT_BYTES)
    );
    assert!(
        PARTICLE_CRAFT_RENDER_PAYLOAD_OFFSET_BYTES
            .is_multiple_of(GPGPU_WALKER_INDIRECT_ALIGNMENT_BYTES)
    );
};
const SHADERTOY_IDD_OFFSET_BYTES: usize = 0x7C00;
const SHADERTOY_BINDING_TABLE_OFFSET_BYTES: usize = 0x7C40;
const SHADERTOY_DST_SURFACE_STATE_OFFSET_BYTES: usize = 0x7C80;
const SHADERTOY_UNIFORMS_SURFACE_STATE_OFFSET_BYTES: usize = 0x7CC0;
const SHADERTOY_PAYLOAD_OFFSET_BYTES: usize = 0x7E00;
const SHADERTOY_UNIFORMS_OFFSET_BYTES: usize = 0x7F00;
const SHADERTOY_UNIFORMS_BYTES: usize = 16 * core::mem::size_of::<f32>();
const SHADERTOY_CROSS_THREAD_BYTES: usize = 96;
const SHADERTOY_PER_THREAD_BYTES: usize = 96;
const SHADERTOY_INDIRECT_BYTES: usize = SHADERTOY_CROSS_THREAD_BYTES + SHADERTOY_PER_THREAD_BYTES;
const SHADERTOY_IDD_BYTES: usize = 8 * core::mem::size_of::<u32>();
const SHADERTOY_PRE_MARKER_SLOT: usize = 51;
const SHADERTOY_POST_MARKER_SLOT: usize = 50;
const SHADERTOY_PRE_MARKER: u32 = 0xC0DE_5701;
const SHADERTOY_POST_MARKER: u32 = 0xC0DE_5702;
const _: () = {
    assert!(
        SHADERTOY_PAYLOAD_OFFSET_BYTES + SHADERTOY_INDIRECT_BYTES
            <= SHADERTOY_UNIFORMS_OFFSET_BYTES
    );
    assert!(SHADERTOY_UNIFORMS_OFFSET_BYTES + SHADERTOY_UNIFORMS_BYTES <= DIRECT_RCS_BATCH_BYTES);
    assert!(SHADERTOY_PAYLOAD_OFFSET_BYTES.is_multiple_of(GPGPU_WALKER_INDIRECT_ALIGNMENT_BYTES));
};
const LFM25_Q8_COMMAND_BYTES: usize = 4096;
const LFM25_Q8_STATE_BASE_OFFSET_BYTES: usize = 0x7000;
const LFM25_Q8_STATE_STRIDE_BYTES: usize = 0x400;
const LFM25_Q8_IDD_RELATIVE_OFFSET_BYTES: usize = 0;
const LFM25_Q8_BINDING_TABLE_RELATIVE_OFFSET_BYTES: usize = 0x40;
const LFM25_Q8_WEIGHTS_SURFACE_STATE_RELATIVE_OFFSET_BYTES: usize = 0x80;
const LFM25_Q8_ACTIVATION_SURFACE_STATE_RELATIVE_OFFSET_BYTES: usize = 0xC0;
const LFM25_Q8_OUTPUT_SURFACE_STATE_RELATIVE_OFFSET_BYTES: usize = 0x100;
const LFM25_Q8_PAYLOAD_RELATIVE_OFFSET_BYTES: usize = 0x200;
const LFM25_Q8_IDD_BYTES: usize = 8 * core::mem::size_of::<u32>();
const LFM25_Q8_CROSS_THREAD_BYTES: usize =
    LFM25_Q8_PROJECT_PACKED_ADLS_CPP_ABI_CONTRACT.cross_thread_data_bytes as usize;
const LFM25_Q8_PER_THREAD_BYTES: usize =
    LFM25_Q8_PROJECT_PACKED_ADLS_CPP_ABI_CONTRACT.per_thread_data_bytes as usize;
const LFM25_Q8_INDIRECT_BYTES: usize = LFM25_Q8_CROSS_THREAD_BYTES + LFM25_Q8_PER_THREAD_BYTES;
const LFM25_Q8_PRE_MARKER_SLOT: usize = 45;
const LFM25_Q8_POST_MARKER_SLOT: usize = 44;
const LFM25_Q8_GPU_START_TIMESTAMP_SLOT: usize = 46;
const LFM25_Q8_GPU_END_TIMESTAMP_SLOT: usize = 48;
const LFM25_Q8_GPU_BATCH_ENTER_TIMESTAMP_SLOT: usize = 50;
const LFM25_Q8_GPU_POST_RELEASE_TIMESTAMP_SLOT: usize = 52;
const LFM25_Q8_PRE_MARKER: u32 = 0xC0DE_B001;
const LFM25_Q8_POST_MARKER: u32 = 0xC0DE_B002;
const LFM25_Q8_COMPLETION_TIMEOUT_MS: u64 = 2_500;
pub(crate) const LFM25_Q8_MAX_BATCH_PROJECTIONS: usize = 3;
const LFM25_Q8_ACTIVATION_ALLOC_BYTES: usize = 8 * 1024;
const LFM25_Q8_OUTPUT_ALLOC_BYTES: usize = 65_536 * core::mem::size_of::<f32>();
const LFM25_Q8_MODEL_MAPPING_GPU_BASE: u64 = 0x1000_0000;
const LFM25_Q8_ACTIVATION_GPU: u64 = 0x2700_0000;
const LFM25_Q8_OUTPUT_GPU: u64 = 0x2701_0000;
const _: () = {
    assert!(
        LFM25_Q8_IDD_RELATIVE_OFFSET_BYTES + LFM25_Q8_IDD_BYTES
            <= LFM25_Q8_BINDING_TABLE_RELATIVE_OFFSET_BYTES
    );
    assert!(
        LFM25_Q8_OUTPUT_SURFACE_STATE_RELATIVE_OFFSET_BYTES
            + COPY_RECT_SURFACE_STATE_DWORDS * core::mem::size_of::<u32>()
            <= LFM25_Q8_PAYLOAD_RELATIVE_OFFSET_BYTES
    );
    assert!(
        LFM25_Q8_PAYLOAD_RELATIVE_OFFSET_BYTES + LFM25_Q8_INDIRECT_BYTES
            <= LFM25_Q8_STATE_STRIDE_BYTES
    );
    assert!(
        LFM25_Q8_STATE_BASE_OFFSET_BYTES
            + LFM25_Q8_MAX_BATCH_PROJECTIONS * LFM25_Q8_STATE_STRIDE_BYTES
            <= DIRECT_RCS_BATCH_BYTES
    );
    assert!(LFM25_Q8_GPU_START_TIMESTAMP_SLOT.is_multiple_of(2));
    assert!(LFM25_Q8_GPU_END_TIMESTAMP_SLOT.is_multiple_of(2));
    assert!(LFM25_Q8_GPU_BATCH_ENTER_TIMESTAMP_SLOT.is_multiple_of(2));
    assert!(LFM25_Q8_GPU_POST_RELEASE_TIMESTAMP_SLOT.is_multiple_of(2));
    assert!(LFM25_Q8_GPU_END_TIMESTAMP_SLOT + 2 <= LFM25_Q8_GPU_BATCH_ENTER_TIMESTAMP_SLOT);
    assert!(
        LFM25_Q8_GPU_BATCH_ENTER_TIMESTAMP_SLOT + 2 <= LFM25_Q8_GPU_POST_RELEASE_TIMESTAMP_SLOT
    );
    assert!(
        (LFM25_Q8_GPU_POST_RELEASE_TIMESTAMP_SLOT + 2) * core::mem::size_of::<u32>()
            <= DIRECT_RCS_RESULT_BYTES
    );
    assert!(LFM25_Q8_COMMAND_BYTES <= LFM25_Q8_STATE_BASE_OFFSET_BYTES);
    assert!(LFM25_Q8_MODEL_MAPPING_GPU_BASE.is_multiple_of(4096));
    assert!(LFM25_Q8_ACTIVATION_GPU.is_multiple_of(4096));
    assert!(LFM25_Q8_OUTPUT_GPU.is_multiple_of(4096));
    assert!(
        LFM25_Q8_MODEL_MAPPING_GPU_BASE
            + trueos_lfm25_model::lfm25::PINNED_NATIVE_IMAGE_BYTES as u64
            + 4095
            <= LFM25_Q8_ACTIVATION_GPU
    );
    assert!(
        LFM25_Q8_OUTPUT_GPU + LFM25_Q8_OUTPUT_ALLOC_BYTES as u64 <= DIRECT_RCS_PPGTT_LIMIT_BYTES
    );
};

// Kokoro's quantized dense lane stages one complete admitted projection in a
// persistent, page-aligned DMA arena.  The six regions deliberately live in
// one allocation: one PPGTT mapping publishes the complete ABI while the
// stateful binding table still exposes six independently-bounded surfaces.
const KOKORO_QGEMM_MAX_MATRIX_ROWS: usize = 512;
const KOKORO_QGEMM_MAX_OUTPUT_COLUMNS: usize = 2_180;
const KOKORO_QGEMM_MAX_REDUCTION_WORDS: usize = 2_048 / 4;
const KOKORO_QGEMM_PACKED_WEIGHTS_ALLOC_BYTES: usize = 0x0018_0000;
const KOKORO_QGEMM_VECTOR_ALLOC_BYTES: usize = 0x0000_3000;
const KOKORO_QGEMM_ACTIVATIONS_ALLOC_BYTES: usize = 0x0010_0000;
const KOKORO_QGEMM_OUTPUT_ALLOC_BYTES: usize = 0x0044_2000;
const KOKORO_QGEMM_PACKED_WEIGHTS_OFFSET_BYTES: usize = 0;
const KOKORO_QGEMM_WEIGHT_SUMS_OFFSET_BYTES: usize =
    KOKORO_QGEMM_PACKED_WEIGHTS_OFFSET_BYTES + KOKORO_QGEMM_PACKED_WEIGHTS_ALLOC_BYTES;
const KOKORO_QGEMM_WEIGHT_SCALES_OFFSET_BYTES: usize =
    KOKORO_QGEMM_WEIGHT_SUMS_OFFSET_BYTES + KOKORO_QGEMM_VECTOR_ALLOC_BYTES;
const KOKORO_QGEMM_ACTIVATIONS_OFFSET_BYTES: usize =
    KOKORO_QGEMM_WEIGHT_SCALES_OFFSET_BYTES + KOKORO_QGEMM_VECTOR_ALLOC_BYTES;
const KOKORO_QGEMM_BIAS_OFFSET_BYTES: usize =
    KOKORO_QGEMM_ACTIVATIONS_OFFSET_BYTES + KOKORO_QGEMM_ACTIVATIONS_ALLOC_BYTES;
const KOKORO_QGEMM_OUTPUT_OFFSET_BYTES: usize =
    KOKORO_QGEMM_BIAS_OFFSET_BYTES + KOKORO_QGEMM_VECTOR_ALLOC_BYTES;
const KOKORO_QGEMM_ARENA_BYTES: usize =
    KOKORO_QGEMM_OUTPUT_OFFSET_BYTES + KOKORO_QGEMM_OUTPUT_ALLOC_BYTES;
const KOKORO_QGEMM_ARENA_GPU: u64 = 0x2100_0000;
const KOKORO_QGEMM_ARENA_GPU_LIMIT: u64 = 0x2200_0000;

const KOKORO_QGEMM_IDD_OFFSET_BYTES: usize = 0x7000;
const KOKORO_QGEMM_BINDING_TABLE_OFFSET_BYTES: usize = 0x7040;
const KOKORO_QGEMM_PACKED_WEIGHTS_SURFACE_OFFSET_BYTES: usize = 0x7080;
const KOKORO_QGEMM_WEIGHT_SUMS_SURFACE_OFFSET_BYTES: usize = 0x70C0;
const KOKORO_QGEMM_WEIGHT_SCALES_SURFACE_OFFSET_BYTES: usize = 0x7100;
const KOKORO_QGEMM_ACTIVATIONS_SURFACE_OFFSET_BYTES: usize = 0x7140;
const KOKORO_QGEMM_BIAS_SURFACE_OFFSET_BYTES: usize = 0x7180;
const KOKORO_QGEMM_OUTPUT_SURFACE_OFFSET_BYTES: usize = 0x71C0;
const KOKORO_QGEMM_PAYLOAD_OFFSET_BYTES: usize = 0x7400;
const KOKORO_QGEMM_IDD_BYTES: usize = 8 * core::mem::size_of::<u32>();
const KOKORO_QGEMM_CROSS_THREAD_BYTES: usize =
    KOKORO_QGEMM_U8_I8_ADLS_CPP_ABI_CONTRACT.cross_thread_data_bytes as usize;
const KOKORO_QGEMM_PER_THREAD_BYTES: usize =
    KOKORO_QGEMM_U8_I8_ADLS_CPP_ABI_CONTRACT.per_thread_data_bytes as usize;
const KOKORO_QGEMM_INDIRECT_BYTES: usize =
    KOKORO_QGEMM_CROSS_THREAD_BYTES + KOKORO_QGEMM_PER_THREAD_BYTES;
const KOKORO_QGEMM_POST_MARKER_SLOT: usize = 56;
const KOKORO_QGEMM_PRE_MARKER_SLOT: usize = 58;
const KOKORO_QGEMM_POST_MARKER: u32 = 0xC0DE_7A02;
const KOKORO_QGEMM_PRE_MARKER: u32 = 0xC0DE_7A01;
const KOKORO_QGEMM_COMPLETION_TIMEOUT_MS: u64 = 5_000;

const _: () = {
    assert!(KOKORO_QGEMM_U8_I8_ADLS_CPP_ABI_CONTRACT.simd_width == 16);
    assert!(KOKORO_QGEMM_CROSS_THREAD_BYTES == 128);
    assert!(KOKORO_QGEMM_PER_THREAD_BYTES == 96);
    assert!(KOKORO_QGEMM_U8_I8_ADLS_CPP_ABI_CONTRACT.bindings.len() == 6);
    assert!(KOKORO_QGEMM_MAX_REDUCTION_WORDS * 4 == 2_048);
    assert!(
        KOKORO_QGEMM_MAX_REDUCTION_WORDS * 768 * core::mem::size_of::<u32>()
            == KOKORO_QGEMM_PACKED_WEIGHTS_ALLOC_BYTES
    );
    assert!(
        KOKORO_QGEMM_MAX_OUTPUT_COLUMNS * core::mem::size_of::<u32>()
            <= KOKORO_QGEMM_VECTOR_ALLOC_BYTES
    );
    assert!(
        KOKORO_QGEMM_MAX_MATRIX_ROWS
            * KOKORO_QGEMM_MAX_REDUCTION_WORDS
            * core::mem::size_of::<u32>()
            == KOKORO_QGEMM_ACTIVATIONS_ALLOC_BYTES
    );
    assert!(
        KOKORO_QGEMM_MAX_MATRIX_ROWS
            * KOKORO_QGEMM_MAX_OUTPUT_COLUMNS
            * core::mem::size_of::<f32>()
            == KOKORO_QGEMM_OUTPUT_ALLOC_BYTES
    );
    assert!(KOKORO_QGEMM_ARENA_GPU.is_multiple_of(4096));
    assert!(KOKORO_QGEMM_ARENA_BYTES.is_multiple_of(4096));
    assert!(
        KOKORO_QGEMM_ARENA_GPU + KOKORO_QGEMM_ARENA_BYTES as u64 <= KOKORO_QGEMM_ARENA_GPU_LIMIT
    );
    assert!(KOKORO_QGEMM_ARENA_GPU_LIMIT <= DIRECT_RCS_PPGTT_LIMIT_BYTES);
    assert!(
        KOKORO_QGEMM_IDD_OFFSET_BYTES + KOKORO_QGEMM_IDD_BYTES
            <= KOKORO_QGEMM_BINDING_TABLE_OFFSET_BYTES
    );
    assert!(
        KOKORO_QGEMM_OUTPUT_SURFACE_OFFSET_BYTES
            + COPY_RECT_SURFACE_STATE_DWORDS * core::mem::size_of::<u32>()
            <= KOKORO_QGEMM_PAYLOAD_OFFSET_BYTES
    );
    assert!(
        KOKORO_QGEMM_PAYLOAD_OFFSET_BYTES + KOKORO_QGEMM_INDIRECT_BYTES <= DIRECT_RCS_BATCH_BYTES
    );
    assert!(
        KOKORO_QGEMM_PAYLOAD_OFFSET_BYTES.is_multiple_of(GPGPU_WALKER_INDIRECT_ALIGNMENT_BYTES)
    );
    assert!(KOKORO_QGEMM_POST_MARKER_SLOT.is_multiple_of(2));
    assert!(KOKORO_QGEMM_POST_MARKER_SLOT + 1 != KOKORO_QGEMM_PRE_MARKER_SLOT);
    assert!(
        (KOKORO_QGEMM_PRE_MARKER_SLOT + 1) * core::mem::size_of::<u32>() <= DIRECT_RCS_RESULT_BYTES
    );
};

// A UI4 compute producer may be queued behind the compositor on RCS0. In
// particular, the first use of each primary swap buffer seeds and composes a
// full scanout-sized surface, which is deliberately allowed to take much
// longer than one 33 ms preview cadence. This timeout proves retirement and
// ownership transfer; it is not a frame-time target. Returning early after a
// successful submit would let UI4 cancel/reuse a lease while the GPU can still
// write it.
const UI4_COMPUTE_PRODUCER_RETIRE_TIMEOUT_MS: u64 = 1_000;
const FONT_OUTLINE_COVERAGE_R8_CROSS_THREAD_BYTES: usize = 128;
const FONT_OUTLINE_COVERAGE_R8_PER_THREAD_BYTES: usize = 96;
const FONT_OUTLINE_COVERAGE_R8_INDIRECT_BYTES: usize =
    FONT_OUTLINE_COVERAGE_R8_CROSS_THREAD_BYTES + FONT_OUTLINE_COVERAGE_R8_PER_THREAD_BYTES;
pub(crate) const FONT_OUTLINE_COVERAGE_BATCH_MAX_RUNS: usize = 64;
const FONT_OUTLINE_COVERAGE_BATCH_STATE_BASE_OFFSET_BYTES: usize = 0x4000;
const FONT_OUTLINE_COVERAGE_BATCH_STATE_BLOCK_BYTES: usize = 0x100;
const FONT_OUTLINE_COVERAGE_BATCH_IDD_OFFSET_IN_BLOCK_BYTES: usize = 0x00;
const FONT_OUTLINE_COVERAGE_BATCH_BINDING_TABLE_OFFSET_IN_BLOCK_BYTES: usize = 0x40;
const FONT_OUTLINE_COVERAGE_BATCH_OPS_SURFACE_OFFSET_IN_BLOCK_BYTES: usize = 0x80;
const FONT_OUTLINE_COVERAGE_BATCH_MASK_SURFACE_OFFSET_IN_BLOCK_BYTES: usize = 0xC0;
const FONT_OUTLINE_COVERAGE_BATCH_PAYLOAD_BASE_OFFSET_BYTES: usize = 0x8000;
const FONT_OUTLINE_COVERAGE_BATCH_PAYLOAD_STRIDE_BYTES: usize =
    (FONT_OUTLINE_COVERAGE_R8_INDIRECT_BYTES + GPGPU_WALKER_INDIRECT_ALIGNMENT_BYTES - 1)
        & !(GPGPU_WALKER_INDIRECT_ALIGNMENT_BYTES - 1);
const RGBA8_SCANOUT_RELEASE_MARKER_SLOT: usize = 34;
const RGBA8_SCANOUT_RELEASE_MARKER: u32 = 0xC0DE_D102;

// Lab256 owns one tightly bounded three-dispatch batch. All resource VAs are
// persistent in the ordinary direct-RCS PPGTT and deliberately avoid the
// display cursor's 0x0600_0000 GGTT aliases.
const LAB256_SIZE: u32 = 256;
const LAB256_STATE_BYTES: usize = LAB256_SIZE as usize * LAB256_SIZE as usize * 4;
const LAB256_CONTROL_DWORDS: usize = 19;
const LAB256_CONTROL_BYTES: usize = LAB256_CONTROL_DWORDS * 4;
const LAB256_REPORT_DWORDS: usize = 16 + 16 * 8;
const LAB256_REPORT_BYTES: usize = LAB256_REPORT_DWORDS * 4;
const LAB256_PAGE_BYTES: usize = 4096;
const LAB256_STATE_A_GPU: u64 = 0x0900_0000;
const LAB256_STATE_B_GPU: u64 = 0x0904_0000;
const LAB256_CONTROL_GPU: u64 = 0x0908_0000;
const LAB256_REPORT_GPU: u64 = 0x0909_0000;
const _: () = assert!(LAB256_STATE_BYTES == 0x0004_0000);
const _: () = assert!(LAB256_CONTROL_BYTES <= LAB256_PAGE_BYTES);
const _: () = assert!(LAB256_REPORT_BYTES <= LAB256_PAGE_BYTES);
const _: () =
    assert!(LAB256_REPORT_GPU + LAB256_PAGE_BYTES as u64 <= DIRECT_RCS_GPU_VA_FONT_COVERAGE_BASE);

const LAB256_STEP_IDD_OFFSET_BYTES: usize = 0x5200;
const LAB256_STEP_BINDING_TABLE_OFFSET_BYTES: usize = 0x5240;
const LAB256_STEP_STATE_IN_SURFACE_OFFSET_BYTES: usize = 0x5280;
const LAB256_STEP_STATE_OUT_SURFACE_OFFSET_BYTES: usize = 0x52C0;
const LAB256_STEP_CONTROL_SURFACE_OFFSET_BYTES: usize = 0x5300;
const LAB256_STEP_PAYLOAD_OFFSET_BYTES: usize = 0x5400;

const LAB256_REDUCE_IDD_OFFSET_BYTES: usize = 0x5600;
const LAB256_REDUCE_BINDING_TABLE_OFFSET_BYTES: usize = 0x5640;
const LAB256_REDUCE_STATE_SURFACE_OFFSET_BYTES: usize = 0x5680;
const LAB256_REDUCE_REPORT_SURFACE_OFFSET_BYTES: usize = 0x56C0;
const LAB256_REDUCE_CONTROL_SURFACE_OFFSET_BYTES: usize = 0x5700;
const LAB256_REDUCE_PAYLOAD_OFFSET_BYTES: usize = 0x5800;

const LAB256_COMPOSITE_IDD_OFFSET_BYTES: usize = 0x5A00;
const LAB256_COMPOSITE_BINDING_TABLE_OFFSET_BYTES: usize = 0x5A40;
const LAB256_COMPOSITE_STATE_SURFACE_OFFSET_BYTES: usize = 0x5A80;
const LAB256_COMPOSITE_REPORT_SURFACE_OFFSET_BYTES: usize = 0x5AC0;
const LAB256_COMPOSITE_CONTROL_SURFACE_OFFSET_BYTES: usize = 0x5B00;
const LAB256_COMPOSITE_DST_SURFACE_OFFSET_BYTES: usize = 0x5B40;
const LAB256_COMPOSITE_PAYLOAD_OFFSET_BYTES: usize = 0x5C00;

const LAB256_IDD_BYTES: usize = 8 * core::mem::size_of::<u32>();
const LAB256_CROSS_THREAD_BYTES: usize = 96;
const LAB256_PER_THREAD_BYTES: usize = 96;
const LAB256_INDIRECT_BYTES: usize = LAB256_CROSS_THREAD_BYTES + LAB256_PER_THREAD_BYTES;
const LAB256_PRE_MARKER_SLOT: usize = 37;
const LAB256_POST_MARKER_SLOT: usize = 36;
const LAB256_PRE_MARKER: u32 = 0xC0DE_2601;
const LAB256_POST_MARKER: u32 = 0xC0DE_2602;
const LAB256_COMPLETION_TIMEOUT_MS: u64 = 1_000;
const LAB256_CONTROL_MAGIC: u32 = 0x4C41_4232;
const LAB256_CONTROL_VERSION: u32 = 6;
const LAB256_REPORT_MAGIC: u32 = 0x4C32_5250;
const LAB256_FLAG_WRAP: u32 = 1 << 0;
const LAB256_FLAG_INJECT: u32 = 1 << 1;
const LAB256_FLAG_RESET: u32 = 1 << 2;
const LAB256_BACKGROUND_ALPHA: f32 = 0.0;

// Spirit VFX owns one fixed two-artifact/two-walker execution batch. The first
// walker authors the procedural alpha background and the second source-over
// composites one immutable resident Lilly RGBA frame into the cursor target.
const SPIRIT_VFX_SIZE: u32 = 256;
// Dwords 0..31 retain the original preview-v1 layout. Dword 32 is an
// append-only UTC seconds-of-day extension consumed only by MagicTimeCircle;
// dword 4 remains smooth animation time for the independent sprite walker.
const SPIRIT_VFX_CONTROL_DWORDS: usize = 33;
const SPIRIT_VFX_CONTROL_BYTES: usize = SPIRIT_VFX_CONTROL_DWORDS * 4;
const SPIRIT_VFX_PAGE_BYTES: usize = 4096;
const SPIRIT_VFX_CONTROL_GPU: u64 = 0x090A_0000;
const CPP_AUDIO_VISUALIZER_SNAPSHOT_GPU: u64 = 0x090B_0000;
const CPP_AUDIO_VISUALIZER_SNAPSHOT_BYTES: usize = 4096;
const _: () = assert!(SPIRIT_VFX_CONTROL_BYTES <= SPIRIT_VFX_PAGE_BYTES);
const _: () = assert!(SPIRIT_VFX_CONTROL_GPU + SPIRIT_VFX_PAGE_BYTES as u64 <= 0x0A00_0000);
const _: () = assert!(
    CPP_AUDIO_VISUALIZER_SNAPSHOT_GPU + CPP_AUDIO_VISUALIZER_SNAPSHOT_BYTES as u64 <= 0x0A00_0000
);

const SPIRIT_VFX_BACKGROUND_IDD_OFFSET_BYTES: usize = 0x6000;
const SPIRIT_VFX_BACKGROUND_BINDING_TABLE_OFFSET_BYTES: usize = 0x6040;
const SPIRIT_VFX_BACKGROUND_CONTROL_SURFACE_OFFSET_BYTES: usize = 0x6080;
const SPIRIT_VFX_BACKGROUND_DST_SURFACE_OFFSET_BYTES: usize = 0x60C0;
const SPIRIT_VFX_BACKGROUND_PAYLOAD_OFFSET_BYTES: usize = 0x6200;
const SPIRIT_VFX_SPRITE_IDD_OFFSET_BYTES: usize = 0x6400;
const SPIRIT_VFX_SPRITE_BINDING_TABLE_OFFSET_BYTES: usize = 0x6440;
const SPIRIT_VFX_SPRITE_SRC_SURFACE_OFFSET_BYTES: usize = 0x6480;
const SPIRIT_VFX_SPRITE_CONTROL_SURFACE_OFFSET_BYTES: usize = 0x64C0;
const SPIRIT_VFX_SPRITE_DST_SURFACE_OFFSET_BYTES: usize = 0x6500;
const SPIRIT_VFX_SPRITE_PAYLOAD_OFFSET_BYTES: usize = 0x6600;

const SPIRIT_VFX_IDD_BYTES: usize = 8 * core::mem::size_of::<u32>();
const SPIRIT_VFX_BACKGROUND_CROSS_THREAD_BYTES: usize = 64;
const SPIRIT_VFX_SPRITE_CROSS_THREAD_BYTES: usize = 96;
const SPIRIT_VFX_PER_THREAD_BYTES: usize = 96;
const SPIRIT_VFX_BACKGROUND_INDIRECT_BYTES: usize =
    SPIRIT_VFX_BACKGROUND_CROSS_THREAD_BYTES + SPIRIT_VFX_PER_THREAD_BYTES;
const SPIRIT_VFX_SPRITE_INDIRECT_BYTES: usize =
    SPIRIT_VFX_SPRITE_CROSS_THREAD_BYTES + SPIRIT_VFX_PER_THREAD_BYTES;
const SPIRIT_VFX_PRE_MARKER_SLOT: usize = 39;
const SPIRIT_VFX_POST_MARKER_SLOT: usize = 38;
const SPIRIT_VFX_PRE_MARKER: u32 = 0xC0DE_5F01;
const SPIRIT_VFX_POST_MARKER: u32 = 0xC0DE_5F02;

// Video-frame-only PIPE_CONTROL timestamp QWords. Each timestamp consumes two
// naturally aligned DWORD result slots. They deliberately do not overlap the
// shared UI4 completion cookie at slots 24-25.
const UI4_VIDEO_FRAME_GPU_PRE_WALKER_TIMESTAMP_SLOT: usize = 40;
const UI4_VIDEO_FRAME_GPU_POST_WALKER_TIMESTAMP_SLOT: usize = 42;
const UI4_VIDEO_FRAME_GPU_BATCH_ENTER_TIMESTAMP_SLOT: usize = 44;
const UI4_VIDEO_FRAME_GPU_POST_RELEASE_TIMESTAMP_SLOT: usize = 46;
const _: () = assert!(UI4_VIDEO_FRAME_GPU_PRE_WALKER_TIMESTAMP_SLOT.is_multiple_of(2));
const _: () = assert!(UI4_VIDEO_FRAME_GPU_POST_WALKER_TIMESTAMP_SLOT.is_multiple_of(2));
const _: () = assert!(UI4_VIDEO_FRAME_GPU_BATCH_ENTER_TIMESTAMP_SLOT.is_multiple_of(2));
const _: () = assert!(UI4_VIDEO_FRAME_GPU_POST_RELEASE_TIMESTAMP_SLOT.is_multiple_of(2));
const SPIRIT_VFX_COMPLETION_TIMEOUT_MS: u64 = 1_000;
const SPIRIT_VFX_CONTROL_MAGIC: u32 = 0x5356_4658;
const SPIRIT_VFX_CONTROL_VERSION: u32 = 1;
const _: () = assert!(
    SPIRIT_VFX_SPRITE_PAYLOAD_OFFSET_BYTES + SPIRIT_VFX_SPRITE_INDIRECT_BYTES
        <= DIRECT_RCS_BATCH_BYTES
);
const _: () = assert!(LAB256_POST_MARKER_SLOT.is_multiple_of(2));
const _: () = assert!(
    LAB256_COMPOSITE_PAYLOAD_OFFSET_BYTES + LAB256_INDIRECT_BYTES <= DIRECT_RCS_BATCH_BYTES
);
pub(crate) const FONT_OUTLINE_STAGE_AUDIT: u32 = 1;
pub(crate) const FONT_OUTLINE_STAGE_FLATTEN: u32 = 2;
pub(crate) const FONT_OUTLINE_STAGE_STROKE_MESH: u32 = 3;
pub(crate) const PIXEL_PLASMA_FLAG_VIGNETTE: u32 = 1 << 0;
pub(crate) const PIXEL_PLASMA_FLAG_RINGS: u32 = 1 << 1;
pub(crate) const PIXEL_PLASMA_FLAG_SCANLINE: u32 = 1 << 2;
pub(crate) const PIXEL_PLASMA_FLAG_FIELD_PALETTE: u32 = 1 << 3;

const COPY_RECT_POST_MARKER_SLOT: usize = 4;
// PIPE_CONTROL post-sync writes a QWord, so slot 5 is reserved for the high
// DWORD of the completion cookie. Keep the diagnostic pre marker outside that
// pair.
const COPY_RECT_PRE_MARKER_SLOT: usize = 6;
const COPY_RECT_PRE_MARKER: u32 = 0xC0DE_A701;
const COPY_RECT_POST_MARKER: u32 = 0xC0DE_A702;
const _: () = assert!(COPY_RECT_POST_MARKER_SLOT.is_multiple_of(2));
const _: () = assert!(COPY_RECT_PRE_MARKER_SLOT != COPY_RECT_POST_MARKER_SLOT);
const _: () = assert!(COPY_RECT_PRE_MARKER_SLOT != COPY_RECT_POST_MARKER_SLOT + 1);

const CLEAR_RECT_IDD_OFFSET_BYTES: usize = 0x300;
const CLEAR_RECT_BINDING_TABLE_OFFSET_BYTES: usize = 0x340;
const CLEAR_RECT_SURFACE_STATE_OFFSET_BYTES: usize = 0x380;
const CLEAR_RECT_PAYLOAD_OFFSET_BYTES: usize = 0x500;
const CLEAR_RECT_IDD_BYTES: usize = 8 * core::mem::size_of::<u32>();
const CLEAR_RECT_SURFACE_STATE_DWORDS: usize = 16;
const CLEAR_RECT_CROSS_THREAD_BYTES: usize = 96;
const CLEAR_RECT_PER_THREAD_BYTES: usize = 96;
const CLEAR_RECT_INDIRECT_BYTES: usize =
    CLEAR_RECT_CROSS_THREAD_BYTES + CLEAR_RECT_PER_THREAD_BYTES;
const CLEAR_RECT_TEST_BYTES: usize = 16 * 1024;
const CLEAR_RECT_PRE_MARKER_SLOT: usize = 3;
const CLEAR_RECT_POST_MARKER_SLOT: usize = 2;
const CLEAR_RECT_PRE_MARKER: u32 = 0xC0DE_C701;
const CLEAR_RECT_POST_MARKER: u32 = 0xC0DE_C702;

const SURFTYPE_BUFFER: u32 = 4;
const SURFACE_FORMAT_RAW: u32 = 0x1FF;

const DIRECT_RCS_ENABLED: bool = true;
const DIRECT_RCS_RING_BYTES: usize = 4096;
const DIRECT_RCS_CONTEXT_BYTES: usize = 22 * 4096;
const DIRECT_RCS_BATCH_BYTES: usize = 256 * 1024;
const EXECUTION_RCS_JOB_SLOTS: usize = 2;
// Worst case: every descriptor changes texture, so each contributes one
// four-DWORD IDD load, one 15-DWORD walker, one two-DWORD state flush, and one
// six-DWORD ordering PIPE_CONTROL.  The fixed allowance covers the prologue,
// markers, and epilogue.  These assertions make command/state aliasing a
// build-time failure instead of a GPU hang.
const SPRITE_QUAD_WORKLIST_MAX_COMMAND_DWORDS: usize = 128 + SPRITE_QUAD_WORKLIST_MAX_DESCS * 27;
const _: () = assert!(
    SPRITE_QUAD_WORKLIST_MAX_COMMAND_DWORDS * core::mem::size_of::<u32>()
        <= SPRITE_QUAD_WORKLIST_STATE_BASE_OFFSET_BYTES
);
const _: () = assert!(
    SPRITE_QUAD_WORKLIST_STATE_BASE_OFFSET_BYTES
        + SPRITE_QUAD_WORKLIST_MAX_DESCS * SPRITE_QUAD_WORKLIST_RUN_STATE_BLOCK_BYTES
        + SPRITE_QUAD_WORKLIST_MAX_DESCS * SPRITE_QUAD_WORKLIST_INDIRECT_BYTES
        <= DIRECT_RCS_BATCH_BYTES
);
const _: () = assert!(
    512 + GLYPH_MASK_BATCH_MAX_LAYERS * 27
        < GLYPH_MASK_BATCH_STATE_BASE_OFFSET_BYTES / core::mem::size_of::<u32>()
);
const _: () = assert!(
    GLYPH_MASK_BATCH_STATE_BASE_OFFSET_BYTES
        + GLYPH_MASK_BATCH_MAX_LAYERS * GLYPH_MASK_BATCH_STATE_BLOCK_BYTES
        <= GLYPH_MASK_BATCH_PAYLOAD_BASE_OFFSET_BYTES
);
const _: () = assert!(
    GLYPH_MASK_BATCH_PAYLOAD_BASE_OFFSET_BYTES
        + GLYPH_MASK_BATCH_MAX_LAYERS * GLYPH_MASK_PAYLOAD_STRIDE_BYTES
        <= DIRECT_RCS_BATCH_BYTES
);
const _: () = assert!(
    GLYPH_MASK_BATCH_PAYLOAD_BASE_OFFSET_BYTES
        .is_multiple_of(GPGPU_WALKER_INDIRECT_ALIGNMENT_BYTES)
);
const _: () =
    assert!(GLYPH_MASK_PAYLOAD_STRIDE_BYTES.is_multiple_of(GPGPU_WALKER_INDIRECT_ALIGNMENT_BYTES));
const _: () = assert!(
    512 + FONT_INSTANCE_BATCH_MAX_LAYERS * 27
        < FONT_INSTANCE_BATCH_STATE_BASE_OFFSET_BYTES / core::mem::size_of::<u32>()
);
const _: () = assert!(
    FONT_INSTANCE_BATCH_STATE_BASE_OFFSET_BYTES
        + FONT_INSTANCE_BATCH_MAX_LAYERS * FONT_INSTANCE_BATCH_STATE_BLOCK_BYTES
        <= FONT_INSTANCE_BATCH_PAYLOAD_BASE_OFFSET_BYTES
);
const _: () = assert!(
    FONT_INSTANCE_BATCH_PAYLOAD_BASE_OFFSET_BYTES
        + FONT_INSTANCE_BATCH_MAX_LAYERS * FONT_INSTANCE_PAYLOAD_STRIDE_BYTES
        <= DIRECT_RCS_BATCH_BYTES
);
const _: () = assert!(
    FONT_INSTANCE_BATCH_PAYLOAD_BASE_OFFSET_BYTES
        .is_multiple_of(GPGPU_WALKER_INDIRECT_ALIGNMENT_BYTES)
);
const _: () = assert!(
    FONT_INSTANCE_PAYLOAD_STRIDE_BYTES.is_multiple_of(GPGPU_WALKER_INDIRECT_ALIGNMENT_BYTES)
);
const _: () = assert!(
    FONT_OUTLINE_COVERAGE_BATCH_STATE_BASE_OFFSET_BYTES
        + FONT_OUTLINE_COVERAGE_BATCH_MAX_RUNS
            * FONT_OUTLINE_COVERAGE_BATCH_STATE_BLOCK_BYTES
        <= FONT_OUTLINE_COVERAGE_BATCH_PAYLOAD_BASE_OFFSET_BYTES
);
const _: () = assert!(
    512 + FONT_OUTLINE_COVERAGE_BATCH_MAX_RUNS * 27
        < FONT_OUTLINE_COVERAGE_BATCH_STATE_BASE_OFFSET_BYTES / core::mem::size_of::<u32>()
);
const _: () = assert!(
    FONT_OUTLINE_COVERAGE_BATCH_PAYLOAD_BASE_OFFSET_BYTES
        + FONT_OUTLINE_COVERAGE_BATCH_MAX_RUNS
            * FONT_OUTLINE_COVERAGE_BATCH_PAYLOAD_STRIDE_BYTES
        <= DIRECT_RCS_BATCH_BYTES
);
const _: () = assert!(
    FONT_OUTLINE_COVERAGE_BATCH_PAYLOAD_BASE_OFFSET_BYTES
        .is_multiple_of(GPGPU_WALKER_INDIRECT_ALIGNMENT_BYTES)
);
const _: () = assert!(
    FONT_OUTLINE_COVERAGE_BATCH_PAYLOAD_STRIDE_BYTES
        .is_multiple_of(GPGPU_WALKER_INDIRECT_ALIGNMENT_BYTES)
);
const DIRECT_RCS_RESULT_BYTES: usize = 4096;
const _: () = assert!(
    (UI4_VIDEO_FRAME_GPU_POST_RELEASE_TIMESTAMP_SLOT + 2) * core::mem::size_of::<u32>()
        <= DIRECT_RCS_RESULT_BYTES
);
const DIRECT_RCS_TIMESTAMP_BITS: u32 = 36;
const DIRECT_RCS_TIMESTAMP_MASK: u64 = (1u64 << DIRECT_RCS_TIMESTAMP_BITS) - 1;
const DIRECT_RCS_PPGTT_PT_COUNT: usize = 512;
const DIRECT_RCS_PPGTT_BYTES: usize = (3 + DIRECT_RCS_PPGTT_PT_COUNT) * 4096;
pub(crate) const DIRECT_RCS_PPGTT_LIMIT_BYTES: u64 =
    (DIRECT_RCS_PPGTT_PT_COUNT as u64) * 512 * 4096;
const DIRECT_RCS_LRC_STATE_OFFSET_DWORDS: usize = 4096 / core::mem::size_of::<u32>();
const DIRECT_RCS_BATCH_START_DWORDS: usize = 4;
// GuC registrations require stable HWLRCAs. Keep the GPGPU context window
// distinct from render-graphics' 0x0080_0000 window instead of remapping another
// allocation underneath the same registered context.
const DIRECT_RCS_GPU_VA_RING_BASE: u64 = 0x01B0_0000;
const DIRECT_RCS_GPU_VA_CONTEXT_BASE: u64 = 0x01B1_0000;
const DIRECT_RCS_GPU_VA_RESULT_BASE: u64 = 0x01B4_0000;
const DIRECT_RCS_GPU_VA_CLEAR_TEST_BASE: u64 = 0x0089_0000;

const DIRECT_RCS_GPU_VA_FONT_COVERAGE_OPS_BASE: u64 = 0x0440_0000;
const DIRECT_RCS_FONT_COVERAGE_OPS_WINDOW_BYTES: usize = 4 * 1024 * 1024;
// One tight or canvas stamp may reach the service's UHD/4K RGBA8 soft cap.
// The primary font VA range has room for one such allocation plus masks; the
// secondary range is exactly 32 MiB.
const DIRECT_RCS_FONT_COVERAGE_MASK_MAX_BYTES: usize = 32 * 1024 * 1024;
// Persistent masks must not alias one another in the direct-RCS PPGTT.  The
// first implementation remapped every simultaneously-live color layer at one
// fixed VA; cached translations could then read or write a different layer's
// physical allocation.  This range is private to the direct-RCS address space
// (the render context may independently use the same numeric addresses).
const DIRECT_RCS_GPU_VA_FONT_COVERAGE_BASE: u64 = 0x0A00_0000;
const DIRECT_RCS_GPU_VA_FONT_COVERAGE_PRIMARY_LIMIT: u64 = 0x0D00_0000;
const DIRECT_RCS_GPU_VA_FONT_COVERAGE_SECONDARY_BASE: u64 = 0x0E00_0000;
const DIRECT_RCS_GPU_VA_FONT_COVERAGE_LIMIT: u64 = 0x1000_0000;
const _: () = assert!(DIRECT_RCS_GPU_VA_FONT_COVERAGE_BASE.is_multiple_of(4096));
const _: () = assert!(DIRECT_RCS_GPU_VA_FONT_COVERAGE_LIMIT.is_multiple_of(4096));
const _: () =
    assert!(DIRECT_RCS_GPU_VA_FONT_COVERAGE_BASE < DIRECT_RCS_GPU_VA_FONT_COVERAGE_PRIMARY_LIMIT);
const _: () = assert!(
    DIRECT_RCS_GPU_VA_FONT_COVERAGE_PRIMARY_LIMIT < DIRECT_RCS_GPU_VA_FONT_COVERAGE_SECONDARY_BASE
);
const _: () =
    assert!(DIRECT_RCS_GPU_VA_FONT_COVERAGE_SECONDARY_BASE < DIRECT_RCS_GPU_VA_FONT_COVERAGE_LIMIT);
const _: () = assert!(DIRECT_RCS_GPU_VA_FONT_COVERAGE_LIMIT <= DIRECT_RCS_PPGTT_LIMIT_BYTES);
// Font Rush keeps four run-owned RGBA8 atlases at stable addresses in the
// Font context's private PPGTT. These numeric addresses may overlap resources
// in another RCS context without aliasing: only the Font page-table root can
// resolve these leaves. The complete atlas window ends exactly where dynamic
// UI producer surfaces begin in that same address space.
pub(crate) const GPGPU_FONT_RUSH_RGBA8_ATLAS_COUNT: usize = 4;
pub(crate) const GPGPU_FONT_RUSH_RGBA8_ATLAS_WIDTH: u32 = 2048;
pub(crate) const GPGPU_FONT_RUSH_RGBA8_ATLAS_HEIGHT: u32 = 1024;
pub(crate) const GPGPU_FONT_RUSH_RGBA8_ATLAS_PITCH_BYTES: u32 =
    GPGPU_FONT_RUSH_RGBA8_ATLAS_WIDTH * core::mem::size_of::<u32>() as u32;
pub(crate) const GPGPU_FONT_RUSH_RGBA8_ATLAS_BYTES: usize = 8 * 1024 * 1024;
const FONT_RCS_GPU_VA_RUSH_RGBA8_BASE: u64 = 0x1000_0000;
const FONT_RCS_GPU_VA_RUSH_RGBA8_LIMIT: u64 = 0x1200_0000;

const fn font_rush_rgba8_atlas_gpu(class: u8) -> Option<u64> {
    if (class as usize) >= GPGPU_FONT_RUSH_RGBA8_ATLAS_COUNT {
        return None;
    }
    Some(
        FONT_RCS_GPU_VA_RUSH_RGBA8_BASE + (class as u64) * GPGPU_FONT_RUSH_RGBA8_ATLAS_BYTES as u64,
    )
}

const fn is_exact_font_rush_rgba8_atlas_range(gpu: u64, len: usize) -> bool {
    if len != GPGPU_FONT_RUSH_RGBA8_ATLAS_BYTES
        || gpu < FONT_RCS_GPU_VA_RUSH_RGBA8_BASE
        || gpu >= FONT_RCS_GPU_VA_RUSH_RGBA8_LIMIT
    {
        return false;
    }
    (gpu - FONT_RCS_GPU_VA_RUSH_RGBA8_BASE).is_multiple_of(GPGPU_FONT_RUSH_RGBA8_ATLAS_BYTES as u64)
}

const _: () = assert!(
    GPGPU_FONT_RUSH_RGBA8_ATLAS_PITCH_BYTES as usize * GPGPU_FONT_RUSH_RGBA8_ATLAS_HEIGHT as usize
        == GPGPU_FONT_RUSH_RGBA8_ATLAS_BYTES
);
const _: () = assert!(FONT_RCS_GPU_VA_RUSH_RGBA8_BASE.is_multiple_of(4096));
const _: () = assert!(FONT_RCS_GPU_VA_RUSH_RGBA8_LIMIT.is_multiple_of(4096));
const _: () = assert!(
    FONT_RCS_GPU_VA_RUSH_RGBA8_BASE
        + (GPGPU_FONT_RUSH_RGBA8_ATLAS_COUNT * GPGPU_FONT_RUSH_RGBA8_ATLAS_BYTES) as u64
        == FONT_RCS_GPU_VA_RUSH_RGBA8_LIMIT
);
const _: () =
    assert!(FONT_RCS_GPU_VA_RUSH_RGBA8_LIMIT == crate::r::ui_surface::UI_SURFACE_GPU_BASE);
const _: () = assert!(FONT_RCS_GPU_VA_RUSH_RGBA8_LIMIT <= DIRECT_RCS_PPGTT_LIMIT_BYTES);
// ParticleCraft instances retain their own state/control allocation. This
// direct-RCS-only VA window is disjoint from both persistent font masks and
// UI4 frame surfaces, so two live Blueprint windows never remap one another.
const DIRECT_RCS_GPU_VA_PARTICLE_CRAFT_BASE: u64 = 0x1000_0000;
const DIRECT_RCS_GPU_VA_PARTICLE_CRAFT_LIMIT: u64 = 0x1100_0000;
const _: () = assert!(DIRECT_RCS_GPU_VA_PARTICLE_CRAFT_BASE.is_multiple_of(4096));
const _: () = assert!(DIRECT_RCS_GPU_VA_PARTICLE_CRAFT_LIMIT.is_multiple_of(4096));
const _: () =
    assert!(DIRECT_RCS_GPU_VA_FONT_COVERAGE_LIMIT <= DIRECT_RCS_GPU_VA_PARTICLE_CRAFT_BASE);
const _: () =
    assert!(DIRECT_RCS_GPU_VA_PARTICLE_CRAFT_LIMIT <= crate::r::ui_surface::UI_SURFACE_GPU_BASE);
const _: () = assert!(DIRECT_RCS_GPU_VA_PARTICLE_CRAFT_LIMIT <= DIRECT_RCS_PPGTT_LIMIT_BYTES);
const DIRECT_RCS_GPU_VA_BATCH_BASE: u64 = 0x01C0_0000;
// Continuously executing programs receive a distinct GGTT control window,
// HWLRCA, PPGTT root, and vGPU timeline. Keeping this window separate from the
// system-service direct-RCS window lets GuC schedule both contexts without one
// producer rewriting another producer's ring, batch, result, or page tables.
const EXECUTION_RCS_GPU_VA_RING_BASE: u64 = 0x0800_0000;
const EXECUTION_RCS_GPU_VA_CONTEXT_BASE: u64 = 0x0801_0000;
const EXECUTION_RCS_GPU_VA_RESULT_BASE: u64 = 0x0804_0000;
const EXECUTION_RCS_GPU_VA_BATCH_BASE: u64 = 0x0810_0000;
// LFM owns a persistent compute context and PPGTT. The native model mapping is
// intentionally absent from every display/system-service address space.
const LFM25_RCS_GPU_VA_RING_BASE: u64 = 0x0820_0000;
const LFM25_RCS_GPU_VA_CONTEXT_BASE: u64 = 0x0821_0000;
const LFM25_RCS_GPU_VA_RESULT_BASE: u64 = 0x0824_0000;
const LFM25_RCS_GPU_VA_BATCH_BASE: u64 = 0x0830_0000;
// Font Engine owns a separate GuC client and control window. Its PPGTT may
// reuse the font resource virtual addresses below because no other client can
// mutate this root or its ring/batch/result storage.
const FONT_RCS_GPU_VA_RING_BASE: u64 = 0x0840_0000;
const FONT_RCS_GPU_VA_CONTEXT_BASE: u64 = 0x0841_0000;
const FONT_RCS_GPU_VA_RESULT_BASE: u64 = 0x0844_0000;
const FONT_RCS_GPU_VA_BATCH_BASE: u64 = 0x0850_0000;
const _: () = assert!(
    EXECUTION_RCS_GPU_VA_RESULT_BASE + (EXECUTION_RCS_JOB_SLOTS * DIRECT_RCS_RESULT_BYTES) as u64
        <= EXECUTION_RCS_GPU_VA_BATCH_BASE
);
const _: () = assert!(
    EXECUTION_RCS_GPU_VA_BATCH_BASE + (EXECUTION_RCS_JOB_SLOTS * DIRECT_RCS_BATCH_BYTES) as u64
        <= LFM25_RCS_GPU_VA_RING_BASE
);
const _: () = assert!(
    LFM25_RCS_GPU_VA_BATCH_BASE + DIRECT_RCS_BATCH_BYTES as u64 <= FONT_RCS_GPU_VA_RING_BASE
);
const _: () = assert!(
    FONT_RCS_GPU_VA_BATCH_BASE + DIRECT_RCS_BATCH_BYTES as u64
        <= DIRECT_RCS_GPU_VA_FONT_COVERAGE_BASE
);
// A compositor submission is intentionally allowed to remain in flight while
// the ordinary GPGPU client services video, fonts, and application compute.
// These GGTT addresses back a distinct HWLRCA/ring/batch/result set; the
// compositor also owns a distinct PPGTT root and vGPU principal below.
const UI4_COMPOSITOR_RCS_GPU_VA_RING_BASE: u64 = 0x01D0_0000;
const UI4_COMPOSITOR_RCS_GPU_VA_CONTEXT_BASE: u64 = 0x01D1_0000;
const UI4_COMPOSITOR_RCS_GPU_VA_RESULT_BASE: u64 = 0x01D4_0000;
const UI4_COMPOSITOR_RCS_GPU_VA_BATCH_BASE: u64 = 0x01E0_0000;
// Two immutable job slots match the decoded-video lifetime budget: one RCS
// conversion may execute while the following decoded picture remains queued.
// Each slot owns a complete batch, result page, and 16 MiB source-alias
// window. The ring and HWLRCA stay shared so both tails target one persistent
// GuC context instead of repeatedly draining a one-job software lane.
pub(crate) const UI4_COMPOSITOR_RCS_JOB_SLOTS: usize = 2;
// The decoder's `gpu_addr` belongs to the media-engine address space. Never
// borrow that number as an RCS PPGTT VA. Each queued video conversion owns one
// compositor-private PAT0 alias until its GuC completion marker retires, so a
// following frame never retargets PTEs which an earlier batch can still read.
// Each 16 MiB window matches the media output backing; the two-slot range stays
// disjoint from both persistent font resources and UI4 RGBA VAs.
pub(crate) const UI4_COMPOSITOR_NV12_SOURCE_GPU_BASE: u64 = 0x1000_0000;
const UI4_COMPOSITOR_NV12_SOURCE_MAX_BYTES: usize = 16 * 1024 * 1024;
// Keep the encoder destination outside both decoder source slots and the
// complete UI-surface arena. The former base+one-slot address collided with
// decoder slot 1 whenever local playback and RDP conversion overlapped.
pub(crate) const UI4_STREAM_NV12_DESTINATION_GPU: u64 = crate::r::ui_surface::UI_SURFACE_GPU_LIMIT;
const _: () = assert!(UI4_COMPOSITOR_NV12_SOURCE_GPU_BASE.is_multiple_of(4096));
const _: () = assert!(
    UI4_COMPOSITOR_NV12_SOURCE_GPU_BASE
        + (UI4_COMPOSITOR_RCS_JOB_SLOTS * UI4_COMPOSITOR_NV12_SOURCE_MAX_BYTES) as u64
        <= crate::r::ui_surface::UI_SURFACE_GPU_BASE
);
const _: () = assert!(UI4_COMPOSITOR_NV12_SOURCE_GPU_BASE >= DIRECT_RCS_GPU_VA_FONT_COVERAGE_LIMIT);
const _: () = assert!(
    UI4_STREAM_NV12_DESTINATION_GPU + UI4_COMPOSITOR_NV12_SOURCE_MAX_BYTES as u64
        <= DIRECT_RCS_PPGTT_LIMIT_BYTES
);
const _: () = assert!(
    UI4_COMPOSITOR_RCS_GPU_VA_RESULT_BASE
        + (UI4_COMPOSITOR_RCS_JOB_SLOTS * DIRECT_RCS_RESULT_BYTES) as u64
        <= UI4_COMPOSITOR_RCS_GPU_VA_BATCH_BASE
);
const DIRECT_RCS_SMOKE_POLL_ITERS: usize = 262_144;
const DIRECT_RCS_TIMEOUT_POLL_PAUSE_ITERS: usize = 64;
