#!/usr/bin/env python3
"""Build deterministic Blueprint shader packages; retain only trust metadata in TRUEOS.

Use --check in validation, or --update-trust after reviewing a reproducible bake.
The package hash covers the raw GLSL, generated C++, SPIR-V, Zebin and provenance.
"""
import argparse
import hashlib
import struct
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
NAMES = ("mandelbrot", "cube_field", "nguyen", "palette_grid", "cosmic_strands")
FILES = ("kernel.bin", "kernel.spv", "input.glsl", "kernel.clcpp",
         "kernel.manifest.json", "kernel.contract.rs")
MAGIC = b"STPKG01\0"


def package(directory):
    parts = [(directory / name).read_bytes() for name in FILES]
    return MAGIC + struct.pack("<6I", *(len(part) for part in parts)) + b"".join(parts), parts


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--blueprints-root", type=Path, default=ROOT.parent / "TRUEOS-Blueprints")
    mode = parser.add_mutually_exclusive_group()
    mode.add_argument("--check", action="store_true")
    mode.add_argument("--update-trust", action="store_true")
    args = parser.parse_args()
    assets = args.blueprints_root / "apps/shadertoy/assets"
    generated = "// Generated by tools/shadertoy-cpp-offline/package_blueprint.py --update-trust.\n"
    generated += "// Trusted metadata only: no shader payload is linked into the kernel.\n"
    for shader_id, name in enumerate(NAMES, 1):
        data, parts = package(assets / name)
        contract = ROOT / f"crates/trueos-shader/gpgpu/kernels/artifacts/adls/cpp/shadertoy_{name}.contract.rs"
        if contract.read_bytes() != parts[5]:
            raise SystemExit(f"{name}: Blueprint contract differs from kernel trust contract")
        output = assets / f"{name}.stpkg"
        if args.check:
            if output.read_bytes() != data:
                raise SystemExit(f"{output}: stale package")
        else:
            output.write_bytes(data)
        digest = ", ".join(f"0x{x:02x}" for x in hashlib.sha256(data).digest())
        generated += f"pub(crate) const SHADERTOY_{name.upper()}_PACKAGE: ShaderToyPackageContract = ShaderToyPackageContract {{\n"
        generated += f"    shader_id: {shader_id}, bytes: {len(data)}, bin_bytes: {len(parts[0])}, spv_bytes: {len(parts[1])},\n"
        generated += f"    sha256: [{digest}],\n}};\n"
        print(f"{name}: {len(data)} package bytes, {len(parts[0])} executable bytes")
    trust = ROOT / "src/intel/gpgpu/artifacts/shadertoy_packages.rs"
    if args.update_trust:
        trust.write_text(generated)
    elif not trust.exists() or trust.read_text() != generated:
        raise SystemExit("Package trust metadata changed; review the bake and use --update-trust")


if __name__ == "__main__":
    main()
