#!/usr/bin/env python3
"""Build deterministic Blueprint shader packages; retain only trust metadata in TRUEOS.

Use --check in validation, or --update-trust after reviewing a reproducible bake.
The package hash covers the raw GLSL, generated C++, SPIR-V, Zebin and provenance.
"""
import argparse
import hashlib
import json
import struct
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
NAMES = ("mandelbrot", "cube_field", "nguyen", "palette_grid", "cosmic_strands", "protean_clouds")
# Selector IDs 9..14 share the gallery's authenticated program (8).
NATIVE_PROGRAMS = {7: ("audio_visualizer", "cpp_audio_visualizer_rgba8"),
                   8: ("cpp_gallery", "cpp_demo_rgba8"),
                   15: ("particle_craft", "particle_craft")}
PROGRAMS = tuple(enumerate(NAMES, 1)) + tuple((i, n) for i, (n, _) in NATIVE_PROGRAMS.items())
FILES = ("kernel.bin", "kernel.spv", "input.glsl", "kernel.clcpp",
         "kernel.manifest.json", "kernel.contract.rs")
MAGIC = b"STPKG01\0"


def package(directory):
    files = list(FILES)
    if directory.name in {name for name, _ in NATIVE_PROGRAMS.values()}:
        files[2] = "input.sources.json"
    parts = [(directory / name).read_bytes() for name in files]
    return MAGIC + struct.pack("<6I", *(len(part) for part in parts)) + b"".join(parts), parts


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--blueprints-root", type=Path, default=ROOT.parent / "TRUEOS-Blueprints")
    mode = parser.add_mutually_exclusive_group()
    mode.add_argument("--check", action="store_true")
    mode.add_argument("--update-trust", action="store_true")
    args = parser.parse_args()
    assets = args.blueprints_root / "apps/shadertoy/assets"
    generated = "// Generated by tools/shadertoy-cpp-offline/package_blueprint.py --update-trust.\n"
    generated += "// Trusted metadata only: no shader payload is linked into the kernel.\n"
    for shader_id, name in PROGRAMS:
        data, parts = package(assets / name)
        manifest = json.loads(parts[4])
        source = manifest["source"]
        inputs = {entry["path"]: entry for entry in source["inputs"]}
        if inputs[source["path"]]["sha256"] != hashlib.sha256(parts[3]).hexdigest():
            raise SystemExit(f"{name}: generated C++ differs from baked source provenance")
        artifact = NATIVE_PROGRAMS[shader_id][1] if shader_id in NATIVE_PROGRAMS else f"shadertoy_{name}"
        if shader_id in NATIVE_PROGRAMS:
            archive = json.loads(parts[2])
            if set(archive) != set(inputs):
                raise SystemExit(f"{name}: incomplete raw source archive")
            for path, entry in inputs.items():
                if hashlib.sha256(archive[path].encode()).hexdigest() != entry["sha256"]:
                    raise SystemExit(f"{name}: archived input differs from baked provenance: {path}")
            if archive[source["path"]].encode() != parts[3]:
                raise SystemExit(f"{name}: entry source differs from source archive")
        contract = ROOT / f"crates/trueos-shader/gpgpu/kernels/artifacts/adls/cpp/{artifact}.contract.rs"
        if contract.read_bytes() != parts[5]:
            raise SystemExit(f"{name}: Blueprint contract differs from kernel trust contract")
        output = assets / f"{name}.stpkg"
        if args.check:
            if output.read_bytes() != data:
                raise SystemExit(f"{output}: stale package")
        else:
            output.write_bytes(data)
        digest = ", ".join(f"0x{x:02x}" for x in hashlib.sha256(data).digest())
        generated += f"pub(crate) const SHADERTOY_{name.upper()}_PACKAGE: ShaderToyPackageContract = ShaderToyPackageContract {{\n"
        generated += f"    shader_id: {shader_id}, bytes: {len(data)}, bin_bytes: {len(parts[0])}, spv_bytes: {len(parts[1])},\n"
        generated += f"    sha256: [{digest}],\n}};\n"
        print(f"{name}: {len(data)} package bytes, {len(parts[0])} executable bytes")
    trust = ROOT / "src/intel/gpgpu/artifacts/shadertoy_packages.rs"
    if args.update_trust:
        trust.write_text(generated)
    elif not trust.exists() or trust.read_text() != generated:
        raise SystemExit("Package trust metadata changed; review the bake and use --update-trust")


if __name__ == "__main__":
    main()
