// @generated by TRUEGA tools/tga-gen; do not hand-edit.
// This is ordinary host Rust metadata. It contains no HDL/compiler runtime.

use super::{FunctionDescriptor, FunctionId};

pub const LED_STEP_HEARTBEAT: FunctionId = FunctionId::SLOT_0;
pub const ADD_U32: FunctionId = FunctionId::SLOT_1;
pub const XOR_U32: FunctionId = FunctionId::SLOT_2;
pub const HEARTBEAT_REPLY: u32 = 0x5453_4154; // "TGAT"
pub const FIRMWARE_RTL_SHA256: [u8; 32] = [
    0x05, 0xed, 0x0f, 0x00, 0xff, 0x48, 0x97, 0xac, 
    0xaa, 0xb6, 0x6c, 0x3c, 0xf5, 0xa2, 0xf3, 0x3a, 
    0xc2, 0x67, 0x2b, 0xa5, 0xdb, 0x45, 0x6b, 0x76, 
    0xc3, 0x8a, 0x62, 0x19, 0x62, 0xf1, 0xad, 0x8d, 
];

pub const FUNCTIONS: [FunctionDescriptor; 3] = [
    FunctionDescriptor { id: LED_STEP_HEARTBEAT.raw(), input_bytes: 0, output_bytes: 4, flags: 0, symbol_hash: 0x63d2650b82c72268 },
    FunctionDescriptor { id: ADD_U32.raw(), input_bytes: 8, output_bytes: 4, flags: 0, symbol_hash: 0xe32d0cd1379e9cdf },
    FunctionDescriptor { id: XOR_U32.raw(), input_bytes: 8, output_bytes: 4, flags: 0, symbol_hash: 0xafcad32a26d65e41 },
];

pub fn binary_u32_args(a: u32, b: u32) -> [u8; 8] {
	let mut bytes = [0; 8];
	bytes[..4].copy_from_slice(&a.to_le_bytes());
	bytes[4..].copy_from_slice(&b.to_le_bytes());
	bytes
}

pub fn result_u32(bytes: &[u8]) -> Option<u32> {
	Some(u32::from_le_bytes(bytes.get(..4)?.try_into().ok()?))
}
