// @generated by TRUEGA tools/tga-gen; do not hand-edit.
// This is ordinary host Rust metadata. It contains no HDL/compiler runtime.

use super::{FunctionDescriptor, FunctionId};

pub const LED_STEP_HEARTBEAT: FunctionId = FunctionId::SLOT_0;
pub const ADD_U32: FunctionId = FunctionId::SLOT_1;
pub const XOR_U32: FunctionId = FunctionId::SLOT_2;
pub const HEARTBEAT_REPLY: u32 = 0x54534154; // "TGAT"
pub const FIRMWARE_RTL_SHA256: [u8; 32] = [
    0x34, 0x62, 0xaf, 0x5d, 0x08, 0x6f, 0x7d, 0xa4, 0x6f, 0x32, 0x4e, 0xb7, 0x76, 0x66, 0x0e, 0xbd,
    0xd6, 0xc3, 0x73, 0x52, 0x9b, 0x86, 0xf9, 0xc4, 0x2e, 0x46, 0x6f, 0x03, 0x6f, 0xe5, 0x72, 0x47,
];

pub const FUNCTIONS: [FunctionDescriptor; 3] = [
    FunctionDescriptor {
        id: LED_STEP_HEARTBEAT.raw(),
        input_bytes: 0,
        output_bytes: 4,
        flags: 0,
        symbol_hash: 0x63d2650b82c72268,
    },
    FunctionDescriptor {
        id: ADD_U32.raw(),
        input_bytes: 8,
        output_bytes: 4,
        flags: 0,
        symbol_hash: 0xe32d0cd1379e9cdf,
    },
    FunctionDescriptor {
        id: XOR_U32.raw(),
        input_bytes: 8,
        output_bytes: 4,
        flags: 0,
        symbol_hash: 0xafcad32a26d65e41,
    },
];

pub fn binary_u32_args(a: u32, b: u32) -> [u8; 8] {
    let mut bytes = [0; 8];
    bytes[..4].copy_from_slice(&a.to_le_bytes());
    bytes[4..].copy_from_slice(&b.to_le_bytes());
    bytes
}

pub fn result_u32(bytes: &[u8]) -> Option<u32> {
    Some(u32::from_le_bytes(bytes.get(..4)?.try_into().ok()?))
}
