// @generated by TRUEGA tools/tga-gen; do not hand-edit.
// This is ordinary host Rust metadata. It contains no HDL/compiler runtime.

use super::{
    AotCodecError, AotCompletionKind, AotFirmwareCapability, AotFixedShape, AotLane,
    AotLaneOwnership, AotOpDescriptor, AotScalarFormat, AotStateOwnership, AotTensorDescriptor,
    AotTransportKind, FirmwareManifest, FunctionDescriptor, FunctionId, TruegaCustomOp,
};

pub const LED_STEP_HEARTBEAT: FunctionId = FunctionId::SLOT_0;
pub const ADD_U32: FunctionId = FunctionId::SLOT_1;
pub const LFM25_FFN_STEP: FunctionId = FunctionId::SLOT_2;
pub const HEARTBEAT_REPLY: u32 = 0x54534154; // "TGAT"
pub const FIRMWARE_RTL_SHA256: [u8; 32] = [
    0x8b, 0x3f, 0x38, 0xe2, 0x85, 0x6c, 0x0a, 0xd1, 0x73, 0x6a, 0x2d, 0xce, 0x1e, 0x80, 0x2e, 0xf0,
    0x91, 0xf3, 0x57, 0x39, 0x20, 0x40, 0xcb, 0xc0, 0xfb, 0x65, 0x7d, 0xa7, 0xc6, 0x6c, 0x80, 0x0a,
];

pub const FUNCTIONS: [FunctionDescriptor; 3] = [
    FunctionDescriptor {
        id: LED_STEP_HEARTBEAT.raw(),
        input_bytes: 0,
        output_bytes: 4,
        flags: 0,
        symbol_hash: 0x63d2650b82c72268,
    },
    FunctionDescriptor {
        id: ADD_U32.raw(),
        input_bytes: 8,
        output_bytes: 4,
        flags: 0,
        symbol_hash: 0xe32d0cd1379e9cdf,
    },
    FunctionDescriptor {
        id: LFM25_FFN_STEP.raw(),
        input_bytes: 72,
        output_bytes: 20,
        flags: 0,
        symbol_hash: 0x308beada59401db0,
    },
];

pub const FIRMWARE_MANIFEST: FirmwareManifest = FirmwareManifest {
    magic: super::FIRMWARE_MANIFEST_MAGIC,
    abi_version: super::ABI_VERSION,
    function_count: super::FUNCTION_COUNT as u16,
    work_package_bytes: core::mem::size_of::<super::WorkPackage>() as u32,
    flags: 0,
    rtl_sha256: FIRMWARE_RTL_SHA256,
    functions: FUNCTIONS,
    reserved: [0; 32],
};

pub mod led_step_heartbeat {
    use super::{
        AotCodecError, AotCompletionKind, AotFirmwareCapability, AotFixedShape, AotLane,
        AotLaneOwnership, AotOpDescriptor, AotScalarFormat, AotStateOwnership, AotTensorDescriptor,
        AotTransportKind, FunctionId, TruegaCustomOp, result_u32,
    };

    pub const ID: FunctionId = super::LED_STEP_HEARTBEAT;
    pub const INPUT_BYTES: usize = 0;
    pub const OUTPUT_BYTES: usize = 4;
    pub const CONTRACT_SHA256: [u8; 32] = [
        0x29, 0x16, 0x0f, 0x74, 0x33, 0x25, 0x46, 0x76, 0x14, 0xdf, 0xe9, 0xd5, 0xfc, 0xea, 0xf7,
        0x11, 0x19, 0x33, 0xc6, 0x79, 0xa6, 0x1c, 0x26, 0x65, 0x7f, 0xfe, 0x64, 0x69, 0xd3, 0xc0,
        0x9e, 0xa3,
    ];
    pub const AOT_INPUTS: &[AotTensorDescriptor] = &[];
    pub const AOT_OUTPUTS: &[AotTensorDescriptor] = &[AotTensorDescriptor {
        name: "reply",
        scalar: AotScalarFormat::U32,
        shape: AotFixedShape::SCALAR,
        encoded_bytes: 4,
    }];
    pub const AOT_DESCRIPTOR: AotOpDescriptor = AotOpDescriptor {
        name: "led_step_heartbeat",
        contract_sha256: CONTRACT_SHA256,
        transport: AotTransportKind::InlineBar0WorkPackage,
        inputs: AOT_INPUTS,
        outputs: AOT_OUTPUTS,
        firmware: AotFirmwareCapability::FunctionSlot {
            function: ID,
            symbol_hash: 0x63d2650b82c72268,
        },
        lane: AotLane::Bar0WorkPackage,
        lane_ownership: AotLaneOwnership::SingleWorkerExclusive,
        state_ownership: AotStateOwnership::HostRequestFpgaCompletion,
        completion: AotCompletionKind::MsiWorkerCallback,
    };
    pub enum AotOp {}
    impl TruegaCustomOp for AotOp {
        type Input = ();
        type Output = u32;
        const DESCRIPTOR: AotOpDescriptor = AOT_DESCRIPTOR;
        fn encode(_: &Self::Input, _: &mut [u8]) -> Result<usize, AotCodecError> {
            Ok(0)
        }
        fn decode(source: &[u8]) -> Result<Self::Output, AotCodecError> {
            decode(source).ok_or(AotCodecError::InvalidEncoding)
        }
    }
    pub const fn encode() -> [u8; 0] {
        []
    }
    pub fn decode(bytes: &[u8]) -> Option<u32> {
        result_u32(bytes)
    }
}

pub mod add_u32 {
    use super::{
        AotCodecError, AotCompletionKind, AotFirmwareCapability, AotFixedShape, AotLane,
        AotLaneOwnership, AotOpDescriptor, AotScalarFormat, AotStateOwnership, AotTensorDescriptor,
        AotTransportKind, FunctionId, TruegaCustomOp, result_u32,
    };

    pub const ID: FunctionId = super::ADD_U32;
    pub const INPUT_BYTES: usize = 8;
    pub const OUTPUT_BYTES: usize = 4;
    pub const CONTRACT_SHA256: [u8; 32] = [
        0xf9, 0xb4, 0xbd, 0x9d, 0xc2, 0x8b, 0x86, 0x8a, 0x5d, 0x92, 0x86, 0x60, 0xef, 0x7c, 0x0f,
        0x10, 0x9d, 0x27, 0xde, 0x23, 0x45, 0xde, 0xca, 0x6c, 0xc1, 0x66, 0x0f, 0xe8, 0xc8, 0xe4,
        0x1e, 0x2d,
    ];
    pub const AOT_INPUTS: &[AotTensorDescriptor] = &[
        AotTensorDescriptor {
            name: "a",
            scalar: AotScalarFormat::U32,
            shape: AotFixedShape::SCALAR,
            encoded_bytes: 4,
        },
        AotTensorDescriptor {
            name: "b",
            scalar: AotScalarFormat::U32,
            shape: AotFixedShape::SCALAR,
            encoded_bytes: 4,
        },
    ];
    pub const AOT_OUTPUTS: &[AotTensorDescriptor] = &[AotTensorDescriptor {
        name: "sum",
        scalar: AotScalarFormat::U32,
        shape: AotFixedShape::SCALAR,
        encoded_bytes: 4,
    }];
    pub const AOT_DESCRIPTOR: AotOpDescriptor = AotOpDescriptor {
        name: "add_u32",
        contract_sha256: CONTRACT_SHA256,
        transport: AotTransportKind::InlineBar0WorkPackage,
        inputs: AOT_INPUTS,
        outputs: AOT_OUTPUTS,
        firmware: AotFirmwareCapability::FunctionSlot {
            function: ID,
            symbol_hash: 0xe32d0cd1379e9cdf,
        },
        lane: AotLane::Bar0WorkPackage,
        lane_ownership: AotLaneOwnership::SingleWorkerExclusive,
        state_ownership: AotStateOwnership::HostRequestFpgaCompletion,
        completion: AotCompletionKind::MsiWorkerCallback,
    };
    pub enum AotOp {}
    impl TruegaCustomOp for AotOp {
        type Input = [u32; 2];
        type Output = u32;
        const DESCRIPTOR: AotOpDescriptor = AOT_DESCRIPTOR;
        fn encode(input: &Self::Input, destination: &mut [u8]) -> Result<usize, AotCodecError> {
            let destination = destination
                .get_mut(..INPUT_BYTES)
                .ok_or(AotCodecError::BufferTooSmall)?;
            destination.copy_from_slice(&encode(input[0], input[1]));
            Ok(INPUT_BYTES)
        }
        fn decode(source: &[u8]) -> Result<Self::Output, AotCodecError> {
            decode(source).ok_or(AotCodecError::InvalidEncoding)
        }
    }
    pub fn encode(a: u32, b: u32) -> [u8; 8] {
        let mut bytes = [0; 8];
        bytes[..4].copy_from_slice(&a.to_le_bytes());
        bytes[4..].copy_from_slice(&b.to_le_bytes());
        bytes
    }
    pub fn decode(bytes: &[u8]) -> Option<u32> {
        result_u32(bytes)
    }
}

pub mod lfm25_ffn_step {
    use super::{
        AotCodecError, AotCompletionKind, AotFirmwareCapability, AotFixedShape, AotLane,
        AotLaneOwnership, AotOpDescriptor, AotScalarFormat, AotStateOwnership, AotTensorDescriptor,
        AotTransportKind, FunctionId, TruegaCustomOp,
    };

    pub const ID: FunctionId = super::LFM25_FFN_STEP;
    pub const INPUT_BYTES: usize = 72;
    pub const OUTPUT_BYTES: usize = 20;
    pub const CONTRACT_SHA256: [u8; 32] = [
        0xfa, 0x08, 0xe3, 0x28, 0xbd, 0x30, 0x39, 0xc4, 0xb6, 0x95, 0x5b, 0xf3, 0xcb, 0x1a, 0x72,
        0x06, 0x98, 0xb6, 0x8e, 0x0c, 0x84, 0x9e, 0x51, 0x66, 0x9b, 0x9e, 0x7e, 0xfc, 0xe4, 0x87,
        0x37, 0x09,
    ];
    pub const AOT_INPUTS: &[AotTensorDescriptor] = &[
        AotTensorDescriptor {
            name: "control",
            scalar: AotScalarFormat::U32,
            shape: AotFixedShape::SCALAR,
            encoded_bytes: 4,
        },
        AotTensorDescriptor {
            name: "activation",
            scalar: AotScalarFormat::GgmlQ8_0,
            shape: AotFixedShape::vector(32),
            encoded_bytes: 34,
        },
        AotTensorDescriptor {
            name: "weight",
            scalar: AotScalarFormat::GgmlQ8_0,
            shape: AotFixedShape::vector(32),
            encoded_bytes: 34,
        },
    ];
    pub const AOT_OUTPUTS: &[AotTensorDescriptor] = &[
        AotTensorDescriptor {
            name: "dot",
            scalar: AotScalarFormat::I32,
            shape: AotFixedShape::SCALAR,
            encoded_bytes: 4,
        },
        AotTensorDescriptor {
            name: "term_q30",
            scalar: AotScalarFormat::I64Q30,
            shape: AotFixedShape::SCALAR,
            encoded_bytes: 8,
        },
        AotTensorDescriptor {
            name: "row_q30",
            scalar: AotScalarFormat::I64Q30,
            shape: AotFixedShape::SCALAR,
            encoded_bytes: 8,
        },
    ];
    pub const AOT_DESCRIPTOR: AotOpDescriptor = AotOpDescriptor {
        name: "lfm25_ffn_step",
        contract_sha256: CONTRACT_SHA256,
        transport: AotTransportKind::InlineBar0WorkPackage,
        inputs: AOT_INPUTS,
        outputs: AOT_OUTPUTS,
        firmware: AotFirmwareCapability::FunctionSlot {
            function: ID,
            symbol_hash: 0x308beada59401db0,
        },
        lane: AotLane::Bar0WorkPackage,
        lane_ownership: AotLaneOwnership::SingleWorkerExclusive,
        state_ownership: AotStateOwnership::HostRequestFpgaCompletion,
        completion: AotCompletionKind::MsiWorkerCallback,
    };
    pub enum AotOp {}
    impl TruegaCustomOp for AotOp {
        type Input = [u8; INPUT_BYTES];
        type Output = Q8RowBlockResult;
        const DESCRIPTOR: AotOpDescriptor = AOT_DESCRIPTOR;
        fn encode(input: &Self::Input, destination: &mut [u8]) -> Result<usize, AotCodecError> {
            let destination = destination
                .get_mut(..INPUT_BYTES)
                .ok_or(AotCodecError::BufferTooSmall)?;
            destination.copy_from_slice(input);
            Ok(INPUT_BYTES)
        }
        fn decode(source: &[u8]) -> Result<Self::Output, AotCodecError> {
            decode(source).ok_or(AotCodecError::InvalidEncoding)
        }
    }
    pub const Q8_0_BLOCK_BYTES: usize = 34;
    pub const GATE_ROW0_BLOCKS: usize = 32;
    pub const WIDE_ROW_BLOCKS: usize = 144;
    pub const GATE_ROW0_NATIVE_OFFSET: u64 = 0x048c9000;

    #[derive(Copy, Clone, Debug, Eq, PartialEq)]
    pub struct Q8RowBlockResult {
        pub dot: i32,
        pub term_q30: i64,
        pub row_q30: i64,
    }

    pub fn encode_projection(
        first: bool,
        last: bool,
        wide: bool,
        block_index: u8,
        activation: &[u8; Q8_0_BLOCK_BYTES],
        weight: &[u8; Q8_0_BLOCK_BYTES],
    ) -> [u8; INPUT_BYTES] {
        let mut bytes = [0; INPUT_BYTES];
        let control = u32::from(first)
            | (u32::from(last) << 1)
            | (u32::from(wide) << 2)
            | (u32::from(block_index) << 8);
        bytes[..4].copy_from_slice(&control.to_le_bytes());
        bytes[4..4 + Q8_0_BLOCK_BYTES].copy_from_slice(activation);
        bytes[4 + Q8_0_BLOCK_BYTES..].copy_from_slice(weight);
        bytes
    }

    pub fn encode(
        first: bool,
        last: bool,
        block_index: u8,
        activation: &[u8; Q8_0_BLOCK_BYTES],
        weight: &[u8; Q8_0_BLOCK_BYTES],
    ) -> [u8; INPUT_BYTES] {
        encode_projection(first, last, false, block_index, activation, weight)
    }

    pub fn encode_activation_cache(
        wide: bool,
        block_index: u8,
        activation: &[u8; Q8_0_BLOCK_BYTES],
    ) -> [u8; INPUT_BYTES] {
        let mut bytes = [0; INPUT_BYTES];
        let control = (u32::from(wide) << 2) | (1 << 4) | (u32::from(block_index) << 8);
        bytes[..4].copy_from_slice(&control.to_le_bytes());
        bytes[4..4 + Q8_0_BLOCK_BYTES].copy_from_slice(activation);
        bytes
    }

    pub fn encode_cached_pair(
        first: bool,
        last: bool,
        wide: bool,
        block_index: u8,
        weight0: &[u8; Q8_0_BLOCK_BYTES],
        weight1: &[u8; Q8_0_BLOCK_BYTES],
    ) -> [u8; INPUT_BYTES] {
        let mut bytes = [0; INPUT_BYTES];
        let control = u32::from(first)
            | (u32::from(last) << 1)
            | (u32::from(wide) << 2)
            | (1 << 5)
            | (u32::from(block_index) << 8);
        bytes[..4].copy_from_slice(&control.to_le_bytes());
        bytes[4..4 + Q8_0_BLOCK_BYTES].copy_from_slice(weight0);
        bytes[4 + Q8_0_BLOCK_BYTES..].copy_from_slice(weight1);
        bytes
    }

    pub fn encode_single(
        activation: &[u8; Q8_0_BLOCK_BYTES],
        weight: &[u8; Q8_0_BLOCK_BYTES],
    ) -> [u8; INPUT_BYTES] {
        encode(true, true, 0, activation, weight)
    }

    pub fn encode_silu(gate_q30: i64, up_q30: i64) -> [u8; INPUT_BYTES] {
        let mut bytes = [0; INPUT_BYTES];
        bytes[..4].copy_from_slice(&8u32.to_le_bytes());
        bytes[4..12].copy_from_slice(&gate_q30.to_le_bytes());
        bytes[12..20].copy_from_slice(&up_q30.to_le_bytes());
        bytes
    }

    pub fn decode(bytes: &[u8]) -> Option<Q8RowBlockResult> {
        Some(Q8RowBlockResult {
            dot: i32::from_le_bytes(bytes.get(..4)?.try_into().ok()?),
            term_q30: i64::from_le_bytes(bytes.get(4..12)?.try_into().ok()?),
            row_q30: i64::from_le_bytes(bytes.get(12..20)?.try_into().ok()?),
        })
    }

    pub const GOLDEN_ACTIVATION: [u8; Q8_0_BLOCK_BYTES] = [
        0x30, 0x18, 0x0d, 0xa8, 0xd4, 0x4e, 0x1f, 0x49, 0x16, 0xb6, 0xb3, 0x3c, 0x25, 0xa8, 0xe7,
        0xf6, 0x25, 0x89, 0x4a, 0xd2, 0xcf, 0xe7, 0x21, 0xb0, 0xda, 0x81, 0x2a, 0x08, 0x17, 0xd3,
        0x56, 0xa7, 0x1d, 0x21,
    ];
    pub const GOLDEN_WEIGHT: [u8; Q8_0_BLOCK_BYTES] = [
        0xb9, 0x0c, 0x7a, 0x14, 0x18, 0x2f, 0xb5, 0x2c, 0xf8, 0xe3, 0x13, 0xb1, 0xd2, 0x05, 0xe3,
        0x01, 0x07, 0x36, 0x28, 0xf2, 0x03, 0xf8, 0xfc, 0xe4, 0x76, 0xf1, 0xfa, 0x7f, 0xf9, 0xc1,
        0xe1, 0x27, 0xa2, 0x82,
    ];
    pub const GOLDEN_RESULT: Q8RowBlockResult = Q8RowBlockResult {
        dot: -14901,
        term_q30: -9429888,
        row_q30: -9429888,
    };
    pub const GOLDEN_GATE_ROW0_ACTIVATIONS: [[u8; Q8_0_BLOCK_BYTES]; GATE_ROW0_BLOCKS] = [
        [
            0x30, 0x18, 0x0d, 0xa8, 0xd4, 0x4e, 0x1f, 0x49, 0x16, 0xb6, 0xb3, 0x3c, 0x25, 0xa8,
            0xe7, 0xf6, 0x25, 0x89, 0x4a, 0xd2, 0xcf, 0xe7, 0x21, 0xb0, 0xda, 0x81, 0x2a, 0x08,
            0x17, 0xd3, 0x56, 0xa7, 0x1d, 0x21,
        ],
        [
            0xd6, 0x18, 0x22, 0x22, 0xc4, 0x38, 0xfd, 0xb4, 0x12, 0x7f, 0xe7, 0x15, 0xeb, 0x2f,
            0x6c, 0x1c, 0x5d, 0xcb, 0xda, 0xdc, 0xcc, 0xe0, 0x1e, 0x0f, 0x31, 0x41, 0x76, 0x2e,
            0xf1, 0xd1, 0xa2, 0x0e, 0xc5, 0x2b,
        ],
        [
            0x53, 0x1d, 0x1d, 0x7f, 0x24, 0x36, 0x03, 0xdb, 0xf7, 0xe4, 0x19, 0x00, 0x01, 0xec,
            0x22, 0xf4, 0x00, 0xf3, 0x15, 0x02, 0x14, 0x00, 0x0f, 0xf1, 0x9e, 0xed, 0x0d, 0x0b,
            0xe7, 0xf0, 0x15, 0x00, 0x05, 0x16,
        ],
        [
            0xad, 0x19, 0x19, 0xff, 0xfd, 0xca, 0x22, 0x28, 0xe2, 0x06, 0xd0, 0x42, 0xe3, 0x22,
            0x1e, 0x00, 0xf1, 0xe7, 0x2a, 0xba, 0x5a, 0x00, 0x13, 0x18, 0xe0, 0xf1, 0x1c, 0xe9,
            0xf7, 0x29, 0xb8, 0xff, 0x7f, 0x09,
        ],
        [
            0x2f, 0x17, 0x17, 0xe2, 0x6e, 0xe9, 0x30, 0x29, 0xd2, 0x26, 0xce, 0x47, 0x68, 0x91,
            0xc7, 0x1c, 0xdf, 0x0c, 0xee, 0xa3, 0xd1, 0x09, 0x5c, 0x1d, 0xc6, 0xc4, 0xfc, 0xf3,
            0xce, 0x7f, 0xa7, 0x74, 0xd8, 0xe1,
        ],
        [
            0x1b, 0x18, 0x0c, 0x0d, 0x25, 0x33, 0x4c, 0x07, 0x2c, 0x04, 0xaf, 0xd3, 0x28, 0x26,
            0x0c, 0x3b, 0x1b, 0x15, 0xcc, 0x81, 0x20, 0x1d, 0xea, 0x0b, 0xc3, 0xa5, 0x44, 0x20,
            0x14, 0x07, 0x5a, 0xcd, 0x61, 0x57,
        ],
        [
            0x75, 0x1c, 0x00, 0xc9, 0x1d, 0xf8, 0x12, 0x0d, 0x54, 0xf9, 0xe0, 0xfa, 0x7f, 0xe8,
            0xc7, 0x11, 0x07, 0x3b, 0x11, 0x1a, 0xe9, 0xde, 0x26, 0xfe, 0x04, 0xfa, 0xdf, 0xdb,
            0xf3, 0xfa, 0xfa, 0xf0, 0x12, 0x2a,
        ],
        [
            0x45, 0x1f, 0x0e, 0x1b, 0xeb, 0x19, 0x08, 0xfa, 0xe9, 0x02, 0xf5, 0x0a, 0xf3, 0x17,
            0xf5, 0x20, 0xfe, 0xf5, 0x05, 0xfa, 0x1a, 0xf4, 0x38, 0x04, 0x18, 0x19, 0x03, 0x81,
            0xf7, 0x03, 0x07, 0x15, 0x2a, 0xf5,
        ],
        [
            0x93, 0x16, 0xb7, 0x99, 0xe4, 0xd5, 0x29, 0x8b, 0x59, 0xfa, 0xd4, 0x82, 0x52, 0xa0,
            0x13, 0x06, 0x73, 0xed, 0x61, 0xf0, 0x82, 0xbc, 0x38, 0x35, 0xe9, 0xf6, 0x09, 0xf0,
            0xe7, 0x81, 0xe3, 0xf1, 0x2b, 0x06,
        ],
        [
            0x26, 0x17, 0x09, 0x19, 0x3b, 0x06, 0x20, 0x02, 0x19, 0xe7, 0xd1, 0xff, 0xa5, 0xc6,
            0x83, 0x08, 0x2e, 0x49, 0x11, 0x26, 0x31, 0x1e, 0xf1, 0x41, 0xae, 0xc5, 0xed, 0xb4,
            0x05, 0xaa, 0x1d, 0x81, 0x27, 0x56,
        ],
        [
            0x0e, 0x18, 0x40, 0xf8, 0x2c, 0xfd, 0x4c, 0xcd, 0x17, 0x26, 0x19, 0xea, 0x46, 0xe2,
            0xbe, 0xe8, 0xe5, 0xd3, 0x1c, 0x81, 0x28, 0xdc, 0x78, 0x42, 0xc4, 0xf3, 0x15, 0x0a,
            0xe9, 0x02, 0xa7, 0x97, 0xd2, 0x22,
        ],
        [
            0xbe, 0x17, 0x19, 0x09, 0xdd, 0x2f, 0xe5, 0x42, 0xe0, 0xbd, 0x24, 0x13, 0xe3, 0xf6,
            0x38, 0x0a, 0xf5, 0x73, 0x4c, 0xdf, 0x70, 0x18, 0xd8, 0xcc, 0x7f, 0xf8, 0x27, 0x0f,
            0x12, 0x44, 0x75, 0x2b, 0x42, 0xfd,
        ],
        [
            0xc4, 0x25, 0x04, 0xfb, 0x06, 0xfe, 0xfb, 0x03, 0x05, 0x7f, 0x00, 0xf8, 0x0c, 0xfb,
            0xfb, 0x05, 0xfa, 0xf6, 0x03, 0x02, 0x02, 0x09, 0xfe, 0xfb, 0xf1, 0xfe, 0xf2, 0x04,
            0xff, 0xff, 0xfb, 0xfe, 0x01, 0x02,
        ],
        [
            0xf5, 0x1a, 0x15, 0x06, 0xfc, 0xf6, 0xfd, 0xc3, 0x0b, 0x1b, 0x0d, 0x22, 0x7f, 0x0e,
            0x02, 0xf3, 0x01, 0x09, 0xe3, 0x04, 0x01, 0x1e, 0x3d, 0x0c, 0xd5, 0xd2, 0xc1, 0x0d,
            0xf0, 0x2f, 0x06, 0xef, 0xf0, 0xea,
        ],
        [
            0xe0, 0x18, 0xff, 0xfc, 0xbd, 0x29, 0xcc, 0xfd, 0xcd, 0xe9, 0x9f, 0xb6, 0xe6, 0x1c,
            0xcf, 0x38, 0xe2, 0xd4, 0xfc, 0xe9, 0xd9, 0xf1, 0xcb, 0xdc, 0xe5, 0xe9, 0x0e, 0x7f,
            0x05, 0x04, 0xf2, 0xef, 0xe7, 0xed,
        ],
        [
            0x5f, 0x1c, 0x34, 0xef, 0x18, 0xf5, 0xe5, 0xfc, 0x12, 0xd2, 0xf7, 0x02, 0x07, 0xf4,
            0xdb, 0x0e, 0x0a, 0xff, 0x1b, 0xd1, 0x00, 0xe7, 0x31, 0xf5, 0xed, 0xe6, 0xf5, 0xf5,
            0x81, 0x01, 0x17, 0x16, 0x1b, 0x0e,
        ],
        [
            0x40, 0x18, 0xf6, 0xbc, 0x36, 0x41, 0x58, 0xf5, 0xf7, 0xb3, 0x85, 0x85, 0x19, 0x12,
            0xbd, 0xfa, 0x25, 0xf2, 0xec, 0xd9, 0xe6, 0xfd, 0xb9, 0xfe, 0xb9, 0x36, 0x2c, 0xc6,
            0x7a, 0xeb, 0x7f, 0xb1, 0xe7, 0x0b,
        ],
        [
            0xee, 0x17, 0x52, 0x34, 0x11, 0x24, 0xcf, 0x4a, 0x10, 0x0e, 0xc6, 0xc1, 0xa1, 0x15,
            0xeb, 0xf7, 0xce, 0x81, 0xa8, 0x00, 0xaf, 0xa2, 0xdf, 0xfb, 0x54, 0xc6, 0x0b, 0x23,
            0xdd, 0x12, 0xf0, 0x4d, 0xf3, 0x37,
        ],
        [
            0x3f, 0x17, 0xd3, 0x07, 0xa0, 0x06, 0xc7, 0xce, 0xf6, 0x25, 0x35, 0x34, 0xe4, 0x37,
            0x54, 0xe4, 0xdf, 0x0e, 0xba, 0x45, 0x81, 0x98, 0xa7, 0x49, 0xd4, 0x20, 0xba, 0x09,
            0xb6, 0xd8, 0x23, 0x57, 0xf5, 0xcf,
        ],
        [
            0x86, 0x1f, 0x03, 0xf0, 0xfa, 0x02, 0x17, 0x1e, 0x00, 0x03, 0x10, 0x0b, 0x14, 0x04,
            0x81, 0x1b, 0xf7, 0xff, 0x05, 0x01, 0xef, 0xde, 0xf6, 0x41, 0xfc, 0x0c, 0x0a, 0x12,
            0x03, 0x0b, 0x15, 0xfa, 0x18, 0x12,
        ],
        [
            0x55, 0x18, 0xfb, 0x3d, 0xef, 0x3a, 0x20, 0xfd, 0x81, 0x30, 0xf0, 0xf5, 0xee, 0xfc,
            0xed, 0xec, 0x46, 0x47, 0x64, 0xd2, 0xf0, 0xf3, 0xd5, 0xf5, 0x04, 0x00, 0xb8, 0xf7,
            0xee, 0x36, 0xfd, 0xea, 0x0a, 0x1b,
        ],
        [
            0x1f, 0x21, 0xec, 0x01, 0xf1, 0x81, 0x00, 0x09, 0x0e, 0x02, 0x01, 0xff, 0x09, 0xf1,
            0x07, 0xfc, 0xee, 0xfd, 0x05, 0x02, 0x0f, 0x0f, 0xf5, 0x01, 0xf2, 0xfd, 0xf2, 0xfd,
            0x01, 0x02, 0xfb, 0xfc, 0xeb, 0xf7,
        ],
        [
            0x2e, 0x18, 0x41, 0x81, 0x43, 0xde, 0x50, 0x7f, 0x22, 0x10, 0xd6, 0x0e, 0xd8, 0xef,
            0xed, 0x05, 0x78, 0x10, 0xea, 0xf7, 0x2a, 0xc4, 0x3c, 0xd2, 0xd5, 0x2b, 0x65, 0x31,
            0x16, 0xc1, 0x04, 0x00, 0xcb, 0xa2,
        ],
        [
            0x6b, 0x18, 0x01, 0xd6, 0xcb, 0x71, 0xde, 0x45, 0x0f, 0xc3, 0x3d, 0x09, 0xaf, 0x40,
            0xbd, 0x2f, 0xcd, 0x5c, 0xaf, 0xa4, 0x0d, 0x19, 0xed, 0xf1, 0xfd, 0xf4, 0x20, 0xef,
            0x0c, 0x81, 0x3d, 0x5a, 0xef, 0xfa,
        ],
        [
            0xe0, 0x1c, 0x07, 0x81, 0x03, 0xf0, 0xec, 0xed, 0x09, 0x0e, 0x2f, 0x02, 0x05, 0x06,
            0xf1, 0xf6, 0xef, 0x10, 0x03, 0x12, 0xf3, 0x20, 0xf2, 0xd1, 0xe9, 0xef, 0xe4, 0x18,
            0x03, 0x25, 0xdf, 0xf6, 0x28, 0x15,
        ],
        [
            0xfe, 0x16, 0x12, 0x95, 0x1c, 0x15, 0xcd, 0xa6, 0x68, 0xf2, 0xf9, 0x64, 0xa2, 0xbf,
            0x33, 0x53, 0x4c, 0x11, 0xbb, 0x3f, 0xe2, 0x81, 0x43, 0x90, 0xd2, 0xf6, 0xfb, 0xac,
            0x15, 0xb0, 0xfa, 0xe3, 0x9c, 0xf4,
        ],
        [
            0xd3, 0x16, 0x37, 0xe1, 0x10, 0xd4, 0x05, 0xdb, 0x19, 0xf4, 0x05, 0xe9, 0xae, 0x8d,
            0xae, 0xa2, 0x2c, 0x99, 0xb7, 0x5e, 0xc0, 0x6f, 0x81, 0xd4, 0xea, 0x03, 0x0a, 0xcc,
            0x11, 0x87, 0xad, 0x27, 0x40, 0xe7,
        ],
        [
            0x41, 0x18, 0xd8, 0x75, 0x0e, 0x1c, 0x7c, 0xe7, 0x17, 0x27, 0xf4, 0xfa, 0xdf, 0xe0,
            0x94, 0xe2, 0xd3, 0x47, 0x05, 0xb2, 0xce, 0xfa, 0xef, 0x23, 0xf0, 0x7f, 0xe6, 0x24,
            0x18, 0x0f, 0x38, 0x09, 0xcc, 0xf5,
        ],
        [
            0xb7, 0x19, 0x3d, 0x01, 0xac, 0xc1, 0x2a, 0xfe, 0x1c, 0x92, 0x3c, 0xf1, 0xf5, 0xd3,
            0x07, 0x57, 0x21, 0x2c, 0x7f, 0x2b, 0xc5, 0x45, 0xe6, 0x10, 0x0a, 0xf1, 0x2f, 0x42,
            0xdc, 0x32, 0x35, 0xee, 0x5d, 0x02,
        ],
        [
            0x07, 0x1c, 0xf3, 0x26, 0xd7, 0xfc, 0x0a, 0xed, 0x02, 0x33, 0x21, 0x01, 0x07, 0xfd,
            0xed, 0xe6, 0x14, 0x7f, 0x0f, 0xf6, 0xf7, 0x15, 0x2e, 0x27, 0x16, 0xff, 0xdc, 0xef,
            0xea, 0x16, 0xf3, 0x0c, 0xc8, 0x2a,
        ],
        [
            0xcd, 0x17, 0xd8, 0x02, 0x07, 0x2b, 0xdd, 0x3f, 0x2f, 0xce, 0x7f, 0x0f, 0x31, 0x03,
            0x01, 0x0f, 0x2b, 0x45, 0xfa, 0x45, 0xef, 0xf3, 0x21, 0xca, 0xba, 0xe1, 0xe5, 0x32,
            0xfd, 0x01, 0xbe, 0x28, 0x5f, 0xa6,
        ],
        [
            0xbb, 0x18, 0x1d, 0x7f, 0xc5, 0x1e, 0xa5, 0xfc, 0xe6, 0xe3, 0x13, 0x2c, 0xd0, 0xf4,
            0x63, 0xda, 0xee, 0x59, 0x14, 0x00, 0x76, 0x31, 0x32, 0xed, 0xce, 0xdf, 0x06, 0x08,
            0x3d, 0x32, 0xef, 0x23, 0xb9, 0xdb,
        ],
    ];
    pub const GOLDEN_GATE_ROW0_DOTS: [i32; GATE_ROW0_BLOCKS] = [
        -14901, -39888, -11363, -6182, -17665, 14298, 7752, 14516, -424, 11067, 12803, -3012, 5304,
        4915, 8088, 2717, -16089, 14286, 8008, -15976, -16800, -4852, 18470, 5181, -2349, 4074,
        25520, 1489, 11456, -9556, 18552, 9334,
    ];
    pub const GOLDEN_GATE_ROW0_TERMS_Q30: [i64; GATE_ROW0_BLOCKS] = [
        -9429888, -26836639, -12500626, -4561398, -10104268, 10888849, 7450039, 34453754, -145384,
        4924707, 8682309, -1539085, 29709320, 3945111, 4411119, 2692942, -10333663, 5395127,
        5001178, -30168804, -10270813, -16834213, 9920049, 3553594, -3392470, 2124000, 14128248,
        788591, 7688545, -12334538, 14879035, 7296481,
    ];
    pub const GOLDEN_GATE_ROW0_Q30: i64 = 29481209;
    pub const GOLDEN_GATE_ROW0_FP_Q30: i64 = 29481200;
    pub const GOLDEN_GATE_ROW0_FP_BOUND_Q30: i64 = 2148;
}

pub mod lfm25_ffn {
    use super::{
        AotCodecError, AotCompletionKind, AotFirmwareCapability, AotFixedShape, AotLane,
        AotLaneOwnership, AotOpDescriptor, AotScalarFormat, AotStateOwnership, AotTensorDescriptor,
        AotTransportKind, TruegaCustomOp,
    };

    pub const MODEL_LAYERS: u16 = 16;
    pub const ACTIVATION_BYTES: usize = 34 * 32;
    pub const ENCODED_INPUT_BYTES: usize = 2 + ACTIVATION_BYTES;
    pub const OUTPUT_ELEMENTS: usize = 1024;
    pub const OUTPUT_BYTES: usize = OUTPUT_ELEMENTS * 8;
    #[derive(Clone, Debug, Eq, PartialEq)]
    pub struct Input {
        pub layer: u16,
        pub activation: [u8; ACTIVATION_BYTES],
    }
    pub const CONTRACT_SHA256: [u8; 32] = [
        0x57, 0x4e, 0x5f, 0x70, 0xa0, 0x64, 0x83, 0xba, 0x5a, 0xaa, 0xd6, 0xd7, 0xa2, 0xec, 0x43,
        0xd4, 0x7a, 0xbb, 0xea, 0x40, 0x42, 0xb8, 0xb8, 0x40, 0x76, 0x79, 0x15, 0x5c, 0xa9, 0x0e,
        0x18, 0x27,
    ];
    pub const AOT_INPUTS: &[AotTensorDescriptor] = &[
        AotTensorDescriptor {
            name: "layer",
            scalar: AotScalarFormat::U16,
            shape: AotFixedShape::SCALAR,
            encoded_bytes: 2,
        },
        AotTensorDescriptor {
            name: "activation",
            scalar: AotScalarFormat::GgmlQ8_0,
            shape: AotFixedShape::vector(1024),
            encoded_bytes: ACTIVATION_BYTES as u32,
        },
    ];
    pub const AOT_OUTPUTS: &[AotTensorDescriptor] = &[AotTensorDescriptor {
        name: "down",
        scalar: AotScalarFormat::I64Q30,
        shape: AotFixedShape::vector(1024),
        encoded_bytes: OUTPUT_BYTES as u32,
    }];
    pub const AOT_DESCRIPTOR: AotOpDescriptor = AotOpDescriptor {
        name: "lfm25.ffn",
        contract_sha256: CONTRACT_SHA256,
        transport: AotTransportKind::FixedBar2RowStream,
        inputs: AOT_INPUTS,
        outputs: AOT_OUTPUTS,
        firmware: AotFirmwareCapability::RegisterMagic {
            bar: 0,
            offset: super::super::BAR0_LFM25_STREAM_CAPABILITY_OFFSET as u16,
            value: super::super::LFM25_STREAM_CAPABILITY_MAGIC,
        },
        lane: AotLane::Bar2Lfm25RowStream,
        lane_ownership: AotLaneOwnership::SingleWorkerExclusive,
        state_ownership: AotStateOwnership::HostRequestFpgaCompletion,
        completion: AotCompletionKind::MsiWorkerCallback,
    };
    pub enum AotOp {}
    impl TruegaCustomOp for AotOp {
        type Input = Input;
        type Output = [i64; OUTPUT_ELEMENTS];
        const DESCRIPTOR: AotOpDescriptor = AOT_DESCRIPTOR;
        fn encode(input: &Self::Input, destination: &mut [u8]) -> Result<usize, AotCodecError> {
            if input.layer >= MODEL_LAYERS {
                return Err(AotCodecError::InvalidEncoding);
            }
            let destination = destination
                .get_mut(..ENCODED_INPUT_BYTES)
                .ok_or(AotCodecError::BufferTooSmall)?;
            destination[..2].copy_from_slice(&input.layer.to_le_bytes());
            destination[2..].copy_from_slice(&input.activation);
            Ok(ENCODED_INPUT_BYTES)
        }
        fn decode(source: &[u8]) -> Result<Self::Output, AotCodecError> {
            if source.len() < OUTPUT_BYTES {
                return Err(AotCodecError::InvalidEncoding);
            }
            let mut output = [0i64; OUTPUT_ELEMENTS];
            let mut index = 0;
            while index < OUTPUT_ELEMENTS {
                let start = index * 8;
                output[index] = i64::from_le_bytes(
                    source[start..start + 8]
                        .try_into()
                        .map_err(|_| AotCodecError::InvalidEncoding)?,
                );
                index += 1;
            }
            Ok(output)
        }
    }
}

pub use lfm25_ffn_step as lfm25_q8_row_block;

pub fn binary_u32_args(a: u32, b: u32) -> [u8; 8] {
    add_u32::encode(a, b)
}

pub fn result_u32(bytes: &[u8]) -> Option<u32> {
    Some(u32::from_le_bytes(bytes.get(..4)?.try_into().ok()?))
}
