use std::env;
use std::fs;
use std::path::PathBuf;

#[derive(Clone, Copy)]
enum Op {
    AddU32,
}

struct Config {
    lanes: usize,
    op: Op,
    out: PathBuf,
}

fn main() {
    let cfg = parse_args().unwrap_or_else(|err| {
        eprintln!("{err}");
        eprintln!(
            "usage: tga-gen --lanes 64 --op add-u32 --out src/generated/tga_static_add64.vhd"
        );
        std::process::exit(2);
    });

    if cfg.lanes == 0 || cfg.lanes > 1024 {
        eprintln!("lane count must be 1..1024");
        std::process::exit(2);
    }

    let text = match cfg.op {
        Op::AddU32 => emit_add_u32(cfg.lanes),
    };

    if let Some(parent) = cfg.out.parent() {
        fs::create_dir_all(parent).expect("create output directory");
    }
    fs::write(&cfg.out, text).expect("write generated VHDL");
    println!("generated {}", cfg.out.display());
}

fn parse_args() -> Result<Config, String> {
    let mut lanes = None;
    let mut op = None;
    let mut out = None;
    let mut args = env::args().skip(1);

    while let Some(arg) = args.next() {
        match arg.as_str() {
            "--lanes" => {
                let value = args.next().ok_or("--lanes needs a value")?;
                lanes = Some(value.parse::<usize>().map_err(|_| "invalid --lanes")?);
            }
            "--op" => {
                let value = args.next().ok_or("--op needs a value")?;
                op = Some(match value.as_str() {
                    "add" | "add-u32" => Op::AddU32,
                    _ => return Err(format!("unknown op {value:?}")),
                });
            }
            "--out" => {
                out = Some(PathBuf::from(args.next().ok_or("--out needs a value")?));
            }
            "-h" | "--help" => return Err(String::new()),
            _ => return Err(format!("unknown argument {arg:?}")),
        }
    }

    Ok(Config {
        lanes: lanes.unwrap_or(64),
        op: op.unwrap_or(Op::AddU32),
        out: out.unwrap_or_else(|| PathBuf::from("src/generated/tga_static_add64.vhd")),
    })
}

fn emit_add_u32(lanes: usize) -> String {
    let bits = lanes * 32;
    let last_bit = bits - 1;
    let last_lane = lanes - 1;

    let mut vhdl = String::new();
    vhdl.push_str("-- Generated by tools/tga-gen. Do not hand-edit this datapath.\n");
    vhdl.push_str("-- Static machine: all lanes are real hardware, not spawned work.\n");
    vhdl.push_str("library IEEE;\n");
    vhdl.push_str("use IEEE.std_logic_1164.all;\n");
    vhdl.push_str("use IEEE.numeric_std.all;\n\n");
    vhdl.push_str("entity tga_static_add64 is\n");
    vhdl.push_str("\tport (\n");
    vhdl.push_str("\t\tclk          : in  std_logic;\n");
    vhdl.push_str("\t\trst          : in  std_logic;\n");
    vhdl.push_str("\t\tstart        : in  std_logic;\n");
    vhdl.push_str(&format!(
        "\t\ta_flat       : in  std_logic_vector({last_bit} downto 0);\n"
    ));
    vhdl.push_str(&format!(
        "\t\tb_flat       : in  std_logic_vector({last_bit} downto 0);\n"
    ));
    vhdl.push_str(&format!(
        "\t\tresult_flat  : out std_logic_vector({last_bit} downto 0);\n"
    ));
    vhdl.push_str("\t\tdone         : out std_logic;\n");
    vhdl.push_str("\t\tretire_count : out std_logic_vector(31 downto 0)\n");
    vhdl.push_str("\t);\n");
    vhdl.push_str("end entity;\n\n");
    vhdl.push_str("architecture rtl of tga_static_add64 is\n");
    vhdl.push_str(&format!(
        "\tsignal result_reg : std_logic_vector({last_bit} downto 0) := (others => '0');\n"
    ));
    vhdl.push_str("\tsignal done_reg : std_logic := '0';\n");
    vhdl.push_str("\tsignal retire_reg : unsigned(31 downto 0) := (others => '0');\n");
    vhdl.push_str("begin\n");
    vhdl.push_str("\tprocess(clk)\n");
    vhdl.push_str("\tbegin\n");
    vhdl.push_str("\t\tif rising_edge(clk) then\n");
    vhdl.push_str("\t\t\tif rst = '1' then\n");
    vhdl.push_str("\t\t\t\tresult_reg <= (others => '0');\n");
    vhdl.push_str("\t\t\t\tdone_reg <= '0';\n");
    vhdl.push_str("\t\t\t\tretire_reg <= (others => '0');\n");
    vhdl.push_str("\t\t\telse\n");
    vhdl.push_str("\t\t\t\tdone_reg <= '0';\n");
    vhdl.push_str("\t\t\t\tif start = '1' then\n");

    for lane in 0..lanes {
        let lo = lane * 32;
        let hi = lo + 31;
        vhdl.push_str(&format!(
            "\t\t\t\t\tresult_reg({hi} downto {lo}) <= std_logic_vector(unsigned(a_flat({hi} downto {lo})) + unsigned(b_flat({hi} downto {lo})));\n"
        ));
    }

    vhdl.push_str("\t\t\t\t\tdone_reg <= '1';\n");
    vhdl.push_str("\t\t\t\t\tretire_reg <= retire_reg + 1;\n");
    vhdl.push_str("\t\t\t\tend if;\n");
    vhdl.push_str("\t\t\tend if;\n");
    vhdl.push_str("\t\tend if;\n");
    vhdl.push_str("\tend process;\n\n");
    vhdl.push_str("\tresult_flat <= result_reg;\n");
    vhdl.push_str("\tdone <= done_reg;\n");
    vhdl.push_str("\tretire_count <= std_logic_vector(retire_reg);\n");
    vhdl.push_str("end architecture;\n");

    debug_assert_eq!(last_lane, 63);
    vhdl
}
