// @generated by tools/intel-gpu-bakery; DO NOT EDIT.
// source: crates/trueos-shader/gpgpu/kernels/ui4_rgba8_to_nv12_linear.cl
// frontend: ocloc OpenCL C frontend
// backend: Intel IGC through ocloc
// normalized commands: [["$OCLOC","compile","-file","$SOURCE_DIR/ui4_rgba8_to_nv12_linear.cl","-device","0x4680","-64","-output","ui4_rgba8_to_nv12_linear","-out_dir","$OUT_DIR","-output_no_suffix","-gen_file"],["$OCLOC","validate","-file","$OUT_DIR/ui4_rgba8_to_nv12_linear.bin"]]

pub(crate) const UI4_RGBA8_TO_NV12_LINEAR_ADLS_LEGACY_ABI_CONTRACT: GpgpuKernelAbiContract = GpgpuKernelAbiContract {
    schema_version: GPGPU_KERNEL_ABI_SCHEMA_VERSION,
    kernel_name: "ui4_rgba8_to_nv12_linear",
    target: GpgpuKernelTarget {
        label: "adls",
        pci_device_ids: &[0x4680],
        revision_min: 0,
        revision_max: 255,
    },
    ze_info_major: 1,
    ze_info_minor: 64,
    zebin_sha256: [
        0x30, 0xea, 0x39, 0x6f, 0xb6, 0xb9, 0x23, 0x87,
        0xc8, 0x15, 0x41, 0x26, 0x87, 0x3b, 0xa0, 0x0a,
        0x6d, 0x3a, 0x7a, 0xd8, 0x13, 0x16, 0x74, 0x53,
        0x70, 0x4c, 0x5c, 0x8f, 0x49, 0x30, 0x25, 0xac,
    ],
    spv_sha256: [
        0xef, 0xc7, 0x1f, 0xab, 0x05, 0x8f, 0xd3, 0xa4,
        0x6f, 0x84, 0xbc, 0xdd, 0x36, 0xfa, 0xcc, 0xe0,
        0x2b, 0xf3, 0x90, 0x49, 0xb9, 0x25, 0x64, 0x79,
        0x81, 0xba, 0x05, 0xf9, 0x50, 0x12, 0xa7, 0xa8,
    ],
    text_section_name: ".text.ui4_rgba8_to_nv12_linear",
    text_section_offset: 64,
    text_section_size: 3008,
    entry_offset: 64,
    entry_size: 2880,
    simd_width: 16,
    grf_count: 128,
    scratch_bytes: 0,
    slm_bytes: 0,
    cross_thread_data_bytes: 96,
    per_thread_data_bytes: 96,
    bindings: &[
        GpgpuArtifactBinding { arg_index: 0, bti: 0 },
        GpgpuArtifactBinding { arg_index: 1, bti: 1 },
    ],
    implicit_payload_args: &[
        GpgpuArtifactImplicitPayloadArg { kind: GpgpuArtifactImplicitArgKind::GlobalIdOffset, offset_bytes: 0, size_bytes: 12 },
        GpgpuArtifactImplicitPayloadArg { kind: GpgpuArtifactImplicitArgKind::LocalSize, offset_bytes: 12, size_bytes: 12 },
        GpgpuArtifactImplicitPayloadArg { kind: GpgpuArtifactImplicitArgKind::EnqueuedLocalSize, offset_bytes: 32, size_bytes: 12 },
    ],
    per_thread_payload_args: &[
        GpgpuArtifactPerThreadPayloadArg { kind: GpgpuArtifactPerThreadArgKind::LocalId, offset_bytes: 0, size_bytes: 96 },
    ],
    payload_args: &[
        GpgpuArtifactPayloadArg { arg_index: 0, kind: GpgpuArtifactArgKind::ByPointer, offset_bytes: 48, size_bytes: 8, access: GpgpuArtifactArgAccess::ReadOnly, address_mode: GpgpuArtifactAddressMode::Stateful },
        GpgpuArtifactPayloadArg { arg_index: 1, kind: GpgpuArtifactArgKind::ByPointer, offset_bytes: 56, size_bytes: 8, access: GpgpuArtifactArgAccess::ReadWrite, address_mode: GpgpuArtifactAddressMode::Stateful },
        GpgpuArtifactPayloadArg { arg_index: 2, kind: GpgpuArtifactArgKind::ByValue, offset_bytes: 64, size_bytes: 4, access: GpgpuArtifactArgAccess::None, address_mode: GpgpuArtifactAddressMode::None },
        GpgpuArtifactPayloadArg { arg_index: 3, kind: GpgpuArtifactArgKind::ByValue, offset_bytes: 68, size_bytes: 4, access: GpgpuArtifactArgAccess::None, address_mode: GpgpuArtifactAddressMode::None },
        GpgpuArtifactPayloadArg { arg_index: 4, kind: GpgpuArtifactArgKind::ByValue, offset_bytes: 72, size_bytes: 4, access: GpgpuArtifactArgAccess::None, address_mode: GpgpuArtifactAddressMode::None },
        GpgpuArtifactPayloadArg { arg_index: 5, kind: GpgpuArtifactArgKind::ByValue, offset_bytes: 76, size_bytes: 4, access: GpgpuArtifactArgAccess::None, address_mode: GpgpuArtifactAddressMode::None },
        GpgpuArtifactPayloadArg { arg_index: 6, kind: GpgpuArtifactArgKind::ByValue, offset_bytes: 80, size_bytes: 4, access: GpgpuArtifactArgAccess::None, address_mode: GpgpuArtifactAddressMode::None },
        GpgpuArtifactPayloadArg { arg_index: 7, kind: GpgpuArtifactArgKind::ByValue, offset_bytes: 84, size_bytes: 4, access: GpgpuArtifactArgAccess::None, address_mode: GpgpuArtifactAddressMode::None },
        GpgpuArtifactPayloadArg { arg_index: 8, kind: GpgpuArtifactArgKind::ByValue, offset_bytes: 88, size_bytes: 4, access: GpgpuArtifactArgAccess::None, address_mode: GpgpuArtifactAddressMode::None },
        GpgpuArtifactPayloadArg { arg_index: 9, kind: GpgpuArtifactArgKind::ByValue, offset_bytes: 92, size_bytes: 4, access: GpgpuArtifactArgAccess::None, address_mode: GpgpuArtifactAddressMode::None },
    ],
};
