[build]
target-dir = "tgt"
target = ".cargo/x86_64-unknown-trueos.json"

[unstable]
build-std = ["core", "compiler_builtins", "alloc", "panic_abort"]
build-std-features = ["compiler-builtins-mem"]
json-target-spec = true

[target.'.cargo/x86_64-unknown-trueos.json']
linker = "rust-lld"
rustflags = [
	"--cfg", "getrandom_backend=\"custom\"",
	"-L", "native=bld/empty-libs",
	"-C", "link-arg=-Tlinker.ld",
	"-C", "force-frame-pointers=yes"
]

[target.'cfg(target_os = "none")']
rustflags = [
	"--cfg", "getrandom_backend=\"custom\"",
	"-C", "link-arg=-Tlinker.ld",
	"-C", "force-frame-pointers=yes"
]

[target.'cfg(target_os = "trueos")']
rustflags = [
	"--cfg", "getrandom_backend=\"custom\"",
	"-L", "native=bld/empty-libs",
	"-C", "link-arg=-Tlinker.ld",
	"-C", "force-frame-pointers=yes"
]

[target.'cfg(target_os = "zkvm")']
rustflags = [
	"--cfg", "getrandom_backend=\"custom\"",
	"-C", "link-arg=-Tlinker.ld",
	"-C", "force-frame-pointers=yes"
]

[env]
# smoltcp generates config.rs at build time. The non-test default for
# IFACE_MAX_ADDR_COUNT is 2, which is not enough for (v6 ll + v6 global + v4).
SMOLTCP_IFACE_MAX_ADDR_COUNT = "4"
