-d C:\Repos\TGA\TangMega-138KPro-example\pcie_dma_demo\pcie_gen3(8G)\impl\gwsynthesis\pcie_dma_demo.vg
-p GW5AST-138B-PBGA484A-1
-pn GW5AST-LV138PG484AC1/I0
-cst C:\Repos\TGA\TangMega-138KPro-example\pcie_dma_demo\pcie_gen3(8G)\src\Pins.cst
-cfg C:\Repos\TGA\TangMega-138KPro-example\pcie_dma_demo\pcie_gen3(8G)\impl\pnr\device.cfg
-sdc C:\Repos\TGA\TangMega-138KPro-example\pcie_dma_demo\pcie_gen3(8G)\src\pcie_dma_demo.sdc
-bit
-tr
-ph
-timing
-ireg_not_in_iob
-oreg_not_in_iob
-ioreg_not_in_iob
-cst_error
-convert_sdp32_36_to_sdp16_18
-place_option 2
-route_option 1
-clock_route_order 1
-correct_hold 1
-route_maxfan 23
-global_freq 100.000
-enable_dsrm 0
