use std::env;
use std::fs::OpenOptions;
use std::io::{self, Write};
use std::net::SocketAddr;
use std::path::PathBuf;
use std::sync::Arc;
use std::time::Duration;

use remoteai::{ChatBackend, CopilotBackend, ServerConfig, app};
use tokio::net::TcpListener;
use tracing_subscriber::EnvFilter;

#[tokio::main]
async fn main() -> Result<(), Box<dyn std::error::Error>> {
    tracing_subscriber::fmt()
        .with_env_filter(
            EnvFilter::try_from_default_env().unwrap_or_else(|_| EnvFilter::new("remoteai=info")),
        )
        .with_target(false)
        .init();

    let mut args = env::args();
    let binary = args.next().unwrap_or_else(|| "remoteai".to_string());
    match (args.next().as_deref(), args.next()) {
        (Some("serve"), None) => serve().await,
        (Some("login"), None) => login().await,
        (Some("init"), None) => init(),
        _ => {
            eprintln!("usage: {binary} <serve|login|init>");
            std::process::exit(2);
        }
    }
}

fn init() -> Result<(), Box<dyn std::error::Error>> {
    let bind: SocketAddr = env_value("REMOTEAI_BIND", "127.0.0.1:3042").parse()?;
    let path = env::var_os("REMOTEAI_ENV_FILE")
        .map(PathBuf::from)
        .unwrap_or_else(default_env_file);
    let parent = path
        .parent()
        .ok_or("REMOTEAI_ENV_FILE must have a parent directory")?;
    prepare_private_config_directory(parent)?;

    let mut random = [0u8; 32];
    getrandom::fill(&mut random)?;
    let secret = hex(&random);
    let contents = format!(
        concat!(
            "# Generated by `remoteai init`; keep this file mode 0600.\n",
            "REMOTEAI_BIND={}\n",
            "REMOTEAI_BEARER_TOKEN={}\n",
            "REMOTEAI_MODEL=auto\n",
            "REMOTEAI_REQUEST_TIMEOUT_SECONDS=24\n",
            "# Optional fine-grained PAT with the Copilot Requests permission:\n",
            "# COPILOT_GITHUB_TOKEN=github_pat_replace_on_host_only\n"
        ),
        bind, secret
    );

    #[cfg(unix)]
    let mut file = {
        use std::os::unix::fs::OpenOptionsExt;
        OpenOptions::new()
            .write(true)
            .create_new(true)
            .mode(0o600)
            .open(&path)?
    };
    #[cfg(not(unix))]
    let mut file = OpenOptions::new()
        .write(true)
        .create_new(true)
        .open(&path)?;
    file.write_all(contents.as_bytes())?;
    file.sync_all()?;
    println!("remoteAI: created {} (secret not printed)", path.display());
    Ok(())
}

async fn login() -> Result<(), Box<dyn std::error::Error>> {
    let copilot_home = env::var_os("REMOTEAI_COPILOT_HOME")
        .map(PathBuf::from)
        .unwrap_or_else(default_copilot_home);
    std::fs::create_dir_all(&copilot_home)?;
    let cli = github_copilot_sdk::install_bundled_cli()
        .ok_or("the bundled Copilot CLI is unavailable in this build")?;
    let status = tokio::process::Command::new(cli)
        .arg("login")
        .env("COPILOT_HOME", copilot_home)
        .env("COPILOT_DISABLE_KEYTAR", "1")
        .status()
        .await?;
    if !status.success() {
        return Err(format!("Copilot login exited with {status}").into());
    }
    Ok(())
}

async fn serve() -> Result<(), Box<dyn std::error::Error>> {
    let bind: SocketAddr = env_value("REMOTEAI_BIND", "127.0.0.1:3042").parse()?;
    let bearer_token = required_env("REMOTEAI_BEARER_TOKEN")?;
    let model = env_value("REMOTEAI_MODEL", "auto");
    let timeout_seconds: u64 = env_value("REMOTEAI_REQUEST_TIMEOUT_SECONDS", "24").parse()?;
    if !(5..=25).contains(&timeout_seconds) {
        return Err("REMOTEAI_REQUEST_TIMEOUT_SECONDS must be between 5 and 25".into());
    }
    let copilot_home = env::var_os("REMOTEAI_COPILOT_HOME")
        .map(PathBuf::from)
        .unwrap_or_else(default_copilot_home);
    let github_token = env::var("COPILOT_GITHUB_TOKEN")
        .ok()
        .filter(|token| !token.trim().is_empty());

    let backend = Arc::new(
        CopilotBackend::start(
            model.clone(),
            Duration::from_secs(timeout_seconds),
            copilot_home,
            github_token,
        )
        .await?,
    );
    let router = app(
        ServerConfig {
            bearer_token,
            advertised_model: model.clone(),
        },
        backend.clone(),
    )?;
    let listener = TcpListener::bind(bind).await?;
    let local_addr = listener.local_addr()?;
    tracing::info!(bind = %local_addr, model = %model, "remoteAI OpenAI-compatible facade ready");
    if !local_addr.ip().is_loopback() {
        tracing::warn!(
            "serving plaintext HTTP beyond loopback; use only on a trusted LAN with the bearer token"
        );
    }

    let serve_result = axum::serve(listener, router)
        .with_graceful_shutdown(shutdown_signal())
        .await;
    if let Err(error) = backend.shutdown().await {
        tracing::warn!(%error, "Copilot runtime did not shut down cleanly");
    }
    serve_result?;
    Ok(())
}

fn env_value(name: &str, fallback: &str) -> String {
    env::var(name)
        .ok()
        .filter(|value| !value.trim().is_empty())
        .unwrap_or_else(|| fallback.to_string())
}

fn required_env(name: &str) -> Result<String, Box<dyn std::error::Error>> {
    let value = env::var(name).map_err(|_| format!("{name} is required"))?;
    if value.trim().is_empty() {
        return Err(format!("{name} is empty").into());
    }
    Ok(value)
}

fn default_copilot_home() -> PathBuf {
    if let Some(state_home) = env::var_os("XDG_STATE_HOME") {
        return PathBuf::from(state_home).join("remoteai/copilot");
    }
    if let Some(user_home) = env::var_os("HOME") {
        return PathBuf::from(user_home).join(".local/state/remoteai/copilot");
    }
    env::temp_dir().join("remoteai-copilot")
}

fn default_env_file() -> PathBuf {
    if let Some(config_home) = env::var_os("XDG_CONFIG_HOME") {
        return PathBuf::from(config_home).join("remoteai/remoteai.env");
    }
    if let Some(user_home) = env::var_os("HOME") {
        return PathBuf::from(user_home).join(".config/remoteai/remoteai.env");
    }
    env::temp_dir().join("remoteai.env")
}

fn hex(bytes: &[u8]) -> String {
    const DIGITS: &[u8; 16] = b"0123456789abcdef";
    let mut out = String::with_capacity(bytes.len() * 2);
    for byte in bytes {
        out.push(DIGITS[(byte >> 4) as usize] as char);
        out.push(DIGITS[(byte & 0x0f) as usize] as char);
    }
    out
}

#[cfg(unix)]
fn prepare_private_config_directory(path: &std::path::Path) -> io::Result<()> {
    use std::os::unix::fs::PermissionsExt;

    match std::fs::symlink_metadata(path) {
        Ok(metadata) => {
            if metadata.file_type().is_symlink() || !metadata.is_dir() {
                return Err(io::Error::new(
                    io::ErrorKind::InvalidInput,
                    format!("config parent {} must be a real directory", path.display()),
                ));
            }
            if metadata.permissions().mode() & 0o077 != 0 {
                return Err(io::Error::new(
                    io::ErrorKind::PermissionDenied,
                    format!(
                        "existing config parent {} must already be private (mode 0700)",
                        path.display()
                    ),
                ));
            }
            Ok(())
        }
        Err(error) if error.kind() == io::ErrorKind::NotFound => {
            if let Some(ancestor) = path.parent() {
                std::fs::create_dir_all(ancestor)?;
            }
            match std::fs::create_dir(path) {
                Ok(()) => std::fs::set_permissions(path, std::fs::Permissions::from_mode(0o700)),
                Err(error) if error.kind() == io::ErrorKind::AlreadyExists => {
                    // Another initializer won the race. Validate it as an
                    // existing directory and never chmod an object we did not
                    // create ourselves.
                    prepare_private_config_directory(path)
                }
                Err(error) => Err(error),
            }
        }
        Err(error) => Err(error),
    }
}

#[cfg(not(unix))]
fn prepare_private_config_directory(path: &std::path::Path) -> io::Result<()> {
    match std::fs::symlink_metadata(path) {
        Ok(metadata) if metadata.is_dir() && !metadata.file_type().is_symlink() => Ok(()),
        Ok(_) => Err(io::Error::new(
            io::ErrorKind::InvalidInput,
            format!("config parent {} must be a real directory", path.display()),
        )),
        Err(error) if error.kind() == io::ErrorKind::NotFound => {
            if let Some(ancestor) = path.parent() {
                std::fs::create_dir_all(ancestor)?;
            }
            match std::fs::create_dir(path) {
                Ok(()) => Ok(()),
                Err(error) if error.kind() == io::ErrorKind::AlreadyExists => {
                    prepare_private_config_directory(path)
                }
                Err(error) => Err(error),
            }
        }
        Err(error) => Err(error),
    }
}

async fn shutdown_signal() {
    #[cfg(unix)]
    {
        let mut terminate =
            tokio::signal::unix::signal(tokio::signal::unix::SignalKind::terminate())
                .expect("install SIGTERM handler");
        tokio::select! {
            _ = tokio::signal::ctrl_c() => {}
            _ = terminate.recv() => {}
        }
    }
    #[cfg(not(unix))]
    {
        let _ = tokio::signal::ctrl_c().await;
    }
    tracing::info!("shutdown requested");
}

#[cfg(test)]
mod tests {
    use std::sync::atomic::{AtomicU64, Ordering};

    use super::*;

    static TEST_SEQUENCE: AtomicU64 = AtomicU64::new(1);

    struct TestDirectory(PathBuf);

    impl TestDirectory {
        fn new() -> Self {
            let sequence = TEST_SEQUENCE.fetch_add(1, Ordering::Relaxed);
            let path = env::temp_dir()
                .join(format!("remoteai-init-test-{}-{sequence}", std::process::id()));
            std::fs::create_dir(&path).expect("create test directory");
            Self(path)
        }
    }

    impl Drop for TestDirectory {
        fn drop(&mut self) {
            let _ = std::fs::remove_dir_all(&self.0);
        }
    }

    #[cfg(unix)]
    fn mode(path: &std::path::Path) -> u32 {
        use std::os::unix::fs::PermissionsExt;

        std::fs::metadata(path).unwrap().permissions().mode() & 0o777
    }

    #[cfg(unix)]
    #[test]
    fn init_creates_only_the_dedicated_private_directory() {
        let root = TestDirectory::new();
        let private = root.0.join("remoteai");

        prepare_private_config_directory(&private).unwrap();

        assert_eq!(mode(&private), 0o700);
    }

    #[cfg(unix)]
    #[test]
    fn init_rejects_existing_public_parent_without_chmodding_it() {
        use std::os::unix::fs::PermissionsExt;

        let root = TestDirectory::new();
        let public = root.0.join("shared");
        std::fs::create_dir(&public).unwrap();
        std::fs::set_permissions(&public, std::fs::Permissions::from_mode(0o755)).unwrap();

        let error = prepare_private_config_directory(&public).unwrap_err();

        assert_eq!(error.kind(), io::ErrorKind::PermissionDenied);
        assert_eq!(mode(&public), 0o755);
    }

    #[cfg(unix)]
    #[test]
    fn init_accepts_an_existing_private_parent() {
        use std::os::unix::fs::PermissionsExt;

        let root = TestDirectory::new();
        let private = root.0.join("remoteai");
        std::fs::create_dir(&private).unwrap();
        std::fs::set_permissions(&private, std::fs::Permissions::from_mode(0o700)).unwrap();

        prepare_private_config_directory(&private).unwrap();

        assert_eq!(mode(&private), 0o700);
    }
}
