use std::env;
use std::fs;
use std::path::{Path, PathBuf};
use std::process::Command;

fn run(cmd: &mut Command) {
    let status = cmd.status().unwrap_or_else(|e| panic!("spawn {:?} failed: {e}", cmd));
    if !status.success() {
        panic!("command {:?} failed with status {status}", cmd);
    }
}

fn ensure_pciids_checkout(out_dir: &Path) -> PathBuf {
    // User override: point directly at a pciids source tree.
    if let Ok(p) = env::var("TRUEOS_PCIDS_DIR") {
        return PathBuf::from(p);
    }

    // Dev convenience: if the workspace has a top-level pciids/ checkout, use it.
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR"));
    let workspace_pciids = manifest_dir.join("..").join("..").join("pciids");
    if workspace_pciids.join("pci.ids").is_file() {
        return workspace_pciids;
    }

    let repo = env::var("TRUEOS_PCIDS_REPO")
        .unwrap_or_else(|_| "https://github.com/pciutils/pciids".to_string());
    let reference = env::var("TRUEOS_PCIDS_REF").unwrap_or_else(|_| "master".to_string());

    if env::var_os("CARGO_NET_OFFLINE").is_some() {
        panic!(
            "pci.ids not found in workspace and CARGO_NET_OFFLINE is set. \
Set TRUEOS_PCIDS_DIR=/path/to/pciids or run with network access."
        );
    }

    let checkout_dir = out_dir.join("pciids-src");
    if checkout_dir.join("pci.ids").is_file() {
        return checkout_dir;
    }

    fs::create_dir_all(out_dir).expect("create OUT_DIR");
    if checkout_dir.exists() {
        let _ = fs::remove_dir_all(&checkout_dir);
    }

    run(
        Command::new("git")
            .arg("clone")
            .arg("--depth")
            .arg("1")
            .arg("--branch")
            .arg(&reference)
            .arg(&repo)
            .arg(&checkout_dir),
    );

    if !checkout_dir.join("pci.ids").is_file() {
        panic!(
            "Fetched pciids but did not find pci.ids at {}",
            checkout_dir.display()
        );
    }

    checkout_dir
}

fn main() {
    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR"));

    println!("cargo:rerun-if-env-changed=TRUEOS_PCIDS_DIR");
    println!("cargo:rerun-if-env-changed=TRUEOS_PCIDS_REPO");
    println!("cargo:rerun-if-env-changed=TRUEOS_PCIDS_REF");
    println!("cargo:rerun-if-env-changed=CARGO_NET_OFFLINE");

    let pciids_dir = ensure_pciids_checkout(&out_dir);
    let src = pciids_dir.join("pci.ids");
    println!("cargo:rerun-if-changed={}", src.display());

    let dst = out_dir.join("pci.ids");
    fs::copy(&src, &dst).unwrap_or_else(|e| {
        panic!(
            "copy pci.ids from {} to {} failed: {e}",
            src.display(),
            dst.display()
        )
    });

    let generated_rs = out_dir.join("pciids_data.rs");
    let contents = r#"// @generated by build.rs
pub static PCI_IDS: &[u8] = include_bytes!(concat!(env!("OUT_DIR"), "/pci.ids"));
"#;
    fs::write(&generated_rs, contents).expect("write pciids_data.rs");
    println!("cargo:rerun-if-changed=build.rs");
}
