// @generated by tools/intel-gpu-bakery; DO NOT EDIT.
// source: crates/trueos-shader/gpgpu/kernels/alpha_blend_worklist_rgba8.clcpp
// frontend: Clang C++ for OpenCL -> LLVM bitcode -> llvm-spirv
// backend: Intel IGC through ocloc -spirv_input
// normalized commands: [["$CLANG","--target=spir64","-x","clcpp","-cl-std=CLC++","-Wall","-Wextra","-Werror","-Wdate-time","-cl-kernel-arg-info","-fno-discard-value-names","-fno-exceptions","-fno-rtti","-MMD","-MF","$OUT_DIR/alpha_blend_worklist_rgba8.d","-MT","alpha_blend_worklist_rgba8.bc","-emit-llvm","-c","alpha_blend_worklist_rgba8.clcpp","-o","$OUT_DIR/alpha_blend_worklist_rgba8.bc"],["$LLVM_SPIRV","--preserve-ocl-kernel-arg-type-metadata-through-string","$OUT_DIR/alpha_blend_worklist_rgba8.bc","-o","$OUT_DIR/alpha_blend_worklist_rgba8.spv"],["$OCLOC","compile","-file","$OUT_DIR/alpha_blend_worklist_rgba8.spv","-spirv_input","-device","0x4680","-64","-output","alpha_blend_worklist_rgba8","-out_dir","$OUT_DIR","-output_no_suffix","-gen_file"],["$OCLOC","validate","-file","$OUT_DIR/alpha_blend_worklist_rgba8.bin"]]

pub(crate) const ALPHA_BLEND_WORKLIST_RGBA8_ADLS_CPP_ABI_CONTRACT: GpgpuKernelAbiContract = GpgpuKernelAbiContract {
    schema_version: GPGPU_KERNEL_ABI_SCHEMA_VERSION,
    kernel_name: "alpha_blend_worklist_rgba8",
    target: GpgpuKernelTarget {
        label: "adls",
        pci_device_ids: &[0x4680],
        revision_min: 12,
        revision_max: 12,
    },
    ze_info_major: 1,
    ze_info_minor: 62,
    zebin_sha256: [
        0x86, 0x04, 0x24, 0x36, 0x20, 0x19, 0xfd, 0x36,
        0xf3, 0x20, 0x32, 0x0c, 0x78, 0x75, 0xcc, 0xc7,
        0x5b, 0x85, 0x21, 0x33, 0x94, 0x50, 0xc7, 0x29,
        0x39, 0x5e, 0x25, 0xec, 0xff, 0x82, 0xdd, 0xa6,
    ],
    spv_sha256: [
        0x29, 0xb7, 0x3b, 0xd6, 0xdc, 0x61, 0x33, 0xdd,
        0x04, 0x0e, 0x5a, 0xb4, 0xee, 0x75, 0x60, 0xc8,
        0x38, 0xdc, 0xba, 0x44, 0x9d, 0x93, 0x45, 0x0b,
        0xd0, 0x82, 0xb8, 0x1b, 0x92, 0xb9, 0xab, 0x76,
    ],
    text_section_name: ".text.alpha_blend_worklist_rgba8",
    text_section_offset: 64,
    text_section_size: 5888,
    entry_offset: 64,
    entry_size: 5752,
    simd_width: 16,
    grf_count: 128,
    scratch_bytes: 0,
    slm_bytes: 0,
    cross_thread_data_bytes: 96,
    per_thread_data_bytes: 96,
    bindings: &[
        GpgpuArtifactBinding { arg_index: 0, bti: 0 },
        GpgpuArtifactBinding { arg_index: 1, bti: 1 },
        GpgpuArtifactBinding { arg_index: 2, bti: 2 },
    ],
    implicit_payload_args: &[
        GpgpuArtifactImplicitPayloadArg { kind: GpgpuArtifactImplicitArgKind::GlobalIdOffset, offset_bytes: 0, size_bytes: 12 },
        GpgpuArtifactImplicitPayloadArg { kind: GpgpuArtifactImplicitArgKind::LocalSize, offset_bytes: 12, size_bytes: 12 },
    ],
    per_thread_payload_args: &[
        GpgpuArtifactPerThreadPayloadArg { kind: GpgpuArtifactPerThreadArgKind::LocalId, offset_bytes: 0, size_bytes: 96 },
    ],
    payload_args: &[
        GpgpuArtifactPayloadArg { arg_index: 0, kind: GpgpuArtifactArgKind::ByPointer, offset_bytes: 32, size_bytes: 8, access: GpgpuArtifactArgAccess::ReadOnly, address_mode: GpgpuArtifactAddressMode::Stateful },
        GpgpuArtifactPayloadArg { arg_index: 1, kind: GpgpuArtifactArgKind::ByPointer, offset_bytes: 40, size_bytes: 8, access: GpgpuArtifactArgAccess::ReadWrite, address_mode: GpgpuArtifactAddressMode::Stateful },
        GpgpuArtifactPayloadArg { arg_index: 2, kind: GpgpuArtifactArgKind::ByPointer, offset_bytes: 48, size_bytes: 8, access: GpgpuArtifactArgAccess::ReadOnly, address_mode: GpgpuArtifactAddressMode::Stateful },
        GpgpuArtifactPayloadArg { arg_index: 3, kind: GpgpuArtifactArgKind::ByValue, offset_bytes: 56, size_bytes: 4, access: GpgpuArtifactArgAccess::None, address_mode: GpgpuArtifactAddressMode::None },
        GpgpuArtifactPayloadArg { arg_index: 4, kind: GpgpuArtifactArgKind::ByValue, offset_bytes: 60, size_bytes: 4, access: GpgpuArtifactArgAccess::None, address_mode: GpgpuArtifactAddressMode::None },
        GpgpuArtifactPayloadArg { arg_index: 5, kind: GpgpuArtifactArgKind::ByValue, offset_bytes: 64, size_bytes: 4, access: GpgpuArtifactArgAccess::None, address_mode: GpgpuArtifactAddressMode::None },
        GpgpuArtifactPayloadArg { arg_index: 6, kind: GpgpuArtifactArgKind::ByValue, offset_bytes: 68, size_bytes: 4, access: GpgpuArtifactArgAccess::None, address_mode: GpgpuArtifactAddressMode::None },
    ],
};
