// @generated by tools/intel-gpu-bakery; DO NOT EDIT.
// source: crates/trueos-shader/gpgpu/kernels/copy_rect_rgba8.clcpp
// frontend: Clang C++ for OpenCL -> LLVM bitcode -> llvm-spirv
// backend: Intel IGC through ocloc -spirv_input
// normalized commands: [["$CLANG","--target=spir64","-x","clcpp","-cl-std=CLC++","-Wall","-Wextra","-Werror","-Wdate-time","-cl-kernel-arg-info","-fno-discard-value-names","-fno-exceptions","-fno-rtti","-MMD","-MF","$OUT_DIR/copy_rect_rgba8.d","-MT","copy_rect_rgba8.bc","-emit-llvm","-c","copy_rect_rgba8.clcpp","-o","$OUT_DIR/copy_rect_rgba8.bc"],["$LLVM_SPIRV","--preserve-ocl-kernel-arg-type-metadata-through-string","$OUT_DIR/copy_rect_rgba8.bc","-o","$OUT_DIR/copy_rect_rgba8.spv"],["$OCLOC","compile","-file","$OUT_DIR/copy_rect_rgba8.spv","-spirv_input","-device","0x4680","-64","-output","copy_rect_rgba8","-out_dir","$OUT_DIR","-output_no_suffix","-gen_file"],["$OCLOC","validate","-file","$OUT_DIR/copy_rect_rgba8.bin"]]

pub(crate) const COPY_RECT_RGBA8_ADLS_CPP_ABI_CONTRACT: GpgpuKernelAbiContract =
    GpgpuKernelAbiContract {
        schema_version: GPGPU_KERNEL_ABI_SCHEMA_VERSION,
        kernel_name: "copy_rect_rgba8",
        target: GpgpuKernelTarget {
            label: "adls",
            pci_device_ids: &[0x4680],
            revision_min: 12,
            revision_max: 12,
        },
        ze_info_major: 1,
        ze_info_minor: 62,
        zebin_sha256: [
            0x5a, 0x27, 0x1e, 0xe6, 0xc3, 0x8b, 0xbf, 0x7d, 0x9d, 0x95, 0x75, 0x29, 0x24, 0xd3,
            0xcc, 0x32, 0x6a, 0x5e, 0xd4, 0x2e, 0x65, 0x93, 0xbc, 0x88, 0x99, 0x0f, 0x57, 0x08,
            0xba, 0x6a, 0x87, 0xc1,
        ],
        spv_sha256: [
            0x66, 0x8b, 0xe1, 0xd0, 0xbb, 0x57, 0xcb, 0x84, 0xb0, 0x0b, 0xeb, 0x7b, 0xc5, 0x4d,
            0xc6, 0x3d, 0x3d, 0x11, 0xf5, 0x9f, 0x6a, 0xa7, 0x92, 0xc5, 0x4b, 0x32, 0x6a, 0xfe,
            0xab, 0x66, 0x22, 0x8a,
        ],
        text_section_name: ".text.copy_rect_rgba8",
        text_section_offset: 64,
        text_section_size: 896,
        entry_offset: 64,
        entry_size: 712,
        simd_width: 16,
        grf_count: 128,
        scratch_bytes: 0,
        slm_bytes: 0,
        cross_thread_data_bytes: 96,
        per_thread_data_bytes: 96,
        bindings: &[
            GpgpuArtifactBinding {
                arg_index: 0,
                bti: 0,
            },
            GpgpuArtifactBinding {
                arg_index: 1,
                bti: 1,
            },
        ],
        implicit_payload_args: &[
            GpgpuArtifactImplicitPayloadArg {
                kind: GpgpuArtifactImplicitArgKind::GlobalIdOffset,
                offset_bytes: 0,
                size_bytes: 12,
            },
            GpgpuArtifactImplicitPayloadArg {
                kind: GpgpuArtifactImplicitArgKind::LocalSize,
                offset_bytes: 12,
                size_bytes: 12,
            },
            GpgpuArtifactImplicitPayloadArg {
                kind: GpgpuArtifactImplicitArgKind::EnqueuedLocalSize,
                offset_bytes: 32,
                size_bytes: 12,
            },
        ],
        per_thread_payload_args: &[GpgpuArtifactPerThreadPayloadArg {
            kind: GpgpuArtifactPerThreadArgKind::LocalId,
            offset_bytes: 0,
            size_bytes: 96,
        }],
        payload_args: &[
            GpgpuArtifactPayloadArg {
                arg_index: 0,
                kind: GpgpuArtifactArgKind::ByPointer,
                offset_bytes: 48,
                size_bytes: 8,
                access: GpgpuArtifactArgAccess::ReadOnly,
                address_mode: GpgpuArtifactAddressMode::Stateful,
            },
            GpgpuArtifactPayloadArg {
                arg_index: 1,
                kind: GpgpuArtifactArgKind::ByPointer,
                offset_bytes: 56,
                size_bytes: 8,
                access: GpgpuArtifactArgAccess::ReadWrite,
                address_mode: GpgpuArtifactAddressMode::Stateful,
            },
            GpgpuArtifactPayloadArg {
                arg_index: 2,
                kind: GpgpuArtifactArgKind::ByValue,
                offset_bytes: 64,
                size_bytes: 4,
                access: GpgpuArtifactArgAccess::None,
                address_mode: GpgpuArtifactAddressMode::None,
            },
            GpgpuArtifactPayloadArg {
                arg_index: 3,
                kind: GpgpuArtifactArgKind::ByValue,
                offset_bytes: 68,
                size_bytes: 4,
                access: GpgpuArtifactArgAccess::None,
                address_mode: GpgpuArtifactAddressMode::None,
            },
            GpgpuArtifactPayloadArg {
                arg_index: 4,
                kind: GpgpuArtifactArgKind::ByValue,
                offset_bytes: 72,
                size_bytes: 4,
                access: GpgpuArtifactArgAccess::None,
                address_mode: GpgpuArtifactAddressMode::None,
            },
            GpgpuArtifactPayloadArg {
                arg_index: 5,
                kind: GpgpuArtifactArgKind::ByValue,
                offset_bytes: 76,
                size_bytes: 4,
                access: GpgpuArtifactArgAccess::None,
                address_mode: GpgpuArtifactAddressMode::None,
            },
            GpgpuArtifactPayloadArg {
                arg_index: 6,
                kind: GpgpuArtifactArgKind::ByValue,
                offset_bytes: 80,
                size_bytes: 4,
                access: GpgpuArtifactArgAccess::None,
                address_mode: GpgpuArtifactAddressMode::None,
            },
            GpgpuArtifactPayloadArg {
                arg_index: 7,
                kind: GpgpuArtifactArgKind::ByValue,
                offset_bytes: 84,
                size_bytes: 4,
                access: GpgpuArtifactArgAccess::None,
                address_mode: GpgpuArtifactAddressMode::None,
            },
            GpgpuArtifactPayloadArg {
                arg_index: 8,
                kind: GpgpuArtifactArgKind::ByValue,
                offset_bytes: 88,
                size_bytes: 4,
                access: GpgpuArtifactArgAccess::None,
                address_mode: GpgpuArtifactAddressMode::None,
            },
            GpgpuArtifactPayloadArg {
                arg_index: 9,
                kind: GpgpuArtifactArgKind::ByValue,
                offset_bytes: 92,
                size_bytes: 4,
                access: GpgpuArtifactArgAccess::None,
                address_mode: GpgpuArtifactAddressMode::None,
            },
        ],
    };
