// @generated by tools/intel-gpu-bakery; DO NOT EDIT.
// source: crates/trueos-shader/gpgpu/kernels/cpp_demo_rgba8.clcpp
// frontend: Clang C++ for OpenCL -> LLVM bitcode -> llvm-spirv
// backend: Intel IGC through ocloc -spirv_input
// normalized commands: [["$CLANG","--target=spir64","-x","clcpp","-cl-std=CLC++","-Wall","-Wextra","-Werror","-Wdate-time","-cl-kernel-arg-info","-fno-discard-value-names","-fno-exceptions","-fno-rtti","-MMD","-MF","$OUT_DIR/cpp_demo_rgba8.d","-MT","cpp_demo_rgba8.bc","-emit-llvm","-c","cpp_demo_rgba8.clcpp","-o","$OUT_DIR/cpp_demo_rgba8.bc"],["$LLVM_SPIRV","--preserve-ocl-kernel-arg-type-metadata-through-string","$OUT_DIR/cpp_demo_rgba8.bc","-o","$OUT_DIR/cpp_demo_rgba8.spv"],["$OCLOC","compile","-file","$OUT_DIR/cpp_demo_rgba8.spv","-spirv_input","-device","0x4680","-64","-output","cpp_demo_rgba8","-out_dir","$OUT_DIR","-output_no_suffix","-gen_file"],["$OCLOC","validate","-file","$OUT_DIR/cpp_demo_rgba8.bin"]]

pub(crate) const CPP_DEMO_RGBA8_ADLS_CPP_ABI_CONTRACT: GpgpuKernelAbiContract = GpgpuKernelAbiContract {
    schema_version: GPGPU_KERNEL_ABI_SCHEMA_VERSION,
    kernel_name: "cpp_demo_rgba8",
    target: GpgpuKernelTarget {
        label: "adls",
        pci_device_ids: &[0x4680],
        revision_min: 12,
        revision_max: 12,
    },
    ze_info_major: 1,
    ze_info_minor: 62,
    zebin_sha256: [
        0x1b, 0xa4, 0xad, 0xb9, 0xf0, 0x27, 0x33, 0x80,
        0x2c, 0x4f, 0xe4, 0x1a, 0x97, 0x46, 0xff, 0xc3,
        0x49, 0xd9, 0x33, 0x08, 0x46, 0xaa, 0x51, 0xed,
        0x1e, 0x57, 0x4a, 0x28, 0x5e, 0xc6, 0x73, 0xd4,
    ],
    spv_sha256: [
        0xbe, 0x41, 0xfc, 0xca, 0xac, 0xa3, 0x9e, 0x0c,
        0x15, 0x84, 0xe5, 0x06, 0x2b, 0x54, 0x34, 0xa1,
        0x73, 0x66, 0x44, 0x1b, 0xc5, 0x86, 0xb2, 0x13,
        0x41, 0x35, 0xd3, 0x66, 0x47, 0x29, 0xb3, 0xd5,
    ],
    text_section_name: ".text.cpp_demo_rgba8",
    text_section_offset: 64,
    text_section_size: 44800,
    entry_offset: 64,
    entry_size: 44632,
    simd_width: 16,
    grf_count: 128,
    scratch_bytes: 0,
    slm_bytes: 0,
    cross_thread_data_bytes: 128,
    per_thread_data_bytes: 96,
    bindings: &[
        GpgpuArtifactBinding { arg_index: 0, bti: 0 },
    ],
    implicit_payload_args: &[
        GpgpuArtifactImplicitPayloadArg { kind: GpgpuArtifactImplicitArgKind::GlobalIdOffset, offset_bytes: 0, size_bytes: 12 },
        GpgpuArtifactImplicitPayloadArg { kind: GpgpuArtifactImplicitArgKind::LocalSize, offset_bytes: 12, size_bytes: 12 },
        GpgpuArtifactImplicitPayloadArg { kind: GpgpuArtifactImplicitArgKind::EnqueuedLocalSize, offset_bytes: 32, size_bytes: 12 },
    ],
    per_thread_payload_args: &[
        GpgpuArtifactPerThreadPayloadArg { kind: GpgpuArtifactPerThreadArgKind::LocalId, offset_bytes: 0, size_bytes: 96 },
    ],
    payload_args: &[
        GpgpuArtifactPayloadArg { arg_index: 0, kind: GpgpuArtifactArgKind::ByPointer, offset_bytes: 48, size_bytes: 8, access: GpgpuArtifactArgAccess::ReadWrite, address_mode: GpgpuArtifactAddressMode::Stateful },
        GpgpuArtifactPayloadArg { arg_index: 1, kind: GpgpuArtifactArgKind::ByValue, offset_bytes: 56, size_bytes: 4, access: GpgpuArtifactArgAccess::None, address_mode: GpgpuArtifactAddressMode::None },
        GpgpuArtifactPayloadArg { arg_index: 2, kind: GpgpuArtifactArgKind::ByValue, offset_bytes: 60, size_bytes: 4, access: GpgpuArtifactArgAccess::None, address_mode: GpgpuArtifactAddressMode::None },
        GpgpuArtifactPayloadArg { arg_index: 3, kind: GpgpuArtifactArgKind::ByValue, offset_bytes: 64, size_bytes: 4, access: GpgpuArtifactArgAccess::None, address_mode: GpgpuArtifactAddressMode::None },
        GpgpuArtifactPayloadArg { arg_index: 4, kind: GpgpuArtifactArgKind::ByValue, offset_bytes: 68, size_bytes: 4, access: GpgpuArtifactArgAccess::None, address_mode: GpgpuArtifactAddressMode::None },
        GpgpuArtifactPayloadArg { arg_index: 5, kind: GpgpuArtifactArgKind::ByValue, offset_bytes: 72, size_bytes: 4, access: GpgpuArtifactArgAccess::None, address_mode: GpgpuArtifactAddressMode::None },
        GpgpuArtifactPayloadArg { arg_index: 6, kind: GpgpuArtifactArgKind::ByValue, offset_bytes: 76, size_bytes: 4, access: GpgpuArtifactArgAccess::None, address_mode: GpgpuArtifactAddressMode::None },
        GpgpuArtifactPayloadArg { arg_index: 7, kind: GpgpuArtifactArgKind::ByValue, offset_bytes: 80, size_bytes: 4, access: GpgpuArtifactArgAccess::None, address_mode: GpgpuArtifactAddressMode::None },
        GpgpuArtifactPayloadArg { arg_index: 8, kind: GpgpuArtifactArgKind::ByValue, offset_bytes: 84, size_bytes: 4, access: GpgpuArtifactArgAccess::None, address_mode: GpgpuArtifactAddressMode::None },
        GpgpuArtifactPayloadArg { arg_index: 9, kind: GpgpuArtifactArgKind::ByValue, offset_bytes: 88, size_bytes: 4, access: GpgpuArtifactArgAccess::None, address_mode: GpgpuArtifactAddressMode::None },
        GpgpuArtifactPayloadArg { arg_index: 10, kind: GpgpuArtifactArgKind::ByValue, offset_bytes: 92, size_bytes: 4, access: GpgpuArtifactArgAccess::None, address_mode: GpgpuArtifactAddressMode::None },
        GpgpuArtifactPayloadArg { arg_index: 11, kind: GpgpuArtifactArgKind::ByValue, offset_bytes: 96, size_bytes: 4, access: GpgpuArtifactArgAccess::None, address_mode: GpgpuArtifactAddressMode::None },
    ],
};
