// @generated by tools/intel-gpu-bakery; DO NOT EDIT.
// source: crates/trueos-shader/gpgpu/kernels/font_instance_rgba8.clcpp
// frontend: Clang C++ for OpenCL -> LLVM bitcode -> llvm-spirv
// backend: Intel IGC through ocloc -spirv_input
// normalized commands: [["$CLANG","--target=spir64","-x","clcpp","-cl-std=CLC++","-Wall","-Wextra","-Werror","-Wdate-time","-cl-kernel-arg-info","-fno-discard-value-names","-fno-exceptions","-fno-rtti","-MMD","-MF","$OUT_DIR/font_instance_rgba8.d","-MT","font_instance_rgba8.bc","-emit-llvm","-c","font_instance_rgba8.clcpp","-o","$OUT_DIR/font_instance_rgba8.bc"],["$LLVM_SPIRV","--preserve-ocl-kernel-arg-type-metadata-through-string","$OUT_DIR/font_instance_rgba8.bc","-o","$OUT_DIR/font_instance_rgba8.spv"],["$OCLOC","compile","-file","$OUT_DIR/font_instance_rgba8.spv","-spirv_input","-device","0x4680","-64","-output","font_instance_rgba8","-out_dir","$OUT_DIR","-output_no_suffix","-gen_file"],["$OCLOC","validate","-file","$OUT_DIR/font_instance_rgba8.bin"]]

pub(crate) const FONT_INSTANCE_RGBA8_ADLS_CPP_ABI_CONTRACT: GpgpuKernelAbiContract = GpgpuKernelAbiContract {
    schema_version: GPGPU_KERNEL_ABI_SCHEMA_VERSION,
    kernel_name: "font_instance_rgba8",
    target: GpgpuKernelTarget {
        label: "adls",
        pci_device_ids: &[0x4680],
        revision_min: 12,
        revision_max: 12,
    },
    ze_info_major: 1,
    ze_info_minor: 64,
    zebin_sha256: [
        0x75, 0x76, 0x4d, 0x74, 0xe0, 0xc2, 0xe5, 0xbc,
        0x2b, 0xc6, 0x08, 0x4e, 0x4c, 0x67, 0x6a, 0x0e,
        0x1a, 0xb4, 0x2e, 0xc7, 0x6b, 0x5e, 0xf9, 0xae,
        0x5f, 0xd9, 0x61, 0xb9, 0x38, 0x01, 0xd3, 0x01,
    ],
    spv_sha256: [
        0xa1, 0x14, 0x85, 0xc5, 0x1b, 0x81, 0x7a, 0x67,
        0xc9, 0xe1, 0x52, 0xe9, 0x35, 0xf7, 0xf2, 0x33,
        0x23, 0x57, 0x8f, 0xc2, 0x89, 0x58, 0xd8, 0x48,
        0x65, 0x34, 0x37, 0x84, 0x31, 0x98, 0x9f, 0x95,
    ],
    text_section_name: ".text.font_instance_rgba8",
    text_section_offset: 64,
    text_section_size: 15616,
    entry_offset: 64,
    entry_size: 15432,
    simd_width: 16,
    grf_count: 128,
    scratch_bytes: 0,
    slm_bytes: 0,
    cross_thread_data_bytes: 128,
    per_thread_data_bytes: 96,
    bindings: &[
        GpgpuArtifactBinding { arg_index: 0, bti: 0 },
        GpgpuArtifactBinding { arg_index: 1, bti: 1 },
        GpgpuArtifactBinding { arg_index: 2, bti: 2 },
    ],
    implicit_payload_args: &[
        GpgpuArtifactImplicitPayloadArg { kind: GpgpuArtifactImplicitArgKind::GlobalIdOffset, offset_bytes: 0, size_bytes: 12 },
        GpgpuArtifactImplicitPayloadArg { kind: GpgpuArtifactImplicitArgKind::LocalSize, offset_bytes: 12, size_bytes: 12 },
        GpgpuArtifactImplicitPayloadArg { kind: GpgpuArtifactImplicitArgKind::EnqueuedLocalSize, offset_bytes: 32, size_bytes: 12 },
    ],
    per_thread_payload_args: &[
        GpgpuArtifactPerThreadPayloadArg { kind: GpgpuArtifactPerThreadArgKind::LocalId, offset_bytes: 0, size_bytes: 96 },
    ],
    payload_args: &[
        GpgpuArtifactPayloadArg { arg_index: 0, kind: GpgpuArtifactArgKind::ByPointer, offset_bytes: 48, size_bytes: 8, access: GpgpuArtifactArgAccess::ReadOnly, address_mode: GpgpuArtifactAddressMode::Stateful },
        GpgpuArtifactPayloadArg { arg_index: 1, kind: GpgpuArtifactArgKind::ByPointer, offset_bytes: 56, size_bytes: 8, access: GpgpuArtifactArgAccess::ReadWrite, address_mode: GpgpuArtifactAddressMode::Stateful },
        GpgpuArtifactPayloadArg { arg_index: 2, kind: GpgpuArtifactArgKind::ByPointer, offset_bytes: 64, size_bytes: 8, access: GpgpuArtifactArgAccess::ReadOnly, address_mode: GpgpuArtifactAddressMode::Stateless },
        GpgpuArtifactPayloadArg { arg_index: 3, kind: GpgpuArtifactArgKind::ByValue, offset_bytes: 72, size_bytes: 4, access: GpgpuArtifactArgAccess::None, address_mode: GpgpuArtifactAddressMode::None },
        GpgpuArtifactPayloadArg { arg_index: 4, kind: GpgpuArtifactArgKind::ByValue, offset_bytes: 76, size_bytes: 4, access: GpgpuArtifactArgAccess::None, address_mode: GpgpuArtifactAddressMode::None },
        GpgpuArtifactPayloadArg { arg_index: 5, kind: GpgpuArtifactArgKind::ByValue, offset_bytes: 80, size_bytes: 4, access: GpgpuArtifactArgAccess::None, address_mode: GpgpuArtifactAddressMode::None },
        GpgpuArtifactPayloadArg { arg_index: 6, kind: GpgpuArtifactArgKind::ByValue, offset_bytes: 84, size_bytes: 4, access: GpgpuArtifactArgAccess::None, address_mode: GpgpuArtifactAddressMode::None },
        GpgpuArtifactPayloadArg { arg_index: 7, kind: GpgpuArtifactArgKind::ByValue, offset_bytes: 88, size_bytes: 4, access: GpgpuArtifactArgAccess::None, address_mode: GpgpuArtifactAddressMode::None },
        GpgpuArtifactPayloadArg { arg_index: 8, kind: GpgpuArtifactArgKind::ByValue, offset_bytes: 92, size_bytes: 4, access: GpgpuArtifactArgAccess::None, address_mode: GpgpuArtifactAddressMode::None },
        GpgpuArtifactPayloadArg { arg_index: 9, kind: GpgpuArtifactArgKind::ByValue, offset_bytes: 96, size_bytes: 4, access: GpgpuArtifactArgAccess::None, address_mode: GpgpuArtifactAddressMode::None },
        GpgpuArtifactPayloadArg { arg_index: 10, kind: GpgpuArtifactArgKind::ByValue, offset_bytes: 100, size_bytes: 4, access: GpgpuArtifactArgAccess::None, address_mode: GpgpuArtifactAddressMode::None },
    ],
};
