// @generated by tools/intel-gpu-bakery; DO NOT EDIT.
// source: crates/trueos-shader/gpgpu/kernels/glyph_mask_rgba8.clcpp
// frontend: Clang C++ for OpenCL -> LLVM bitcode -> llvm-spirv
// backend: Intel IGC through ocloc -spirv_input
// normalized commands: [["$CLANG","--target=spir64","-x","clcpp","-cl-std=CLC++","-Wall","-Wextra","-Werror","-Wdate-time","-cl-kernel-arg-info","-fno-discard-value-names","-fno-exceptions","-fno-rtti","-MMD","-MF","$OUT_DIR/glyph_mask_rgba8.d","-MT","glyph_mask_rgba8.bc","-emit-llvm","-c","glyph_mask_rgba8.clcpp","-o","$OUT_DIR/glyph_mask_rgba8.bc"],["$LLVM_SPIRV","--preserve-ocl-kernel-arg-type-metadata-through-string","$OUT_DIR/glyph_mask_rgba8.bc","-o","$OUT_DIR/glyph_mask_rgba8.spv"],["$OCLOC","compile","-file","$OUT_DIR/glyph_mask_rgba8.spv","-spirv_input","-device","0x4680","-64","-output","glyph_mask_rgba8","-out_dir","$OUT_DIR","-output_no_suffix","-gen_file"],["$OCLOC","validate","-file","$OUT_DIR/glyph_mask_rgba8.bin"]]

pub(crate) const GLYPH_MASK_RGBA8_ADLS_CPP_ABI_CONTRACT: GpgpuKernelAbiContract =
    GpgpuKernelAbiContract {
        schema_version: GPGPU_KERNEL_ABI_SCHEMA_VERSION,
        kernel_name: "glyph_mask_rgba8",
        target: GpgpuKernelTarget {
            label: "adls",
            pci_device_ids: &[0x4680],
            revision_min: 12,
            revision_max: 12,
        },
        ze_info_major: 1,
        ze_info_minor: 62,
        zebin_sha256: [
            0xc4, 0x2b, 0x19, 0x56, 0x53, 0x2b, 0xee, 0xd9, 0x3a, 0xd4, 0x22, 0xca, 0x5a, 0xa6,
            0xc9, 0x29, 0x3a, 0x05, 0xf6, 0x8e, 0xc3, 0x69, 0x18, 0x22, 0x38, 0x72, 0xd8, 0x78,
            0xfc, 0x20, 0x06, 0xdd,
        ],
        spv_sha256: [
            0x9b, 0x23, 0x5d, 0xbc, 0xc0, 0x2a, 0x92, 0x43, 0x2b, 0x14, 0x2a, 0xee, 0xfd, 0x93,
            0xc9, 0x64, 0x90, 0x39, 0x36, 0xf3, 0x2d, 0x60, 0x84, 0x4c, 0x50, 0xb7, 0xf5, 0x71,
            0xca, 0xb2, 0xa2, 0xab,
        ],
        text_section_name: ".text.glyph_mask_rgba8",
        text_section_offset: 64,
        text_section_size: 1792,
        entry_offset: 64,
        entry_size: 1624,
        simd_width: 16,
        grf_count: 128,
        scratch_bytes: 0,
        slm_bytes: 0,
        cross_thread_data_bytes: 128,
        per_thread_data_bytes: 96,
        bindings: &[
            GpgpuArtifactBinding {
                arg_index: 0,
                bti: 0,
            },
            GpgpuArtifactBinding {
                arg_index: 1,
                bti: 1,
            },
        ],
        implicit_payload_args: &[
            GpgpuArtifactImplicitPayloadArg {
                kind: GpgpuArtifactImplicitArgKind::GlobalIdOffset,
                offset_bytes: 0,
                size_bytes: 12,
            },
            GpgpuArtifactImplicitPayloadArg {
                kind: GpgpuArtifactImplicitArgKind::LocalSize,
                offset_bytes: 12,
                size_bytes: 12,
            },
            GpgpuArtifactImplicitPayloadArg {
                kind: GpgpuArtifactImplicitArgKind::EnqueuedLocalSize,
                offset_bytes: 32,
                size_bytes: 12,
            },
            GpgpuArtifactImplicitPayloadArg {
                kind: GpgpuArtifactImplicitArgKind::BufferOffset { arg_index: 0 },
                offset_bytes: 100,
                size_bytes: 4,
            },
        ],
        per_thread_payload_args: &[GpgpuArtifactPerThreadPayloadArg {
            kind: GpgpuArtifactPerThreadArgKind::LocalId,
            offset_bytes: 0,
            size_bytes: 96,
        }],
        payload_args: &[
            GpgpuArtifactPayloadArg {
                arg_index: 0,
                kind: GpgpuArtifactArgKind::ByPointer,
                offset_bytes: 48,
                size_bytes: 8,
                access: GpgpuArtifactArgAccess::ReadOnly,
                address_mode: GpgpuArtifactAddressMode::Stateful,
            },
            GpgpuArtifactPayloadArg {
                arg_index: 1,
                kind: GpgpuArtifactArgKind::ByPointer,
                offset_bytes: 56,
                size_bytes: 8,
                access: GpgpuArtifactArgAccess::ReadWrite,
                address_mode: GpgpuArtifactAddressMode::Stateful,
            },
            GpgpuArtifactPayloadArg {
                arg_index: 2,
                kind: GpgpuArtifactArgKind::ByValue,
                offset_bytes: 64,
                size_bytes: 4,
                access: GpgpuArtifactArgAccess::None,
                address_mode: GpgpuArtifactAddressMode::None,
            },
            GpgpuArtifactPayloadArg {
                arg_index: 3,
                kind: GpgpuArtifactArgKind::ByValue,
                offset_bytes: 68,
                size_bytes: 4,
                access: GpgpuArtifactArgAccess::None,
                address_mode: GpgpuArtifactAddressMode::None,
            },
            GpgpuArtifactPayloadArg {
                arg_index: 4,
                kind: GpgpuArtifactArgKind::ByValue,
                offset_bytes: 72,
                size_bytes: 4,
                access: GpgpuArtifactArgAccess::None,
                address_mode: GpgpuArtifactAddressMode::None,
            },
            GpgpuArtifactPayloadArg {
                arg_index: 5,
                kind: GpgpuArtifactArgKind::ByValue,
                offset_bytes: 76,
                size_bytes: 4,
                access: GpgpuArtifactArgAccess::None,
                address_mode: GpgpuArtifactAddressMode::None,
            },
            GpgpuArtifactPayloadArg {
                arg_index: 6,
                kind: GpgpuArtifactArgKind::ByValue,
                offset_bytes: 80,
                size_bytes: 4,
                access: GpgpuArtifactArgAccess::None,
                address_mode: GpgpuArtifactAddressMode::None,
            },
            GpgpuArtifactPayloadArg {
                arg_index: 7,
                kind: GpgpuArtifactArgKind::ByValue,
                offset_bytes: 84,
                size_bytes: 4,
                access: GpgpuArtifactArgAccess::None,
                address_mode: GpgpuArtifactAddressMode::None,
            },
            GpgpuArtifactPayloadArg {
                arg_index: 8,
                kind: GpgpuArtifactArgKind::ByValue,
                offset_bytes: 88,
                size_bytes: 4,
                access: GpgpuArtifactArgAccess::None,
                address_mode: GpgpuArtifactAddressMode::None,
            },
            GpgpuArtifactPayloadArg {
                arg_index: 9,
                kind: GpgpuArtifactArgKind::ByValue,
                offset_bytes: 92,
                size_bytes: 4,
                access: GpgpuArtifactArgAccess::None,
                address_mode: GpgpuArtifactAddressMode::None,
            },
            GpgpuArtifactPayloadArg {
                arg_index: 10,
                kind: GpgpuArtifactArgKind::ByValue,
                offset_bytes: 96,
                size_bytes: 4,
                access: GpgpuArtifactArgAccess::None,
                address_mode: GpgpuArtifactAddressMode::None,
            },
        ],
    };
