// @generated by tools/intel-gpu-bakery; DO NOT EDIT.
// source: crates/trueos-shader/gpgpu/kernels/lab256_multiphase.clcpp
// frontend: Clang C++ for OpenCL -> LLVM bitcode -> llvm-spirv
// backend: Intel IGC through ocloc -spirv_input
// normalized commands: [["$CLANG","--target=spir64","-x","clcpp","-cl-std=CLC++","-Wall","-Wextra","-Werror","-Wdate-time","-cl-kernel-arg-info","-fno-discard-value-names","-fno-exceptions","-fno-rtti","-MMD","-MF","$OUT_DIR/lab256_multiphase.d","-MT","lab256_multiphase.bc","-emit-llvm","-c","lab256_multiphase.clcpp","-o","$OUT_DIR/lab256_multiphase.bc"],["$LLVM_SPIRV","--preserve-ocl-kernel-arg-type-metadata-through-string","$OUT_DIR/lab256_multiphase.bc","-o","$OUT_DIR/lab256_multiphase.spv"],["$OCLOC","compile","-file","$OUT_DIR/lab256_multiphase.spv","-spirv_input","-device","0x4680","-64","-output","lab256_multiphase","-out_dir","$OUT_DIR","-output_no_suffix","-gen_file"],["$OCLOC","validate","-file","$OUT_DIR/lab256_multiphase.bin"]]

pub(crate) const LAB256_STEP_ADLS_CPP_ABI_CONTRACT: GpgpuKernelAbiContract = GpgpuKernelAbiContract {
    schema_version: GPGPU_KERNEL_ABI_SCHEMA_VERSION,
    kernel_name: "lab256_step",
    target: GpgpuKernelTarget {
        label: "adls",
        pci_device_ids: &[0x4680],
        revision_min: 12,
        revision_max: 12,
    },
    ze_info_major: 1,
    ze_info_minor: 62,
    zebin_sha256: [
        0x63, 0xff, 0x15, 0x3f, 0x71, 0x02, 0x21, 0xa8,
        0x81, 0x2d, 0x23, 0xe5, 0xb7, 0x46, 0x6d, 0x25,
        0x4d, 0xc0, 0xbe, 0xfd, 0xc9, 0x7d, 0xbc, 0xa5,
        0xeb, 0x8b, 0x0f, 0x95, 0x2d, 0x1d, 0x66, 0x46,
    ],
    spv_sha256: [
        0x24, 0x51, 0x5e, 0x9b, 0x48, 0x7f, 0x9e, 0x0b,
        0xbb, 0x06, 0x86, 0xe5, 0x0c, 0x37, 0x4e, 0x09,
        0xbd, 0xa2, 0xbb, 0xfe, 0xa9, 0x99, 0x9e, 0xa2,
        0x1f, 0x73, 0x64, 0xec, 0xf4, 0x4c, 0xe4, 0xe5,
    ],
    text_section_name: ".text.lab256_step",
    text_section_offset: 64,
    text_section_size: 6528,
    entry_offset: 64,
    entry_size: 6400,
    simd_width: 16,
    grf_count: 128,
    scratch_bytes: 0,
    slm_bytes: 0,
    cross_thread_data_bytes: 96,
    per_thread_data_bytes: 96,
    bindings: &[
        GpgpuArtifactBinding { arg_index: 0, bti: 0 },
        GpgpuArtifactBinding { arg_index: 1, bti: 1 },
        GpgpuArtifactBinding { arg_index: 2, bti: 2 },
    ],
    implicit_payload_args: &[
        GpgpuArtifactImplicitPayloadArg { kind: GpgpuArtifactImplicitArgKind::GlobalIdOffset, offset_bytes: 0, size_bytes: 12 },
        GpgpuArtifactImplicitPayloadArg { kind: GpgpuArtifactImplicitArgKind::LocalSize, offset_bytes: 12, size_bytes: 12 },
        GpgpuArtifactImplicitPayloadArg { kind: GpgpuArtifactImplicitArgKind::EnqueuedLocalSize, offset_bytes: 32, size_bytes: 12 },
    ],
    per_thread_payload_args: &[
        GpgpuArtifactPerThreadPayloadArg { kind: GpgpuArtifactPerThreadArgKind::LocalId, offset_bytes: 0, size_bytes: 96 },
    ],
    payload_args: &[
        GpgpuArtifactPayloadArg { arg_index: 0, kind: GpgpuArtifactArgKind::ByPointer, offset_bytes: 48, size_bytes: 8, access: GpgpuArtifactArgAccess::ReadOnly, address_mode: GpgpuArtifactAddressMode::Stateful },
        GpgpuArtifactPayloadArg { arg_index: 1, kind: GpgpuArtifactArgKind::ByPointer, offset_bytes: 56, size_bytes: 8, access: GpgpuArtifactArgAccess::ReadWrite, address_mode: GpgpuArtifactAddressMode::Stateful },
        GpgpuArtifactPayloadArg { arg_index: 2, kind: GpgpuArtifactArgKind::ByPointer, offset_bytes: 64, size_bytes: 8, access: GpgpuArtifactArgAccess::ReadOnly, address_mode: GpgpuArtifactAddressMode::Stateless },
    ],
};

pub(crate) const LAB256_REDUCE_ADLS_CPP_ABI_CONTRACT: GpgpuKernelAbiContract = GpgpuKernelAbiContract {
    schema_version: GPGPU_KERNEL_ABI_SCHEMA_VERSION,
    kernel_name: "lab256_reduce",
    target: GpgpuKernelTarget {
        label: "adls",
        pci_device_ids: &[0x4680],
        revision_min: 12,
        revision_max: 12,
    },
    ze_info_major: 1,
    ze_info_minor: 62,
    zebin_sha256: [
        0x63, 0xff, 0x15, 0x3f, 0x71, 0x02, 0x21, 0xa8,
        0x81, 0x2d, 0x23, 0xe5, 0xb7, 0x46, 0x6d, 0x25,
        0x4d, 0xc0, 0xbe, 0xfd, 0xc9, 0x7d, 0xbc, 0xa5,
        0xeb, 0x8b, 0x0f, 0x95, 0x2d, 0x1d, 0x66, 0x46,
    ],
    spv_sha256: [
        0x24, 0x51, 0x5e, 0x9b, 0x48, 0x7f, 0x9e, 0x0b,
        0xbb, 0x06, 0x86, 0xe5, 0x0c, 0x37, 0x4e, 0x09,
        0xbd, 0xa2, 0xbb, 0xfe, 0xa9, 0x99, 0x9e, 0xa2,
        0x1f, 0x73, 0x64, 0xec, 0xf4, 0x4c, 0xe4, 0xe5,
    ],
    text_section_name: ".text.lab256_reduce",
    text_section_offset: 6592,
    text_section_size: 1664,
    entry_offset: 6592,
    entry_size: 1536,
    simd_width: 16,
    grf_count: 128,
    scratch_bytes: 0,
    slm_bytes: 0,
    cross_thread_data_bytes: 96,
    per_thread_data_bytes: 96,
    bindings: &[
        GpgpuArtifactBinding { arg_index: 0, bti: 0 },
        GpgpuArtifactBinding { arg_index: 1, bti: 1 },
        GpgpuArtifactBinding { arg_index: 2, bti: 2 },
    ],
    implicit_payload_args: &[
        GpgpuArtifactImplicitPayloadArg { kind: GpgpuArtifactImplicitArgKind::GlobalIdOffset, offset_bytes: 0, size_bytes: 12 },
        GpgpuArtifactImplicitPayloadArg { kind: GpgpuArtifactImplicitArgKind::LocalSize, offset_bytes: 12, size_bytes: 12 },
        GpgpuArtifactImplicitPayloadArg { kind: GpgpuArtifactImplicitArgKind::EnqueuedLocalSize, offset_bytes: 32, size_bytes: 12 },
    ],
    per_thread_payload_args: &[
        GpgpuArtifactPerThreadPayloadArg { kind: GpgpuArtifactPerThreadArgKind::LocalId, offset_bytes: 0, size_bytes: 96 },
    ],
    payload_args: &[
        GpgpuArtifactPayloadArg { arg_index: 0, kind: GpgpuArtifactArgKind::ByPointer, offset_bytes: 48, size_bytes: 8, access: GpgpuArtifactArgAccess::ReadOnly, address_mode: GpgpuArtifactAddressMode::Stateful },
        GpgpuArtifactPayloadArg { arg_index: 1, kind: GpgpuArtifactArgKind::ByPointer, offset_bytes: 56, size_bytes: 8, access: GpgpuArtifactArgAccess::ReadWrite, address_mode: GpgpuArtifactAddressMode::Stateless },
        GpgpuArtifactPayloadArg { arg_index: 2, kind: GpgpuArtifactArgKind::ByPointer, offset_bytes: 64, size_bytes: 8, access: GpgpuArtifactArgAccess::ReadOnly, address_mode: GpgpuArtifactAddressMode::Stateful },
    ],
};

pub(crate) const LAB256_COMPOSITE_ADLS_CPP_ABI_CONTRACT: GpgpuKernelAbiContract = GpgpuKernelAbiContract {
    schema_version: GPGPU_KERNEL_ABI_SCHEMA_VERSION,
    kernel_name: "lab256_composite",
    target: GpgpuKernelTarget {
        label: "adls",
        pci_device_ids: &[0x4680],
        revision_min: 12,
        revision_max: 12,
    },
    ze_info_major: 1,
    ze_info_minor: 62,
    zebin_sha256: [
        0x63, 0xff, 0x15, 0x3f, 0x71, 0x02, 0x21, 0xa8,
        0x81, 0x2d, 0x23, 0xe5, 0xb7, 0x46, 0x6d, 0x25,
        0x4d, 0xc0, 0xbe, 0xfd, 0xc9, 0x7d, 0xbc, 0xa5,
        0xeb, 0x8b, 0x0f, 0x95, 0x2d, 0x1d, 0x66, 0x46,
    ],
    spv_sha256: [
        0x24, 0x51, 0x5e, 0x9b, 0x48, 0x7f, 0x9e, 0x0b,
        0xbb, 0x06, 0x86, 0xe5, 0x0c, 0x37, 0x4e, 0x09,
        0xbd, 0xa2, 0xbb, 0xfe, 0xa9, 0x99, 0x9e, 0xa2,
        0x1f, 0x73, 0x64, 0xec, 0xf4, 0x4c, 0xe4, 0xe5,
    ],
    text_section_name: ".text.lab256_composite",
    text_section_offset: 8256,
    text_section_size: 6464,
    entry_offset: 8256,
    entry_size: 6296,
    simd_width: 16,
    grf_count: 128,
    scratch_bytes: 0,
    slm_bytes: 0,
    cross_thread_data_bytes: 96,
    per_thread_data_bytes: 96,
    bindings: &[
        GpgpuArtifactBinding { arg_index: 0, bti: 0 },
        GpgpuArtifactBinding { arg_index: 1, bti: 1 },
        GpgpuArtifactBinding { arg_index: 2, bti: 2 },
        GpgpuArtifactBinding { arg_index: 3, bti: 3 },
    ],
    implicit_payload_args: &[
        GpgpuArtifactImplicitPayloadArg { kind: GpgpuArtifactImplicitArgKind::GlobalIdOffset, offset_bytes: 0, size_bytes: 12 },
        GpgpuArtifactImplicitPayloadArg { kind: GpgpuArtifactImplicitArgKind::LocalSize, offset_bytes: 12, size_bytes: 12 },
        GpgpuArtifactImplicitPayloadArg { kind: GpgpuArtifactImplicitArgKind::EnqueuedLocalSize, offset_bytes: 32, size_bytes: 12 },
    ],
    per_thread_payload_args: &[
        GpgpuArtifactPerThreadPayloadArg { kind: GpgpuArtifactPerThreadArgKind::LocalId, offset_bytes: 0, size_bytes: 96 },
    ],
    payload_args: &[
        GpgpuArtifactPayloadArg { arg_index: 0, kind: GpgpuArtifactArgKind::ByPointer, offset_bytes: 48, size_bytes: 8, access: GpgpuArtifactArgAccess::ReadOnly, address_mode: GpgpuArtifactAddressMode::Stateful },
        GpgpuArtifactPayloadArg { arg_index: 1, kind: GpgpuArtifactArgKind::ByPointer, offset_bytes: 56, size_bytes: 8, access: GpgpuArtifactArgAccess::ReadOnly, address_mode: GpgpuArtifactAddressMode::Stateless },
        GpgpuArtifactPayloadArg { arg_index: 2, kind: GpgpuArtifactArgKind::ByPointer, offset_bytes: 64, size_bytes: 8, access: GpgpuArtifactArgAccess::ReadOnly, address_mode: GpgpuArtifactAddressMode::Stateful },
        GpgpuArtifactPayloadArg { arg_index: 3, kind: GpgpuArtifactArgKind::ByPointer, offset_bytes: 72, size_bytes: 8, access: GpgpuArtifactArgAccess::ReadWrite, address_mode: GpgpuArtifactAddressMode::Stateful },
        GpgpuArtifactPayloadArg { arg_index: 4, kind: GpgpuArtifactArgKind::ByValue, offset_bytes: 80, size_bytes: 4, access: GpgpuArtifactArgAccess::None, address_mode: GpgpuArtifactAddressMode::None },
    ],
};
