// @generated by tools/intel-gpu-bakery; DO NOT EDIT.
// source: crates/trueos-shader/gpgpu/kernels/lz4_decode_cooperative.clcpp
// frontend: Clang C++ for OpenCL -> LLVM bitcode -> llvm-spirv
// backend: Intel IGC through ocloc -spirv_input
// normalized commands: [["$CLANG","--target=spir64","-x","clcpp","-cl-std=CLC++","-Wall","-Wextra","-Werror","-Wdate-time","-cl-kernel-arg-info","-fno-discard-value-names","-fno-exceptions","-fno-rtti","-MMD","-MF","$OUT_DIR/lz4_decode_cooperative.d","-MT","lz4_decode_cooperative.bc","-emit-llvm","-c","lz4_decode_cooperative.clcpp","-o","$OUT_DIR/lz4_decode_cooperative.bc"],["$LLVM_SPIRV","--preserve-ocl-kernel-arg-type-metadata-through-string","$OUT_DIR/lz4_decode_cooperative.bc","-o","$OUT_DIR/lz4_decode_cooperative.spv"],["$OCLOC","compile","-file","$OUT_DIR/lz4_decode_cooperative.spv","-spirv_input","-device","0x4680","-64","-output","lz4_decode_cooperative","-out_dir","$OUT_DIR","-output_no_suffix","-gen_file"],["$OCLOC","validate","-file","$OUT_DIR/lz4_decode_cooperative.bin"]]

pub(crate) const LZ4_DECODE_COOPERATIVE_ADLS_CPP_ABI_CONTRACT: GpgpuKernelAbiContract = GpgpuKernelAbiContract {
    schema_version: GPGPU_KERNEL_ABI_SCHEMA_VERSION,
    kernel_name: "lz4_decode_cooperative",
    target: GpgpuKernelTarget {
        label: "adls",
        pci_device_ids: &[0x4680],
        revision_min: 12,
        revision_max: 12,
    },
    ze_info_major: 1,
    ze_info_minor: 62,
    zebin_sha256: [
        0x77, 0x0a, 0xc9, 0x54, 0x69, 0xc7, 0xb7, 0x3d,
        0x26, 0x46, 0xd4, 0x73, 0x5d, 0xca, 0xbd, 0xba,
        0x1e, 0x6a, 0x57, 0xb4, 0xd4, 0x26, 0x1d, 0x81,
        0xc4, 0x27, 0xde, 0xff, 0x6f, 0xca, 0x99, 0xa7,
    ],
    spv_sha256: [
        0x09, 0xd4, 0x27, 0x2c, 0x1f, 0xcb, 0xbd, 0xe0,
        0x51, 0x57, 0x79, 0x07, 0x6c, 0xa9, 0xa3, 0xcc,
        0x75, 0x1d, 0x1d, 0x24, 0xcf, 0x75, 0x7f, 0x40,
        0xa3, 0xb5, 0xc8, 0xc0, 0xef, 0x8c, 0xfc, 0xd2,
    ],
    text_section_name: ".text.lz4_decode_cooperative",
    text_section_offset: 64,
    text_section_size: 7040,
    entry_offset: 64,
    entry_size: 6896,
    simd_width: 16,
    grf_count: 128,
    scratch_bytes: 0,
    slm_bytes: 0,
    cross_thread_data_bytes: 96,
    per_thread_data_bytes: 96,
    bindings: &[
        GpgpuArtifactBinding { arg_index: 0, bti: 0 },
        GpgpuArtifactBinding { arg_index: 1, bti: 1 },
        GpgpuArtifactBinding { arg_index: 2, bti: 2 },
    ],
    implicit_payload_args: &[
        GpgpuArtifactImplicitPayloadArg { kind: GpgpuArtifactImplicitArgKind::GlobalIdOffset, offset_bytes: 0, size_bytes: 12 },
        GpgpuArtifactImplicitPayloadArg { kind: GpgpuArtifactImplicitArgKind::LocalSize, offset_bytes: 12, size_bytes: 12 },
        GpgpuArtifactImplicitPayloadArg { kind: GpgpuArtifactImplicitArgKind::BufferOffset { arg_index: 0 }, offset_bytes: 60, size_bytes: 4 },
        GpgpuArtifactImplicitPayloadArg { kind: GpgpuArtifactImplicitArgKind::BufferOffset { arg_index: 1 }, offset_bytes: 64, size_bytes: 4 },
    ],
    per_thread_payload_args: &[
        GpgpuArtifactPerThreadPayloadArg { kind: GpgpuArtifactPerThreadArgKind::LocalId, offset_bytes: 0, size_bytes: 96 },
    ],
    payload_args: &[
        GpgpuArtifactPayloadArg { arg_index: 0, kind: GpgpuArtifactArgKind::ByPointer, offset_bytes: 32, size_bytes: 8, access: GpgpuArtifactArgAccess::ReadOnly, address_mode: GpgpuArtifactAddressMode::Stateful },
        GpgpuArtifactPayloadArg { arg_index: 1, kind: GpgpuArtifactArgKind::ByPointer, offset_bytes: 40, size_bytes: 8, access: GpgpuArtifactArgAccess::ReadWrite, address_mode: GpgpuArtifactAddressMode::Stateful },
        GpgpuArtifactPayloadArg { arg_index: 2, kind: GpgpuArtifactArgKind::ByPointer, offset_bytes: 48, size_bytes: 8, access: GpgpuArtifactArgAccess::ReadWrite, address_mode: GpgpuArtifactAddressMode::Stateful },
        GpgpuArtifactPayloadArg { arg_index: 3, kind: GpgpuArtifactArgKind::ByValue, offset_bytes: 56, size_bytes: 4, access: GpgpuArtifactArgAccess::None, address_mode: GpgpuArtifactAddressMode::None },
    ],
};
