// @generated by tools/intel-gpu-bakery; DO NOT EDIT.
// source: crates/trueos-shader/gpgpu/kernels/particle_craft.clcpp
// frontend: Clang C++ for OpenCL -> LLVM bitcode -> llvm-spirv
// backend: Intel IGC through ocloc -spirv_input
// normalized commands: [["$CLANG","--target=spir64","-x","clcpp","-cl-std=CLC++","-Wall","-Wextra","-Werror","-Wdate-time","-cl-kernel-arg-info","-fno-discard-value-names","-fno-exceptions","-fno-rtti","-MMD","-MF","$OUT_DIR/particle_craft.d","-MT","particle_craft.bc","-emit-llvm","-c","particle_craft.clcpp","-o","$OUT_DIR/particle_craft.bc"],["$LLVM_SPIRV","--preserve-ocl-kernel-arg-type-metadata-through-string","$OUT_DIR/particle_craft.bc","-o","$OUT_DIR/particle_craft.spv"],["$OCLOC","compile","-file","$OUT_DIR/particle_craft.spv","-spirv_input","-device","0x4680","-64","-output","particle_craft","-out_dir","$OUT_DIR","-output_no_suffix","-gen_file"],["$OCLOC","validate","-file","$OUT_DIR/particle_craft.bin"]]

pub(crate) const PARTICLE_CRAFT_STEP_ADLS_CPP_ABI_CONTRACT: GpgpuKernelAbiContract = GpgpuKernelAbiContract {
    schema_version: GPGPU_KERNEL_ABI_SCHEMA_VERSION,
    kernel_name: "particle_craft_step",
    target: GpgpuKernelTarget {
        label: "adls",
        pci_device_ids: &[0x4680],
        revision_min: 12,
        revision_max: 12,
    },
    ze_info_major: 1,
    ze_info_minor: 64,
    zebin_sha256: [
        0xa3, 0xbc, 0xb2, 0xa4, 0xf0, 0x41, 0xe1, 0xfb,
        0x82, 0xa0, 0x57, 0x1c, 0x5d, 0xcc, 0x49, 0x95,
        0x90, 0x61, 0x22, 0x91, 0x05, 0x11, 0x2e, 0xcc,
        0x22, 0x32, 0x11, 0xca, 0x83, 0xc2, 0xf4, 0x91,
    ],
    spv_sha256: [
        0x20, 0x19, 0x72, 0x3b, 0x05, 0x67, 0x0c, 0x5f,
        0x9c, 0x03, 0x67, 0xdf, 0x21, 0x35, 0x5a, 0x04,
        0xf8, 0xe4, 0xd3, 0xce, 0x55, 0xcc, 0x6d, 0x62,
        0x58, 0x79, 0xc9, 0xbe, 0x10, 0xe3, 0x7b, 0x59,
    ],
    text_section_name: ".text.particle_craft_step",
    text_section_offset: 64,
    text_section_size: 10688,
    entry_offset: 64,
    entry_size: 10504,
    simd_width: 16,
    grf_count: 128,
    scratch_bytes: 0,
    slm_bytes: 0,
    cross_thread_data_bytes: 64,
    per_thread_data_bytes: 96,
    bindings: &[
        GpgpuArtifactBinding { arg_index: 0, bti: 0 },
        GpgpuArtifactBinding { arg_index: 1, bti: 1 },
    ],
    implicit_payload_args: &[
        GpgpuArtifactImplicitPayloadArg { kind: GpgpuArtifactImplicitArgKind::GlobalIdOffset, offset_bytes: 0, size_bytes: 12 },
        GpgpuArtifactImplicitPayloadArg { kind: GpgpuArtifactImplicitArgKind::LocalSize, offset_bytes: 12, size_bytes: 12 },
        GpgpuArtifactImplicitPayloadArg { kind: GpgpuArtifactImplicitArgKind::EnqueuedLocalSize, offset_bytes: 32, size_bytes: 12 },
    ],
    per_thread_payload_args: &[
        GpgpuArtifactPerThreadPayloadArg { kind: GpgpuArtifactPerThreadArgKind::LocalId, offset_bytes: 0, size_bytes: 96 },
    ],
    payload_args: &[
        GpgpuArtifactPayloadArg { arg_index: 0, kind: GpgpuArtifactArgKind::ByPointer, offset_bytes: 48, size_bytes: 8, access: GpgpuArtifactArgAccess::ReadWrite, address_mode: GpgpuArtifactAddressMode::Stateful },
        GpgpuArtifactPayloadArg { arg_index: 1, kind: GpgpuArtifactArgKind::ByPointer, offset_bytes: 56, size_bytes: 8, access: GpgpuArtifactArgAccess::ReadOnly, address_mode: GpgpuArtifactAddressMode::Stateless },
    ],
};

pub(crate) const PARTICLE_CRAFT_BIN_TILES_ADLS_CPP_ABI_CONTRACT: GpgpuKernelAbiContract = GpgpuKernelAbiContract {
    schema_version: GPGPU_KERNEL_ABI_SCHEMA_VERSION,
    kernel_name: "particle_craft_bin_tiles",
    target: GpgpuKernelTarget {
        label: "adls",
        pci_device_ids: &[0x4680],
        revision_min: 12,
        revision_max: 12,
    },
    ze_info_major: 1,
    ze_info_minor: 64,
    zebin_sha256: [
        0xa3, 0xbc, 0xb2, 0xa4, 0xf0, 0x41, 0xe1, 0xfb,
        0x82, 0xa0, 0x57, 0x1c, 0x5d, 0xcc, 0x49, 0x95,
        0x90, 0x61, 0x22, 0x91, 0x05, 0x11, 0x2e, 0xcc,
        0x22, 0x32, 0x11, 0xca, 0x83, 0xc2, 0xf4, 0x91,
    ],
    spv_sha256: [
        0x20, 0x19, 0x72, 0x3b, 0x05, 0x67, 0x0c, 0x5f,
        0x9c, 0x03, 0x67, 0xdf, 0x21, 0x35, 0x5a, 0x04,
        0xf8, 0xe4, 0xd3, 0xce, 0x55, 0xcc, 0x6d, 0x62,
        0x58, 0x79, 0xc9, 0xbe, 0x10, 0xe3, 0x7b, 0x59,
    ],
    text_section_name: ".text.particle_craft_bin_tiles",
    text_section_offset: 10752,
    text_section_size: 19392,
    entry_offset: 10752,
    entry_size: 19264,
    simd_width: 16,
    grf_count: 128,
    scratch_bytes: 0,
    slm_bytes: 0,
    cross_thread_data_bytes: 96,
    per_thread_data_bytes: 96,
    bindings: &[
        GpgpuArtifactBinding { arg_index: 0, bti: 0 },
        GpgpuArtifactBinding { arg_index: 1, bti: 1 },
        GpgpuArtifactBinding { arg_index: 2, bti: 2 },
    ],
    implicit_payload_args: &[
        GpgpuArtifactImplicitPayloadArg { kind: GpgpuArtifactImplicitArgKind::GlobalIdOffset, offset_bytes: 0, size_bytes: 12 },
        GpgpuArtifactImplicitPayloadArg { kind: GpgpuArtifactImplicitArgKind::LocalSize, offset_bytes: 12, size_bytes: 12 },
        GpgpuArtifactImplicitPayloadArg { kind: GpgpuArtifactImplicitArgKind::EnqueuedLocalSize, offset_bytes: 32, size_bytes: 12 },
    ],
    per_thread_payload_args: &[
        GpgpuArtifactPerThreadPayloadArg { kind: GpgpuArtifactPerThreadArgKind::LocalId, offset_bytes: 0, size_bytes: 96 },
    ],
    payload_args: &[
        GpgpuArtifactPayloadArg { arg_index: 0, kind: GpgpuArtifactArgKind::ByPointer, offset_bytes: 48, size_bytes: 8, access: GpgpuArtifactArgAccess::ReadOnly, address_mode: GpgpuArtifactAddressMode::Stateful },
        GpgpuArtifactPayloadArg { arg_index: 1, kind: GpgpuArtifactArgKind::ByPointer, offset_bytes: 56, size_bytes: 8, access: GpgpuArtifactArgAccess::ReadOnly, address_mode: GpgpuArtifactAddressMode::Stateless },
        GpgpuArtifactPayloadArg { arg_index: 2, kind: GpgpuArtifactArgKind::ByPointer, offset_bytes: 64, size_bytes: 8, access: GpgpuArtifactArgAccess::ReadWrite, address_mode: GpgpuArtifactAddressMode::Stateful },
    ],
};

pub(crate) const PARTICLE_CRAFT_RENDER_RGBA8_ADLS_CPP_ABI_CONTRACT: GpgpuKernelAbiContract = GpgpuKernelAbiContract {
    schema_version: GPGPU_KERNEL_ABI_SCHEMA_VERSION,
    kernel_name: "particle_craft_render_rgba8",
    target: GpgpuKernelTarget {
        label: "adls",
        pci_device_ids: &[0x4680],
        revision_min: 12,
        revision_max: 12,
    },
    ze_info_major: 1,
    ze_info_minor: 64,
    zebin_sha256: [
        0xa3, 0xbc, 0xb2, 0xa4, 0xf0, 0x41, 0xe1, 0xfb,
        0x82, 0xa0, 0x57, 0x1c, 0x5d, 0xcc, 0x49, 0x95,
        0x90, 0x61, 0x22, 0x91, 0x05, 0x11, 0x2e, 0xcc,
        0x22, 0x32, 0x11, 0xca, 0x83, 0xc2, 0xf4, 0x91,
    ],
    spv_sha256: [
        0x20, 0x19, 0x72, 0x3b, 0x05, 0x67, 0x0c, 0x5f,
        0x9c, 0x03, 0x67, 0xdf, 0x21, 0x35, 0x5a, 0x04,
        0xf8, 0xe4, 0xd3, 0xce, 0x55, 0xcc, 0x6d, 0x62,
        0x58, 0x79, 0xc9, 0xbe, 0x10, 0xe3, 0x7b, 0x59,
    ],
    text_section_name: ".text.particle_craft_render_rgba8",
    text_section_offset: 30144,
    text_section_size: 26112,
    entry_offset: 30144,
    entry_size: 25984,
    simd_width: 16,
    grf_count: 128,
    scratch_bytes: 0,
    slm_bytes: 0,
    cross_thread_data_bytes: 96,
    per_thread_data_bytes: 96,
    bindings: &[
        GpgpuArtifactBinding { arg_index: 0, bti: 0 },
        GpgpuArtifactBinding { arg_index: 1, bti: 1 },
        GpgpuArtifactBinding { arg_index: 2, bti: 2 },
        GpgpuArtifactBinding { arg_index: 3, bti: 3 },
    ],
    implicit_payload_args: &[
        GpgpuArtifactImplicitPayloadArg { kind: GpgpuArtifactImplicitArgKind::GlobalIdOffset, offset_bytes: 0, size_bytes: 12 },
        GpgpuArtifactImplicitPayloadArg { kind: GpgpuArtifactImplicitArgKind::LocalSize, offset_bytes: 12, size_bytes: 12 },
        GpgpuArtifactImplicitPayloadArg { kind: GpgpuArtifactImplicitArgKind::EnqueuedLocalSize, offset_bytes: 32, size_bytes: 12 },
    ],
    per_thread_payload_args: &[
        GpgpuArtifactPerThreadPayloadArg { kind: GpgpuArtifactPerThreadArgKind::LocalId, offset_bytes: 0, size_bytes: 96 },
    ],
    payload_args: &[
        GpgpuArtifactPayloadArg { arg_index: 0, kind: GpgpuArtifactArgKind::ByPointer, offset_bytes: 48, size_bytes: 8, access: GpgpuArtifactArgAccess::ReadOnly, address_mode: GpgpuArtifactAddressMode::Stateful },
        GpgpuArtifactPayloadArg { arg_index: 1, kind: GpgpuArtifactArgKind::ByPointer, offset_bytes: 56, size_bytes: 8, access: GpgpuArtifactArgAccess::ReadOnly, address_mode: GpgpuArtifactAddressMode::Stateless },
        GpgpuArtifactPayloadArg { arg_index: 2, kind: GpgpuArtifactArgKind::ByPointer, offset_bytes: 64, size_bytes: 8, access: GpgpuArtifactArgAccess::ReadOnly, address_mode: GpgpuArtifactAddressMode::Stateful },
        GpgpuArtifactPayloadArg { arg_index: 3, kind: GpgpuArtifactArgKind::ByPointer, offset_bytes: 72, size_bytes: 8, access: GpgpuArtifactArgAccess::ReadWrite, address_mode: GpgpuArtifactAddressMode::Stateful },
    ],
};
