// @generated by tools/intel-gpu-bakery; DO NOT EDIT.
// source: /home/t4ce/Repos/Cubes/Cube/mandelbox/kernel.clcpp
// frontend: Clang C++ for OpenCL -> LLVM bitcode -> llvm-spirv
// backend: Intel IGC through ocloc -spirv_input
// normalized commands: [["$CLANG","--target=spir64","-x","clcpp","-cl-std=CLC++","-Wall","-Wextra","-Werror","-Wdate-time","-cl-kernel-arg-info","-fno-discard-value-names","-fno-exceptions","-fno-rtti","-MMD","-MF","$OUT_DIR/shadertoy_mandelbox.d","-MT","shadertoy_mandelbox.bc","-emit-llvm","-c","kernel.clcpp","-o","$OUT_DIR/shadertoy_mandelbox.bc"],["$LLVM_SPIRV","--preserve-ocl-kernel-arg-type-metadata-through-string","$OUT_DIR/shadertoy_mandelbox.bc","-o","$OUT_DIR/shadertoy_mandelbox.spv"],["$OCLOC","compile","-file","$OUT_DIR/shadertoy_mandelbox.spv","-spirv_input","-device","0x4680","-64","-output","shadertoy_mandelbox","-out_dir","$OUT_DIR","-output_no_suffix","-gen_file","-options","-cl-fast-relaxed-math"],["$OCLOC","validate","-file","$OUT_DIR/shadertoy_mandelbox.bin"]]

pub(crate) const SHADERTOY_MANDELBOX_ADLS_CPP_ABI_CONTRACT: GpgpuKernelAbiContract = GpgpuKernelAbiContract {
    schema_version: GPGPU_KERNEL_ABI_SCHEMA_VERSION,
    kernel_name: "shadertoy_mandelbox",
    target: GpgpuKernelTarget {
        label: "adls",
        pci_device_ids: &[0x4680],
        revision_min: 12,
        revision_max: 12,
    },
    ze_info_major: 1,
    ze_info_minor: 62,
    zebin_sha256: [
        0x65, 0x4e, 0xe1, 0x9b, 0xee, 0x2f, 0x6e, 0xed,
        0x00, 0x97, 0x19, 0x56, 0x22, 0x91, 0xef, 0x0f,
        0x27, 0x40, 0xdf, 0xd7, 0x46, 0x85, 0x67, 0x3a,
        0xd8, 0xfa, 0xba, 0x0d, 0x68, 0x12, 0x01, 0x7c,
    ],
    spv_sha256: [
        0xfb, 0xf3, 0x71, 0x1c, 0x00, 0xf6, 0x13, 0xfd,
        0xbf, 0x2e, 0x88, 0x57, 0x27, 0xd6, 0xfc, 0x32,
        0x06, 0xbf, 0xb8, 0x99, 0xe6, 0xfd, 0xd0, 0xd5,
        0xf1, 0x7b, 0x0b, 0x35, 0x44, 0x3a, 0x91, 0xf2,
    ],
    text_section_name: ".text.shadertoy_mandelbox",
    text_section_offset: 64,
    text_section_size: 35008,
    entry_offset: 64,
    entry_size: 34848,
    simd_width: 16,
    grf_count: 128,
    scratch_bytes: 0,
    slm_bytes: 0,
    cross_thread_data_bytes: 96,
    per_thread_data_bytes: 96,
    bindings: &[
        GpgpuArtifactBinding { arg_index: 0, bti: 0 },
        GpgpuArtifactBinding { arg_index: 1, bti: 1 },
    ],
    implicit_payload_args: &[
        GpgpuArtifactImplicitPayloadArg { kind: GpgpuArtifactImplicitArgKind::GlobalIdOffset, offset_bytes: 0, size_bytes: 12 },
        GpgpuArtifactImplicitPayloadArg { kind: GpgpuArtifactImplicitArgKind::LocalSize, offset_bytes: 12, size_bytes: 12 },
        GpgpuArtifactImplicitPayloadArg { kind: GpgpuArtifactImplicitArgKind::EnqueuedLocalSize, offset_bytes: 32, size_bytes: 12 },
    ],
    per_thread_payload_args: &[
        GpgpuArtifactPerThreadPayloadArg { kind: GpgpuArtifactPerThreadArgKind::LocalId, offset_bytes: 0, size_bytes: 96 },
    ],
    payload_args: &[
        GpgpuArtifactPayloadArg { arg_index: 0, kind: GpgpuArtifactArgKind::ByPointer, offset_bytes: 48, size_bytes: 8, access: GpgpuArtifactArgAccess::ReadWrite, address_mode: GpgpuArtifactAddressMode::Stateful },
        GpgpuArtifactPayloadArg { arg_index: 1, kind: GpgpuArtifactArgKind::ByPointer, offset_bytes: 56, size_bytes: 8, access: GpgpuArtifactArgAccess::ReadOnly, address_mode: GpgpuArtifactAddressMode::Stateless },
        GpgpuArtifactPayloadArg { arg_index: 2, kind: GpgpuArtifactArgKind::ByValue, offset_bytes: 64, size_bytes: 4, access: GpgpuArtifactArgAccess::None, address_mode: GpgpuArtifactAddressMode::None },
        GpgpuArtifactPayloadArg { arg_index: 3, kind: GpgpuArtifactArgKind::ByValue, offset_bytes: 68, size_bytes: 4, access: GpgpuArtifactArgAccess::None, address_mode: GpgpuArtifactAddressMode::None },
        GpgpuArtifactPayloadArg { arg_index: 4, kind: GpgpuArtifactArgKind::ByValue, offset_bytes: 72, size_bytes: 4, access: GpgpuArtifactArgAccess::None, address_mode: GpgpuArtifactAddressMode::None },
    ],
};
