// @generated by tools/intel-gpu-bakery; DO NOT EDIT.
// source: /home/t4ce/Repos/Cubes/Cube/mandelbox/kernel.clcpp
// frontend: Clang C++ for OpenCL -> LLVM bitcode -> llvm-spirv
// backend: Intel IGC through ocloc -spirv_input
// normalized commands: [["$CLANG","--target=spir64","-x","clcpp","-cl-std=CLC++","-Wall","-Wextra","-Werror","-Wdate-time","-cl-kernel-arg-info","-fno-discard-value-names","-fno-exceptions","-fno-rtti","-MMD","-MF","$OUT_DIR/shadertoy_mandelbox.d","-MT","shadertoy_mandelbox.bc","-emit-llvm","-c","kernel.clcpp","-o","$OUT_DIR/shadertoy_mandelbox.bc"],["$LLVM_SPIRV","--preserve-ocl-kernel-arg-type-metadata-through-string","$OUT_DIR/shadertoy_mandelbox.bc","-o","$OUT_DIR/shadertoy_mandelbox.spv"],["$OCLOC","compile","-file","$OUT_DIR/shadertoy_mandelbox.spv","-spirv_input","-device","0x4680","-64","-output","shadertoy_mandelbox","-out_dir","$OUT_DIR","-output_no_suffix","-gen_file","-options","-cl-fast-relaxed-math"],["$OCLOC","validate","-file","$OUT_DIR/shadertoy_mandelbox.bin"]]

pub(crate) const SHADERTOY_MANDELBOX_ADLS_CPP_ABI_CONTRACT: GpgpuKernelAbiContract = GpgpuKernelAbiContract {
    schema_version: GPGPU_KERNEL_ABI_SCHEMA_VERSION,
    kernel_name: "shadertoy_mandelbox",
    target: GpgpuKernelTarget {
        label: "adls",
        pci_device_ids: &[0x4680],
        revision_min: 12,
        revision_max: 12,
    },
    ze_info_major: 1,
    ze_info_minor: 62,
    zebin_sha256: [
        0x6c, 0xf0, 0x39, 0x04, 0x1c, 0x1f, 0xec, 0xb1,
        0x5b, 0x76, 0xb5, 0x32, 0x8f, 0x36, 0x04, 0x73,
        0xf9, 0x47, 0xc8, 0x19, 0x00, 0x75, 0xe6, 0x1b,
        0x34, 0x9a, 0x0b, 0x8e, 0x13, 0x33, 0x2a, 0x2b,
    ],
    spv_sha256: [
        0xec, 0x82, 0x44, 0x82, 0x49, 0xe3, 0x57, 0x72,
        0xda, 0x66, 0x69, 0xc6, 0x4a, 0xb6, 0x26, 0x9c,
        0x1e, 0x0d, 0xea, 0x83, 0x12, 0x7f, 0xec, 0xb1,
        0x0b, 0xe9, 0x74, 0xe2, 0x75, 0x9b, 0x9f, 0xa5,
    ],
    text_section_name: ".text.shadertoy_mandelbox",
    text_section_offset: 64,
    text_section_size: 28288,
    entry_offset: 64,
    entry_size: 28136,
    simd_width: 16,
    grf_count: 128,
    scratch_bytes: 0,
    slm_bytes: 0,
    cross_thread_data_bytes: 96,
    per_thread_data_bytes: 96,
    bindings: &[
        GpgpuArtifactBinding { arg_index: 0, bti: 0 },
        GpgpuArtifactBinding { arg_index: 1, bti: 1 },
    ],
    implicit_payload_args: &[
        GpgpuArtifactImplicitPayloadArg { kind: GpgpuArtifactImplicitArgKind::GlobalIdOffset, offset_bytes: 0, size_bytes: 12 },
        GpgpuArtifactImplicitPayloadArg { kind: GpgpuArtifactImplicitArgKind::LocalSize, offset_bytes: 12, size_bytes: 12 },
        GpgpuArtifactImplicitPayloadArg { kind: GpgpuArtifactImplicitArgKind::EnqueuedLocalSize, offset_bytes: 32, size_bytes: 12 },
    ],
    per_thread_payload_args: &[
        GpgpuArtifactPerThreadPayloadArg { kind: GpgpuArtifactPerThreadArgKind::LocalId, offset_bytes: 0, size_bytes: 96 },
    ],
    payload_args: &[
        GpgpuArtifactPayloadArg { arg_index: 0, kind: GpgpuArtifactArgKind::ByPointer, offset_bytes: 48, size_bytes: 8, access: GpgpuArtifactArgAccess::ReadWrite, address_mode: GpgpuArtifactAddressMode::Stateful },
        GpgpuArtifactPayloadArg { arg_index: 1, kind: GpgpuArtifactArgKind::ByPointer, offset_bytes: 56, size_bytes: 8, access: GpgpuArtifactArgAccess::ReadOnly, address_mode: GpgpuArtifactAddressMode::Stateless },
        GpgpuArtifactPayloadArg { arg_index: 2, kind: GpgpuArtifactArgKind::ByValue, offset_bytes: 64, size_bytes: 4, access: GpgpuArtifactArgAccess::None, address_mode: GpgpuArtifactAddressMode::None },
        GpgpuArtifactPayloadArg { arg_index: 3, kind: GpgpuArtifactArgKind::ByValue, offset_bytes: 68, size_bytes: 4, access: GpgpuArtifactArgAccess::None, address_mode: GpgpuArtifactAddressMode::None },
        GpgpuArtifactPayloadArg { arg_index: 4, kind: GpgpuArtifactArgKind::ByValue, offset_bytes: 72, size_bytes: 4, access: GpgpuArtifactArgAccess::None, address_mode: GpgpuArtifactAddressMode::None },
    ],
};
