// @generated by tools/intel-gpu-bakery; DO NOT EDIT.
// source: crates/trueos-shader/gpgpu/kernels/spirit_vfx_background_rgba8.clcpp
// frontend: Clang C++ for OpenCL -> LLVM bitcode -> llvm-spirv
// backend: Intel IGC through ocloc -spirv_input
// normalized commands: [["$CLANG","--target=spir64","-x","clcpp","-cl-std=CLC++","-Wall","-Wextra","-Werror","-Wdate-time","-cl-kernel-arg-info","-fno-discard-value-names","-fno-exceptions","-fno-rtti","-MMD","-MF","$OUT_DIR/spirit_vfx_background_rgba8.d","-MT","spirit_vfx_background_rgba8.bc","-emit-llvm","-c","spirit_vfx_background_rgba8.clcpp","-o","$OUT_DIR/spirit_vfx_background_rgba8.bc"],["$LLVM_SPIRV","--preserve-ocl-kernel-arg-type-metadata-through-string","$OUT_DIR/spirit_vfx_background_rgba8.bc","-o","$OUT_DIR/spirit_vfx_background_rgba8.spv"],["$OCLOC","compile","-file","$OUT_DIR/spirit_vfx_background_rgba8.spv","-spirv_input","-device","0x4680","-64","-output","spirit_vfx_background_rgba8","-out_dir","$OUT_DIR","-output_no_suffix","-gen_file"],["$OCLOC","validate","-file","$OUT_DIR/spirit_vfx_background_rgba8.bin"]]

pub(crate) const SPIRIT_VFX_BACKGROUND_RGBA8_ADLS_CPP_ABI_CONTRACT: GpgpuKernelAbiContract = GpgpuKernelAbiContract {
    schema_version: GPGPU_KERNEL_ABI_SCHEMA_VERSION,
    kernel_name: "spirit_vfx_background_rgba8",
    target: GpgpuKernelTarget {
        label: "adls",
        pci_device_ids: &[0x4680],
        revision_min: 12,
        revision_max: 12,
    },
    ze_info_major: 1,
    ze_info_minor: 64,
    zebin_sha256: [
        0x6e, 0x1f, 0x90, 0xa2, 0xaf, 0x80, 0x01, 0x03,
        0xf9, 0x5f, 0xcc, 0xa3, 0xde, 0x25, 0x32, 0x0f,
        0x0b, 0x9b, 0x7b, 0x73, 0xfb, 0xf9, 0x41, 0xd7,
        0x85, 0x2e, 0xc4, 0x08, 0xb1, 0x37, 0x5f, 0x19,
    ],
    spv_sha256: [
        0x3e, 0x14, 0x5e, 0xe2, 0x59, 0x63, 0x5f, 0x16,
        0xb0, 0x3e, 0x73, 0x56, 0xc0, 0xd9, 0x92, 0x94,
        0xf9, 0x84, 0xf8, 0x4e, 0xb0, 0xef, 0x3d, 0x46,
        0xe6, 0x73, 0xbf, 0x73, 0x0a, 0x15, 0xab, 0xeb,
    ],
    text_section_name: ".text.spirit_vfx_background_rgba8",
    text_section_offset: 64,
    text_section_size: 35456,
    entry_offset: 64,
    entry_size: 35272,
    simd_width: 16,
    grf_count: 128,
    scratch_bytes: 0,
    slm_bytes: 0,
    cross_thread_data_bytes: 64,
    per_thread_data_bytes: 96,
    bindings: &[
        GpgpuArtifactBinding { arg_index: 0, bti: 0 },
        GpgpuArtifactBinding { arg_index: 1, bti: 1 },
    ],
    implicit_payload_args: &[
        GpgpuArtifactImplicitPayloadArg { kind: GpgpuArtifactImplicitArgKind::GlobalIdOffset, offset_bytes: 0, size_bytes: 12 },
        GpgpuArtifactImplicitPayloadArg { kind: GpgpuArtifactImplicitArgKind::LocalSize, offset_bytes: 12, size_bytes: 12 },
        GpgpuArtifactImplicitPayloadArg { kind: GpgpuArtifactImplicitArgKind::EnqueuedLocalSize, offset_bytes: 32, size_bytes: 12 },
    ],
    per_thread_payload_args: &[
        GpgpuArtifactPerThreadPayloadArg { kind: GpgpuArtifactPerThreadArgKind::LocalId, offset_bytes: 0, size_bytes: 96 },
    ],
    payload_args: &[
        GpgpuArtifactPayloadArg { arg_index: 0, kind: GpgpuArtifactArgKind::ByPointer, offset_bytes: 48, size_bytes: 8, access: GpgpuArtifactArgAccess::ReadOnly, address_mode: GpgpuArtifactAddressMode::Stateless },
        GpgpuArtifactPayloadArg { arg_index: 1, kind: GpgpuArtifactArgKind::ByPointer, offset_bytes: 56, size_bytes: 8, access: GpgpuArtifactArgAccess::ReadWrite, address_mode: GpgpuArtifactAddressMode::Stateful },
    ],
};
