// @generated by tools/intel-gpu-bakery; DO NOT EDIT.
// source: crates/trueos-shader/gpgpu/kernels/spirit_vfx_background_rgba8.clcpp
// frontend: Clang C++ for OpenCL -> LLVM bitcode -> llvm-spirv
// backend: Intel IGC through ocloc -spirv_input
// normalized commands: [["$CLANG","--target=spir64","-x","clcpp","-cl-std=CLC++","-Wall","-Wextra","-Werror","-Wdate-time","-cl-kernel-arg-info","-fno-discard-value-names","-fno-exceptions","-fno-rtti","-MMD","-MF","$OUT_DIR/spirit_vfx_background_rgba8.d","-MT","spirit_vfx_background_rgba8.bc","-emit-llvm","-c","spirit_vfx_background_rgba8.clcpp","-o","$OUT_DIR/spirit_vfx_background_rgba8.bc"],["$LLVM_SPIRV","--preserve-ocl-kernel-arg-type-metadata-through-string","$OUT_DIR/spirit_vfx_background_rgba8.bc","-o","$OUT_DIR/spirit_vfx_background_rgba8.spv"],["$OCLOC","compile","-file","$OUT_DIR/spirit_vfx_background_rgba8.spv","-spirv_input","-device","0x4680","-64","-output","spirit_vfx_background_rgba8","-out_dir","$OUT_DIR","-output_no_suffix","-gen_file"],["$OCLOC","validate","-file","$OUT_DIR/spirit_vfx_background_rgba8.bin"]]

pub(crate) const SPIRIT_VFX_BACKGROUND_RGBA8_ADLS_CPP_ABI_CONTRACT: GpgpuKernelAbiContract = GpgpuKernelAbiContract {
    schema_version: GPGPU_KERNEL_ABI_SCHEMA_VERSION,
    kernel_name: "spirit_vfx_background_rgba8",
    target: GpgpuKernelTarget {
        label: "adls",
        pci_device_ids: &[0x4680],
        revision_min: 12,
        revision_max: 12,
    },
    ze_info_major: 1,
    ze_info_minor: 64,
    zebin_sha256: [
        0xa8, 0xa7, 0x78, 0x10, 0x8c, 0x0d, 0x86, 0xd9,
        0xd1, 0x34, 0xfd, 0xdd, 0xc2, 0x44, 0x19, 0x10,
        0x31, 0x7b, 0x1b, 0x8a, 0x39, 0x40, 0x4d, 0xa6,
        0x7b, 0xce, 0x02, 0xba, 0x2b, 0x34, 0xc3, 0x55,
    ],
    spv_sha256: [
        0x24, 0x0b, 0x37, 0x95, 0xdd, 0x78, 0xb6, 0x84,
        0xa1, 0x29, 0x37, 0xcd, 0x35, 0x0f, 0x1f, 0xc7,
        0xa0, 0xda, 0x51, 0x88, 0xc6, 0x95, 0x76, 0x40,
        0xd3, 0x0a, 0xaf, 0x4e, 0x66, 0x91, 0x27, 0x17,
    ],
    text_section_name: ".text.spirit_vfx_background_rgba8",
    text_section_offset: 64,
    text_section_size: 34816,
    entry_offset: 64,
    entry_size: 34648,
    simd_width: 16,
    grf_count: 128,
    scratch_bytes: 0,
    slm_bytes: 0,
    cross_thread_data_bytes: 64,
    per_thread_data_bytes: 96,
    bindings: &[
        GpgpuArtifactBinding { arg_index: 0, bti: 0 },
        GpgpuArtifactBinding { arg_index: 1, bti: 1 },
    ],
    implicit_payload_args: &[
        GpgpuArtifactImplicitPayloadArg { kind: GpgpuArtifactImplicitArgKind::GlobalIdOffset, offset_bytes: 0, size_bytes: 12 },
        GpgpuArtifactImplicitPayloadArg { kind: GpgpuArtifactImplicitArgKind::LocalSize, offset_bytes: 12, size_bytes: 12 },
        GpgpuArtifactImplicitPayloadArg { kind: GpgpuArtifactImplicitArgKind::EnqueuedLocalSize, offset_bytes: 32, size_bytes: 12 },
    ],
    per_thread_payload_args: &[
        GpgpuArtifactPerThreadPayloadArg { kind: GpgpuArtifactPerThreadArgKind::LocalId, offset_bytes: 0, size_bytes: 96 },
    ],
    payload_args: &[
        GpgpuArtifactPayloadArg { arg_index: 0, kind: GpgpuArtifactArgKind::ByPointer, offset_bytes: 48, size_bytes: 8, access: GpgpuArtifactArgAccess::ReadOnly, address_mode: GpgpuArtifactAddressMode::Stateless },
        GpgpuArtifactPayloadArg { arg_index: 1, kind: GpgpuArtifactArgKind::ByPointer, offset_bytes: 56, size_bytes: 8, access: GpgpuArtifactArgAccess::ReadWrite, address_mode: GpgpuArtifactAddressMode::Stateful },
    ],
};
