// @generated by tools/intel-gpu-bakery; DO NOT EDIT.
// source: crates/trueos-shader/gpgpu/kernels/spirit_vfx_background_rgba8.clcpp
// frontend: Clang C++ for OpenCL -> LLVM bitcode -> llvm-spirv
// backend: Intel IGC through ocloc -spirv_input
// normalized commands: [["$CLANG","--target=spir64","-x","clcpp","-cl-std=CLC++","-Wall","-Wextra","-Werror","-Wdate-time","-cl-kernel-arg-info","-fno-discard-value-names","-fno-exceptions","-fno-rtti","-MMD","-MF","$OUT_DIR/spirit_vfx_background_rgba8.d","-MT","spirit_vfx_background_rgba8.bc","-emit-llvm","-c","spirit_vfx_background_rgba8.clcpp","-o","$OUT_DIR/spirit_vfx_background_rgba8.bc"],["$LLVM_SPIRV","--preserve-ocl-kernel-arg-type-metadata-through-string","$OUT_DIR/spirit_vfx_background_rgba8.bc","-o","$OUT_DIR/spirit_vfx_background_rgba8.spv"],["$OCLOC","compile","-file","$OUT_DIR/spirit_vfx_background_rgba8.spv","-spirv_input","-device","0x4680","-64","-output","spirit_vfx_background_rgba8","-out_dir","$OUT_DIR","-output_no_suffix","-gen_file"],["$OCLOC","validate","-file","$OUT_DIR/spirit_vfx_background_rgba8.bin"]]

pub(crate) const SPIRIT_VFX_BACKGROUND_RGBA8_ADLS_CPP_ABI_CONTRACT: GpgpuKernelAbiContract = GpgpuKernelAbiContract {
    schema_version: GPGPU_KERNEL_ABI_SCHEMA_VERSION,
    kernel_name: "spirit_vfx_background_rgba8",
    target: GpgpuKernelTarget {
        label: "adls",
        pci_device_ids: &[0x4680],
        revision_min: 12,
        revision_max: 12,
    },
    ze_info_major: 1,
    ze_info_minor: 64,
    zebin_sha256: [
        0x4c, 0x82, 0x59, 0x2a, 0x44, 0x1b, 0x88, 0x90,
        0x24, 0x91, 0xb6, 0xd3, 0xcf, 0x8f, 0x99, 0xa3,
        0x52, 0x4a, 0x41, 0x17, 0x8a, 0x34, 0x79, 0x28,
        0xcf, 0x58, 0x45, 0xe0, 0x87, 0x28, 0x41, 0xf7,
    ],
    spv_sha256: [
        0x0a, 0xcb, 0x9f, 0xff, 0xa9, 0x11, 0xd6, 0x39,
        0x99, 0x53, 0x9c, 0xa1, 0x46, 0xc1, 0x96, 0x84,
        0xca, 0xbe, 0x14, 0x28, 0x48, 0x99, 0x88, 0x6f,
        0x90, 0xa5, 0x5f, 0x77, 0x50, 0x8a, 0x70, 0xbe,
    ],
    text_section_name: ".text.spirit_vfx_background_rgba8",
    text_section_offset: 64,
    text_section_size: 35072,
    entry_offset: 64,
    entry_size: 34912,
    simd_width: 16,
    grf_count: 128,
    scratch_bytes: 0,
    slm_bytes: 0,
    cross_thread_data_bytes: 64,
    per_thread_data_bytes: 96,
    bindings: &[
        GpgpuArtifactBinding { arg_index: 0, bti: 0 },
        GpgpuArtifactBinding { arg_index: 1, bti: 1 },
    ],
    implicit_payload_args: &[
        GpgpuArtifactImplicitPayloadArg { kind: GpgpuArtifactImplicitArgKind::GlobalIdOffset, offset_bytes: 0, size_bytes: 12 },
        GpgpuArtifactImplicitPayloadArg { kind: GpgpuArtifactImplicitArgKind::LocalSize, offset_bytes: 12, size_bytes: 12 },
        GpgpuArtifactImplicitPayloadArg { kind: GpgpuArtifactImplicitArgKind::EnqueuedLocalSize, offset_bytes: 32, size_bytes: 12 },
    ],
    per_thread_payload_args: &[
        GpgpuArtifactPerThreadPayloadArg { kind: GpgpuArtifactPerThreadArgKind::LocalId, offset_bytes: 0, size_bytes: 96 },
    ],
    payload_args: &[
        GpgpuArtifactPayloadArg { arg_index: 0, kind: GpgpuArtifactArgKind::ByPointer, offset_bytes: 48, size_bytes: 8, access: GpgpuArtifactArgAccess::ReadOnly, address_mode: GpgpuArtifactAddressMode::Stateless },
        GpgpuArtifactPayloadArg { arg_index: 1, kind: GpgpuArtifactArgKind::ByPointer, offset_bytes: 56, size_bytes: 8, access: GpgpuArtifactArgAccess::ReadWrite, address_mode: GpgpuArtifactAddressMode::Stateful },
    ],
};
