// @generated by tools/intel-gpu-bakery; DO NOT EDIT.
// source: crates/trueos-shader/gpgpu/kernels/sprite_quad_worklist_rgba8.clcpp
// frontend: Clang C++ for OpenCL -> LLVM bitcode -> llvm-spirv
// backend: Intel IGC through ocloc -spirv_input
// normalized commands: [["$CLANG","--target=spir64","-x","clcpp","-cl-std=CLC++","-Wall","-Wextra","-Werror","-Wdate-time","-cl-kernel-arg-info","-fno-discard-value-names","-fno-exceptions","-fno-rtti","-MMD","-MF","$OUT_DIR/sprite_quad_worklist_rgba8.d","-MT","sprite_quad_worklist_rgba8.bc","-emit-llvm","-c","sprite_quad_worklist_rgba8.clcpp","-o","$OUT_DIR/sprite_quad_worklist_rgba8.bc"],["$LLVM_SPIRV","--preserve-ocl-kernel-arg-type-metadata-through-string","$OUT_DIR/sprite_quad_worklist_rgba8.bc","-o","$OUT_DIR/sprite_quad_worklist_rgba8.spv"],["$OCLOC","compile","-file","$OUT_DIR/sprite_quad_worklist_rgba8.spv","-spirv_input","-device","0x4680","-64","-output","sprite_quad_worklist_rgba8","-out_dir","$OUT_DIR","-output_no_suffix","-gen_file"],["$OCLOC","validate","-file","$OUT_DIR/sprite_quad_worklist_rgba8.bin"]]

pub(crate) const SPRITE_QUAD_WORKLIST_RGBA8_ADLS_CPP_ABI_CONTRACT: GpgpuKernelAbiContract =
    GpgpuKernelAbiContract {
        schema_version: GPGPU_KERNEL_ABI_SCHEMA_VERSION,
        kernel_name: "sprite_quad_worklist_rgba8",
        target: GpgpuKernelTarget {
            label: "adls",
            pci_device_ids: &[0x4680],
            revision_min: 12,
            revision_max: 12,
        },
        ze_info_major: 1,
        ze_info_minor: 62,
        zebin_sha256: [
            0xd4, 0xe7, 0x5a, 0xce, 0xc4, 0xaf, 0x2b, 0x70, 0x7e, 0xc7, 0x08, 0x5e, 0x46, 0x52,
            0xf9, 0xcd, 0x48, 0x47, 0xfc, 0xc2, 0x19, 0xfe, 0x41, 0x99, 0xba, 0xee, 0x86, 0xfe,
            0x49, 0x0e, 0x1f, 0xd8,
        ],
        spv_sha256: [
            0x51, 0x25, 0x11, 0x2f, 0xb4, 0xcc, 0x29, 0x52, 0x1a, 0x4c, 0x12, 0x77, 0x9d, 0x16,
            0x95, 0x31, 0xac, 0x6d, 0x00, 0x5d, 0xb0, 0xd8, 0x8a, 0xd6, 0x26, 0x40, 0x8b, 0x17,
            0xa7, 0xcb, 0x24, 0x55,
        ],
        text_section_name: ".text.sprite_quad_worklist_rgba8",
        text_section_offset: 64,
        text_section_size: 14144,
        entry_offset: 64,
        entry_size: 13968,
        simd_width: 16,
        grf_count: 128,
        scratch_bytes: 0,
        slm_bytes: 0,
        cross_thread_data_bytes: 128,
        per_thread_data_bytes: 96,
        bindings: &[
            GpgpuArtifactBinding {
                arg_index: 0,
                bti: 0,
            },
            GpgpuArtifactBinding {
                arg_index: 1,
                bti: 1,
            },
            GpgpuArtifactBinding {
                arg_index: 2,
                bti: 2,
            },
        ],
        implicit_payload_args: &[
            GpgpuArtifactImplicitPayloadArg {
                kind: GpgpuArtifactImplicitArgKind::GlobalIdOffset,
                offset_bytes: 0,
                size_bytes: 12,
            },
            GpgpuArtifactImplicitPayloadArg {
                kind: GpgpuArtifactImplicitArgKind::LocalSize,
                offset_bytes: 12,
                size_bytes: 12,
            },
            GpgpuArtifactImplicitPayloadArg {
                kind: GpgpuArtifactImplicitArgKind::EnqueuedLocalSize,
                offset_bytes: 32,
                size_bytes: 12,
            },
            GpgpuArtifactImplicitPayloadArg {
                kind: GpgpuArtifactImplicitArgKind::BufferOffset { arg_index: 2 },
                offset_bytes: 104,
                size_bytes: 4,
            },
        ],
        per_thread_payload_args: &[GpgpuArtifactPerThreadPayloadArg {
            kind: GpgpuArtifactPerThreadArgKind::LocalId,
            offset_bytes: 0,
            size_bytes: 96,
        }],
        payload_args: &[
            GpgpuArtifactPayloadArg {
                arg_index: 0,
                kind: GpgpuArtifactArgKind::ByPointer,
                offset_bytes: 48,
                size_bytes: 8,
                access: GpgpuArtifactArgAccess::ReadOnly,
                address_mode: GpgpuArtifactAddressMode::Stateful,
            },
            GpgpuArtifactPayloadArg {
                arg_index: 1,
                kind: GpgpuArtifactArgKind::ByPointer,
                offset_bytes: 56,
                size_bytes: 8,
                access: GpgpuArtifactArgAccess::ReadWrite,
                address_mode: GpgpuArtifactAddressMode::Stateful,
            },
            GpgpuArtifactPayloadArg {
                arg_index: 2,
                kind: GpgpuArtifactArgKind::ByPointer,
                offset_bytes: 64,
                size_bytes: 8,
                access: GpgpuArtifactArgAccess::ReadOnly,
                address_mode: GpgpuArtifactAddressMode::Stateful,
            },
            GpgpuArtifactPayloadArg {
                arg_index: 3,
                kind: GpgpuArtifactArgKind::ByValue,
                offset_bytes: 72,
                size_bytes: 4,
                access: GpgpuArtifactArgAccess::None,
                address_mode: GpgpuArtifactAddressMode::None,
            },
            GpgpuArtifactPayloadArg {
                arg_index: 4,
                kind: GpgpuArtifactArgKind::ByValue,
                offset_bytes: 76,
                size_bytes: 4,
                access: GpgpuArtifactArgAccess::None,
                address_mode: GpgpuArtifactAddressMode::None,
            },
            GpgpuArtifactPayloadArg {
                arg_index: 5,
                kind: GpgpuArtifactArgKind::ByValue,
                offset_bytes: 80,
                size_bytes: 4,
                access: GpgpuArtifactArgAccess::None,
                address_mode: GpgpuArtifactAddressMode::None,
            },
            GpgpuArtifactPayloadArg {
                arg_index: 6,
                kind: GpgpuArtifactArgKind::ByValue,
                offset_bytes: 84,
                size_bytes: 4,
                access: GpgpuArtifactArgAccess::None,
                address_mode: GpgpuArtifactAddressMode::None,
            },
            GpgpuArtifactPayloadArg {
                arg_index: 7,
                kind: GpgpuArtifactArgKind::ByValue,
                offset_bytes: 88,
                size_bytes: 4,
                access: GpgpuArtifactArgAccess::None,
                address_mode: GpgpuArtifactAddressMode::None,
            },
            GpgpuArtifactPayloadArg {
                arg_index: 8,
                kind: GpgpuArtifactArgKind::ByValue,
                offset_bytes: 92,
                size_bytes: 4,
                access: GpgpuArtifactArgAccess::None,
                address_mode: GpgpuArtifactAddressMode::None,
            },
            GpgpuArtifactPayloadArg {
                arg_index: 9,
                kind: GpgpuArtifactArgKind::ByValue,
                offset_bytes: 96,
                size_bytes: 4,
                access: GpgpuArtifactArgAccess::None,
                address_mode: GpgpuArtifactAddressMode::None,
            },
            GpgpuArtifactPayloadArg {
                arg_index: 10,
                kind: GpgpuArtifactArgKind::ByValue,
                offset_bytes: 100,
                size_bytes: 4,
                access: GpgpuArtifactArgAccess::None,
                address_mode: GpgpuArtifactAddressMode::None,
            },
        ],
    };
