#![allow(dead_code)]

// Source element formats supported by the VF unit, distilled from the PRM
// table the user pasted into this file. Page headers and repeated captions
// have been removed, and the remaining rows are represented as typed Rust
// metadata so the table can be queried in code.

#[derive(Copy, Clone, Debug, Eq, PartialEq)]
pub(crate) enum VfConvertedType {
    Float,
    Sint,
    Uint,
    None,
}

#[derive(Copy, Clone, Debug, Eq, PartialEq)]
pub(crate) enum VfComponent {
    R,
    G,
    B,
    A,
}

#[derive(Copy, Clone, Debug, Eq, PartialEq)]
pub(crate) enum VfFormat {
    R32G32B32A32Float,
    R32G32B32A32Sint,
    R32G32B32A32Uint,
    R32G32B32A32Unorm,
    R32G32B32A32Snorm,
    R64G64Float,
    R32G32B32A32Sscaled,
    R32G32B32A32Uscaled,
    R32G32B32A32Sfixed,
    R64G64Passthru,
    R32G32B32Float,
    R32G32B32Sint,
    R32G32B32Uint,
    R32G32B32Unorm,
    R32G32B32Snorm,
    R32G32B32Sscaled,
    R32G32B32Uscaled,
    R32G32B32Sfixed,
    R16G16B16A16Unorm,
    R16G16B16A16Snorm,
    R16G16B16A16Sint,
    R16G16B16A16Uint,
    R16G16B16A16Float,
    R32G32Float,
    R32G32Sint,
    R32G32Uint,
    R32G32Unorm,
    R32G32Snorm,
    R64Float,
    R16G16B16A16Sscaled,
    R16G16B16A16Uscaled,
    R32G32Sscaled,
    R32G32Uscaled,
    R32G32Sfixed,
    R64Passthru,
    B8G8R8A8Unorm,
    R10G10B10A2Unorm,
    R10G10B10A2Uint,
    R10G10B10SnormA2Unorm,
    R8G8B8A8Unorm,
    R8G8B8A8Snorm,
    R8G8B8A8Sint,
    R8G8B8A8Uint,
    R16G16Unorm,
    R16G16Snorm,
    R16G16Sint,
    R16G16Uint,
    R16G16Float,
    B10G10R10A2Unorm,
    R11G11B10Float,
    R32Sint,
    R32Uint,
    R32Float,
    R32Unorm,
    R32Snorm,
    R10G10B10X2Uscaled,
    R8G8B8A8Sscaled,
    R8G8B8A8Uscaled,
    R16G16Sscaled,
    R16G16Uscaled,
    R32Sscaled,
    R32Uscaled,
    R8G8Unorm,
    R8G8Snorm,
    R8G8Sint,
    R8G8Uint,
    R16Unorm,
    R16Snorm,
    R16Sint,
    R16Uint,
    R16Float,
    R8G8Sscaled,
    R8G8Uscaled,
    R16Sscaled,
    R16Uscaled,
    R8Unorm,
    R8Snorm,
    R8Sint,
    R8Uint,
    R8Sscaled,
    R8Uscaled,
    R8G8B8Unorm,
    R8G8B8Snorm,
    R8G8B8Sscaled,
    R8G8B8Uscaled,
    R8G8B8Sint,
    R8G8B8Uint,
    R64G64B64A64Float,
    R64G64B64Float,
    R16G16B16Float,
    R16G16B16Unorm,
    R16G16B16Snorm,
    R16G16B16Sscaled,
    R16G16B16Uscaled,
    R16G16B16Uint,
    R16G16B16Sint,
    R32Sfixed,
    R10G10B10A2Snorm,
    R10G10B10A2Uscaled,
    R10G10B10A2Sscaled,
    R10G10B10A2Sint,
    B10G10R10A2Snorm,
    B10G10R10A2Uscaled,
    B10G10R10A2Sscaled,
    B10G10R10A2Uint,
    B10G10R10A2Sint,
    R64G64B64A64Passthru,
    R64G64B64Passthru,
}

#[derive(Copy, Clone, Debug, Eq, PartialEq)]
pub(crate) struct VfFormatInfo {
    pub(crate) format: VfFormat,
    pub(crate) converted_type: VfConvertedType,
    pub(crate) components: [Option<VfComponent>; 4],
}

pub(crate) const VF_FORMATS: &[VfFormat] = &[
    VfFormat::R32G32B32A32Float,
    VfFormat::R32G32B32A32Sint,
    VfFormat::R32G32B32A32Uint,
    VfFormat::R32G32B32A32Unorm,
    VfFormat::R32G32B32A32Snorm,
    VfFormat::R64G64Float,
    VfFormat::R32G32B32A32Sscaled,
    VfFormat::R32G32B32A32Uscaled,
    VfFormat::R32G32B32A32Sfixed,
    VfFormat::R64G64Passthru,
    VfFormat::R32G32B32Float,
    VfFormat::R32G32B32Sint,
    VfFormat::R32G32B32Uint,
    VfFormat::R32G32B32Unorm,
    VfFormat::R32G32B32Snorm,
    VfFormat::R32G32B32Sscaled,
    VfFormat::R32G32B32Uscaled,
    VfFormat::R32G32B32Sfixed,
    VfFormat::R16G16B16A16Unorm,
    VfFormat::R16G16B16A16Snorm,
    VfFormat::R16G16B16A16Sint,
    VfFormat::R16G16B16A16Uint,
    VfFormat::R16G16B16A16Float,
    VfFormat::R32G32Float,
    VfFormat::R32G32Sint,
    VfFormat::R32G32Uint,
    VfFormat::R32G32Unorm,
    VfFormat::R32G32Snorm,
    VfFormat::R64Float,
    VfFormat::R16G16B16A16Sscaled,
    VfFormat::R16G16B16A16Uscaled,
    VfFormat::R32G32Sscaled,
    VfFormat::R32G32Uscaled,
    VfFormat::R32G32Sfixed,
    VfFormat::R64Passthru,
    VfFormat::B8G8R8A8Unorm,
    VfFormat::R10G10B10A2Unorm,
    VfFormat::R10G10B10A2Uint,
    VfFormat::R10G10B10SnormA2Unorm,
    VfFormat::R8G8B8A8Unorm,
    VfFormat::R8G8B8A8Snorm,
    VfFormat::R8G8B8A8Sint,
    VfFormat::R8G8B8A8Uint,
    VfFormat::R16G16Unorm,
    VfFormat::R16G16Snorm,
    VfFormat::R16G16Sint,
    VfFormat::R16G16Uint,
    VfFormat::R16G16Float,
    VfFormat::B10G10R10A2Unorm,
    VfFormat::R11G11B10Float,
    VfFormat::R32Sint,
    VfFormat::R32Uint,
    VfFormat::R32Float,
    VfFormat::R32Unorm,
    VfFormat::R32Snorm,
    VfFormat::R10G10B10X2Uscaled,
    VfFormat::R8G8B8A8Sscaled,
    VfFormat::R8G8B8A8Uscaled,
    VfFormat::R16G16Sscaled,
    VfFormat::R16G16Uscaled,
    VfFormat::R32Sscaled,
    VfFormat::R32Uscaled,
    VfFormat::R8G8Unorm,
    VfFormat::R8G8Snorm,
    VfFormat::R8G8Sint,
    VfFormat::R8G8Uint,
    VfFormat::R16Unorm,
    VfFormat::R16Snorm,
    VfFormat::R16Sint,
    VfFormat::R16Uint,
    VfFormat::R16Float,
    VfFormat::R8G8Sscaled,
    VfFormat::R8G8Uscaled,
    VfFormat::R16Sscaled,
    VfFormat::R16Uscaled,
    VfFormat::R8Unorm,
    VfFormat::R8Snorm,
    VfFormat::R8Sint,
    VfFormat::R8Uint,
    VfFormat::R8Sscaled,
    VfFormat::R8Uscaled,
    VfFormat::R8G8B8Unorm,
    VfFormat::R8G8B8Snorm,
    VfFormat::R8G8B8Sscaled,
    VfFormat::R8G8B8Uscaled,
    VfFormat::R8G8B8Sint,
    VfFormat::R8G8B8Uint,
    VfFormat::R64G64B64A64Float,
    VfFormat::R64G64B64Float,
    VfFormat::R16G16B16Float,
    VfFormat::R16G16B16Unorm,
    VfFormat::R16G16B16Snorm,
    VfFormat::R16G16B16Sscaled,
    VfFormat::R16G16B16Uscaled,
    VfFormat::R16G16B16Uint,
    VfFormat::R16G16B16Sint,
    VfFormat::R32Sfixed,
    VfFormat::R10G10B10A2Snorm,
    VfFormat::R10G10B10A2Uscaled,
    VfFormat::R10G10B10A2Sscaled,
    VfFormat::R10G10B10A2Sint,
    VfFormat::B10G10R10A2Snorm,
    VfFormat::B10G10R10A2Uscaled,
    VfFormat::B10G10R10A2Sscaled,
    VfFormat::B10G10R10A2Uint,
    VfFormat::B10G10R10A2Sint,
    VfFormat::R64G64B64A64Passthru,
    VfFormat::R64G64B64Passthru,
];

impl VfFormat {
    pub(crate) const fn symbol(self) -> &'static str {
        match self {
            Self::R32G32B32A32Float => "R32G32B32A32_FLOAT",
            Self::R32G32B32A32Sint => "R32G32B32A32_SINT",
            Self::R32G32B32A32Uint => "R32G32B32A32_UINT",
            Self::R32G32B32A32Unorm => "R32G32B32A32_UNORM",
            Self::R32G32B32A32Snorm => "R32G32B32A32_SNORM",
            Self::R64G64Float => "R64G64_FLOAT",
            Self::R32G32B32A32Sscaled => "R32G32B32A32_SSCALED",
            Self::R32G32B32A32Uscaled => "R32G32B32A32_USCALED",
            Self::R32G32B32A32Sfixed => "R32G32B32A32_SFIXED",
            Self::R64G64Passthru => "R64G64_PASSTHRU",
            Self::R32G32B32Float => "R32G32B32_FLOAT",
            Self::R32G32B32Sint => "R32G32B32_SINT",
            Self::R32G32B32Uint => "R32G32B32_UINT",
            Self::R32G32B32Unorm => "R32G32B32_UNORM",
            Self::R32G32B32Snorm => "R32G32B32_SNORM",
            Self::R32G32B32Sscaled => "R32G32B32_SSCALED",
            Self::R32G32B32Uscaled => "R32G32B32_USCALED",
            Self::R32G32B32Sfixed => "R32G32B32_SFIXED",
            Self::R16G16B16A16Unorm => "R16G16B16A16_UNORM",
            Self::R16G16B16A16Snorm => "R16G16B16A16_SNORM",
            Self::R16G16B16A16Sint => "R16G16B16A16_SINT",
            Self::R16G16B16A16Uint => "R16G16B16A16_UINT",
            Self::R16G16B16A16Float => "R16G16B16A16_FLOAT",
            Self::R32G32Float => "R32G32_FLOAT",
            Self::R32G32Sint => "R32G32_SINT",
            Self::R32G32Uint => "R32G32_UINT",
            Self::R32G32Unorm => "R32G32_UNORM",
            Self::R32G32Snorm => "R32G32_SNORM",
            Self::R64Float => "R64_FLOAT",
            Self::R16G16B16A16Sscaled => "R16G16B16A16_SSCALED",
            Self::R16G16B16A16Uscaled => "R16G16B16A16_USCALED",
            Self::R32G32Sscaled => "R32G32_SSCALED",
            Self::R32G32Uscaled => "R32G32_USCALED",
            Self::R32G32Sfixed => "R32G32_SFIXED",
            Self::R64Passthru => "R64_PASSTHRU",
            Self::B8G8R8A8Unorm => "B8G8R8A8_UNORM",
            Self::R10G10B10A2Unorm => "R10G10B10A2_UNORM",
            Self::R10G10B10A2Uint => "R10G10B10A2_UINT",
            Self::R10G10B10SnormA2Unorm => "R10G10B10_SNORM_A2_UNORM",
            Self::R8G8B8A8Unorm => "R8G8B8A8_UNORM",
            Self::R8G8B8A8Snorm => "R8G8B8A8_SNORM",
            Self::R8G8B8A8Sint => "R8G8B8A8_SINT",
            Self::R8G8B8A8Uint => "R8G8B8A8_UINT",
            Self::R16G16Unorm => "R16G16_UNORM",
            Self::R16G16Snorm => "R16G16_SNORM",
            Self::R16G16Sint => "R16G16_SINT",
            Self::R16G16Uint => "R16G16_UINT",
            Self::R16G16Float => "R16G16_FLOAT",
            Self::B10G10R10A2Unorm => "B10G10R10A2_UNORM",
            Self::R11G11B10Float => "R11G11B10_FLOAT",
            Self::R32Sint => "R32_SINT",
            Self::R32Uint => "R32_UINT",
            Self::R32Float => "R32_FLOAT",
            Self::R32Unorm => "R32_UNORM",
            Self::R32Snorm => "R32_SNORM",
            Self::R10G10B10X2Uscaled => "R10G10B10X2_USCALED",
            Self::R8G8B8A8Sscaled => "R8G8B8A8_SSCALED",
            Self::R8G8B8A8Uscaled => "R8G8B8A8_USCALED",
            Self::R16G16Sscaled => "R16G16_SSCALED",
            Self::R16G16Uscaled => "R16G16_USCALED",
            Self::R32Sscaled => "R32_SSCALED",
            Self::R32Uscaled => "R32_USCALED",
            Self::R8G8Unorm => "R8G8_UNORM",
            Self::R8G8Snorm => "R8G8_SNORM",
            Self::R8G8Sint => "R8G8_SINT",
            Self::R8G8Uint => "R8G8_UINT",
            Self::R16Unorm => "R16_UNORM",
            Self::R16Snorm => "R16_SNORM",
            Self::R16Sint => "R16_SINT",
            Self::R16Uint => "R16_UINT",
            Self::R16Float => "R16_FLOAT",
            Self::R8G8Sscaled => "R8G8_SSCALED",
            Self::R8G8Uscaled => "R8G8_USCALED",
            Self::R16Sscaled => "R16_SSCALED",
            Self::R16Uscaled => "R16_USCALED",
            Self::R8Unorm => "R8_UNORM",
            Self::R8Snorm => "R8_SNORM",
            Self::R8Sint => "R8_SINT",
            Self::R8Uint => "R8_UINT",
            Self::R8Sscaled => "R8_SSCALED",
            Self::R8Uscaled => "R8_USCALED",
            Self::R8G8B8Unorm => "R8G8B8_UNORM",
            Self::R8G8B8Snorm => "R8G8B8_SNORM",
            Self::R8G8B8Sscaled => "R8G8B8_SSCALED",
            Self::R8G8B8Uscaled => "R8G8B8_USCALED",
            Self::R8G8B8Sint => "R8G8B8_SINT",
            Self::R8G8B8Uint => "R8G8B8_UINT",
            Self::R64G64B64A64Float => "R64G64B64A64_FLOAT",
            Self::R64G64B64Float => "R64G64B64_FLOAT",
            Self::R16G16B16Float => "R16G16B16_FLOAT",
            Self::R16G16B16Unorm => "R16G16B16_UNORM",
            Self::R16G16B16Snorm => "R16G16B16_SNORM",
            Self::R16G16B16Sscaled => "R16G16B16_SSCALED",
            Self::R16G16B16Uscaled => "R16G16B16_USCALED",
            Self::R16G16B16Uint => "R16G16B16_UINT",
            Self::R16G16B16Sint => "R16G16B16_SINT",
            Self::R32Sfixed => "R32_SFIXED",
            Self::R10G10B10A2Snorm => "R10G10B10A2_SNORM",
            Self::R10G10B10A2Uscaled => "R10G10B10A2_USCALED",
            Self::R10G10B10A2Sscaled => "R10G10B10A2_SSCALED",
            Self::R10G10B10A2Sint => "R10G10B10A2_SINT",
            Self::B10G10R10A2Snorm => "B10G10R10A2_SNORM",
            Self::B10G10R10A2Uscaled => "B10G10R10A2_USCALED",
            Self::B10G10R10A2Sscaled => "B10G10R10A2_SSCALED",
            Self::B10G10R10A2Uint => "B10G10R10A2_UINT",
            Self::B10G10R10A2Sint => "B10G10R10A2_SINT",
            Self::R64G64B64A64Passthru => "R64G64B64A64_PASSTHRU",
            Self::R64G64B64Passthru => "R64G64B64_PASSTHRU",
        }
    }

    pub(crate) const fn info(self) -> VfFormatInfo {
        use VfComponent::{A, B, G, R};
        use VfConvertedType::{Float, Sint, Uint};

        match self {
            Self::R32G32B32A32Float => VfFormatInfo {
                format: self,
                converted_type: Float,
                components: [Some(R), Some(G), Some(B), Some(A)],
            },
            Self::R32G32B32A32Sint => VfFormatInfo {
                format: self,
                converted_type: Sint,
                components: [Some(R), Some(G), Some(B), Some(A)],
            },
            Self::R32G32B32A32Uint => VfFormatInfo {
                format: self,
                converted_type: Uint,
                components: [Some(R), Some(G), Some(B), Some(A)],
            },
            Self::R32G32B32A32Unorm => VfFormatInfo {
                format: self,
                converted_type: Float,
                components: [Some(R), Some(G), Some(B), Some(A)],
            },
            Self::R32G32B32A32Snorm => VfFormatInfo {
                format: self,
                converted_type: Float,
                components: [Some(R), Some(G), Some(B), Some(A)],
            },
            Self::R64G64Float => VfFormatInfo {
                format: self,
                converted_type: Float,
                components: [Some(R), Some(G), None, None],
            },
            Self::R32G32B32A32Sscaled => VfFormatInfo {
                format: self,
                converted_type: Float,
                components: [Some(R), Some(G), Some(B), Some(A)],
            },
            Self::R32G32B32A32Uscaled => VfFormatInfo {
                format: self,
                converted_type: Float,
                components: [Some(R), Some(G), Some(B), Some(A)],
            },
            Self::R32G32B32A32Sfixed => VfFormatInfo {
                format: self,
                converted_type: Float,
                components: [Some(R), Some(G), Some(B), Some(A)],
            },
            Self::R64G64Passthru => VfFormatInfo {
                format: self,
                converted_type: VfConvertedType::None,
                components: [Some(R), Some(G), None, None],
            },
            Self::R32G32B32Float => VfFormatInfo {
                format: self,
                converted_type: Float,
                components: [Some(R), Some(G), Some(B), None],
            },
            Self::R32G32B32Sint => VfFormatInfo {
                format: self,
                converted_type: Sint,
                components: [Some(R), Some(G), Some(B), None],
            },
            Self::R32G32B32Uint => VfFormatInfo {
                format: self,
                converted_type: Uint,
                components: [Some(R), Some(G), Some(B), None],
            },
            Self::R32G32B32Unorm => VfFormatInfo {
                format: self,
                converted_type: Float,
                components: [Some(R), Some(G), Some(B), None],
            },
            Self::R32G32B32Snorm => VfFormatInfo {
                format: self,
                converted_type: Float,
                components: [Some(R), Some(G), Some(B), None],
            },
            Self::R32G32B32Sscaled => VfFormatInfo {
                format: self,
                converted_type: Float,
                components: [Some(R), Some(G), Some(B), None],
            },
            Self::R32G32B32Uscaled => VfFormatInfo {
                format: self,
                converted_type: Float,
                components: [Some(R), Some(G), Some(B), None],
            },
            Self::R32G32B32Sfixed => VfFormatInfo {
                format: self,
                converted_type: Float,
                components: [Some(R), Some(G), Some(B), None],
            },
            Self::R16G16B16A16Unorm => VfFormatInfo {
                format: self,
                converted_type: Float,
                components: [Some(R), Some(G), Some(B), Some(A)],
            },
            Self::R16G16B16A16Snorm => VfFormatInfo {
                format: self,
                converted_type: Float,
                components: [Some(R), Some(G), Some(B), Some(A)],
            },
            Self::R16G16B16A16Sint => VfFormatInfo {
                format: self,
                converted_type: Sint,
                components: [Some(R), Some(G), Some(B), Some(A)],
            },
            Self::R16G16B16A16Uint => VfFormatInfo {
                format: self,
                converted_type: Uint,
                components: [Some(R), Some(G), Some(B), Some(A)],
            },
            Self::R16G16B16A16Float => VfFormatInfo {
                format: self,
                converted_type: Float,
                components: [Some(R), Some(G), Some(B), Some(A)],
            },
            Self::R32G32Float => VfFormatInfo {
                format: self,
                converted_type: Float,
                components: [Some(R), Some(G), None, None],
            },
            Self::R32G32Sint => VfFormatInfo {
                format: self,
                converted_type: Sint,
                components: [Some(R), Some(G), None, None],
            },
            Self::R32G32Uint => VfFormatInfo {
                format: self,
                converted_type: Uint,
                components: [Some(R), Some(G), None, None],
            },
            Self::R32G32Unorm => VfFormatInfo {
                format: self,
                converted_type: Float,
                components: [Some(R), Some(G), None, None],
            },
            Self::R32G32Snorm => VfFormatInfo {
                format: self,
                converted_type: Float,
                components: [Some(R), Some(G), None, None],
            },
            Self::R64Float => VfFormatInfo {
                format: self,
                converted_type: Float,
                components: [Some(R), None, None, None],
            },
            Self::R16G16B16A16Sscaled => VfFormatInfo {
                format: self,
                converted_type: Float,
                components: [Some(R), Some(G), Some(B), Some(A)],
            },
            Self::R16G16B16A16Uscaled => VfFormatInfo {
                format: self,
                converted_type: Float,
                components: [Some(R), Some(G), Some(B), Some(A)],
            },
            Self::R32G32Sscaled => VfFormatInfo {
                format: self,
                converted_type: Float,
                components: [Some(R), Some(G), None, None],
            },
            Self::R32G32Uscaled => VfFormatInfo {
                format: self,
                converted_type: Float,
                components: [Some(R), Some(G), None, None],
            },
            Self::R32G32Sfixed => VfFormatInfo {
                format: self,
                converted_type: Float,
                components: [Some(R), Some(G), None, None],
            },
            Self::R64Passthru => VfFormatInfo {
                format: self,
                converted_type: VfConvertedType::None,
                components: [Some(R), None, None, None],
            },
            Self::B8G8R8A8Unorm => VfFormatInfo {
                format: self,
                converted_type: Float,
                components: [Some(B), Some(G), Some(R), Some(A)],
            },
            Self::R10G10B10A2Unorm => VfFormatInfo {
                format: self,
                converted_type: Float,
                components: [Some(R), Some(G), Some(B), Some(A)],
            },
            Self::R10G10B10A2Uint => VfFormatInfo {
                format: self,
                converted_type: Uint,
                components: [Some(R), Some(G), Some(B), Some(A)],
            },
            Self::R10G10B10SnormA2Unorm => VfFormatInfo {
                format: self,
                converted_type: Float,
                components: [Some(R), Some(G), Some(B), Some(A)],
            },
            Self::R8G8B8A8Unorm => VfFormatInfo {
                format: self,
                converted_type: Float,
                components: [Some(R), Some(G), Some(B), Some(A)],
            },
            Self::R8G8B8A8Snorm => VfFormatInfo {
                format: self,
                converted_type: Float,
                components: [Some(R), Some(G), Some(B), Some(A)],
            },
            Self::R8G8B8A8Sint => VfFormatInfo {
                format: self,
                converted_type: Sint,
                components: [Some(R), Some(G), Some(B), Some(A)],
            },
            Self::R8G8B8A8Uint => VfFormatInfo {
                format: self,
                converted_type: Uint,
                components: [Some(R), Some(G), Some(B), Some(A)],
            },
            Self::R16G16Unorm => VfFormatInfo {
                format: self,
                converted_type: Float,
                components: [Some(R), Some(G), None, None],
            },
            Self::R16G16Snorm => VfFormatInfo {
                format: self,
                converted_type: Float,
                components: [Some(R), Some(G), None, None],
            },
            Self::R16G16Sint => VfFormatInfo {
                format: self,
                converted_type: Sint,
                components: [Some(R), Some(G), None, None],
            },
            Self::R16G16Uint => VfFormatInfo {
                format: self,
                converted_type: Uint,
                components: [Some(R), Some(G), None, None],
            },
            Self::R16G16Float => VfFormatInfo {
                format: self,
                converted_type: Float,
                components: [Some(R), Some(G), None, None],
            },
            Self::B10G10R10A2Unorm => VfFormatInfo {
                format: self,
                converted_type: Float,
                components: [Some(R), Some(G), Some(B), Some(A)],
            },
            Self::R11G11B10Float => VfFormatInfo {
                format: self,
                converted_type: Float,
                components: [Some(R), Some(G), Some(B), None],
            },
            Self::R32Sint => VfFormatInfo {
                format: self,
                converted_type: Sint,
                components: [Some(R), None, None, None],
            },
            Self::R32Uint => VfFormatInfo {
                format: self,
                converted_type: Uint,
                components: [Some(R), None, None, None],
            },
            Self::R32Float => VfFormatInfo {
                format: self,
                converted_type: Float,
                components: [Some(R), None, None, None],
            },
            Self::R32Unorm => VfFormatInfo {
                format: self,
                converted_type: Float,
                components: [Some(R), None, None, None],
            },
            Self::R32Snorm => VfFormatInfo {
                format: self,
                converted_type: Float,
                components: [Some(R), None, None, None],
            },
            Self::R10G10B10X2Uscaled => VfFormatInfo {
                format: self,
                converted_type: Float,
                components: [Some(R), Some(G), Some(B), None],
            },
            Self::R8G8B8A8Sscaled => VfFormatInfo {
                format: self,
                converted_type: Float,
                components: [Some(R), Some(G), Some(B), Some(A)],
            },
            Self::R8G8B8A8Uscaled => VfFormatInfo {
                format: self,
                converted_type: Float,
                components: [Some(R), Some(G), Some(B), Some(A)],
            },
            Self::R16G16Sscaled => VfFormatInfo {
                format: self,
                converted_type: Float,
                components: [Some(R), Some(G), None, None],
            },
            Self::R16G16Uscaled => VfFormatInfo {
                format: self,
                converted_type: Float,
                components: [Some(R), Some(G), None, None],
            },
            Self::R32Sscaled => VfFormatInfo {
                format: self,
                converted_type: Float,
                components: [Some(R), None, None, None],
            },
            Self::R32Uscaled => VfFormatInfo {
                format: self,
                converted_type: Float,
                components: [Some(R), None, None, None],
            },
            Self::R8G8Unorm => VfFormatInfo {
                format: self,
                converted_type: Float,
                components: [Some(R), Some(G), None, None],
            },
            Self::R8G8Snorm => VfFormatInfo {
                format: self,
                converted_type: Float,
                components: [Some(R), Some(G), None, None],
            },
            Self::R8G8Sint => VfFormatInfo {
                format: self,
                converted_type: Sint,
                components: [Some(R), Some(G), None, None],
            },
            Self::R8G8Uint => VfFormatInfo {
                format: self,
                converted_type: Uint,
                components: [Some(R), Some(G), None, None],
            },
            Self::R16Unorm => VfFormatInfo {
                format: self,
                converted_type: Float,
                components: [Some(R), None, None, None],
            },
            Self::R16Snorm => VfFormatInfo {
                format: self,
                converted_type: Float,
                components: [Some(R), None, None, None],
            },
            Self::R16Sint => VfFormatInfo {
                format: self,
                converted_type: Sint,
                components: [Some(R), None, None, None],
            },
            Self::R16Uint => VfFormatInfo {
                format: self,
                converted_type: Uint,
                components: [Some(R), None, None, None],
            },
            Self::R16Float => VfFormatInfo {
                format: self,
                converted_type: Float,
                components: [Some(R), None, None, None],
            },
            Self::R8G8Sscaled => VfFormatInfo {
                format: self,
                converted_type: Float,
                components: [Some(R), Some(G), None, None],
            },
            Self::R8G8Uscaled => VfFormatInfo {
                format: self,
                converted_type: Float,
                components: [Some(R), Some(G), None, None],
            },
            Self::R16Sscaled => VfFormatInfo {
                format: self,
                converted_type: Float,
                components: [Some(R), None, None, None],
            },
            Self::R16Uscaled => VfFormatInfo {
                format: self,
                converted_type: Float,
                components: [Some(R), None, None, None],
            },
            Self::R8Unorm => VfFormatInfo {
                format: self,
                converted_type: Float,
                components: [Some(R), None, None, None],
            },
            Self::R8Snorm => VfFormatInfo {
                format: self,
                converted_type: Float,
                components: [Some(R), None, None, None],
            },
            Self::R8Sint => VfFormatInfo {
                format: self,
                converted_type: Sint,
                components: [Some(R), None, None, None],
            },
            Self::R8Uint => VfFormatInfo {
                format: self,
                converted_type: Uint,
                components: [Some(R), None, None, None],
            },
            Self::R8Sscaled => VfFormatInfo {
                format: self,
                converted_type: Float,
                components: [Some(R), None, None, None],
            },
            Self::R8Uscaled => VfFormatInfo {
                format: self,
                converted_type: Float,
                components: [Some(R), None, None, None],
            },
            Self::R8G8B8Unorm => VfFormatInfo {
                format: self,
                converted_type: Float,
                components: [Some(R), Some(G), Some(B), None],
            },
            Self::R8G8B8Snorm => VfFormatInfo {
                format: self,
                converted_type: Float,
                components: [Some(R), Some(G), Some(B), None],
            },
            Self::R8G8B8Sscaled => VfFormatInfo {
                format: self,
                converted_type: Float,
                components: [Some(R), Some(G), Some(B), None],
            },
            Self::R8G8B8Uscaled => VfFormatInfo {
                format: self,
                converted_type: Float,
                components: [Some(R), Some(G), Some(B), None],
            },
            Self::R8G8B8Sint => VfFormatInfo {
                format: self,
                converted_type: Sint,
                components: [Some(R), Some(G), Some(B), None],
            },
            Self::R8G8B8Uint => VfFormatInfo {
                format: self,
                converted_type: Uint,
                components: [Some(R), Some(G), Some(B), None],
            },
            Self::R64G64B64A64Float => VfFormatInfo {
                format: self,
                converted_type: Float,
                components: [Some(R), Some(G), Some(B), Some(A)],
            },
            Self::R64G64B64Float => VfFormatInfo {
                format: self,
                converted_type: Float,
                components: [Some(R), Some(G), Some(B), Some(A)],
            },
            Self::R16G16B16Float => VfFormatInfo {
                format: self,
                converted_type: Float,
                components: [Some(R), Some(G), Some(B), None],
            },
            Self::R16G16B16Unorm => VfFormatInfo {
                format: self,
                converted_type: Float,
                components: [Some(R), Some(G), Some(B), None],
            },
            Self::R16G16B16Snorm => VfFormatInfo {
                format: self,
                converted_type: Float,
                components: [Some(R), Some(G), Some(B), None],
            },
            Self::R16G16B16Sscaled => VfFormatInfo {
                format: self,
                converted_type: Float,
                components: [Some(R), Some(G), Some(B), None],
            },
            Self::R16G16B16Uscaled => VfFormatInfo {
                format: self,
                converted_type: Float,
                components: [Some(R), Some(G), Some(B), None],
            },
            Self::R16G16B16Uint => VfFormatInfo {
                format: self,
                converted_type: Uint,
                components: [Some(R), Some(G), Some(B), None],
            },
            Self::R16G16B16Sint => VfFormatInfo {
                format: self,
                converted_type: Sint,
                components: [Some(R), Some(G), Some(B), None],
            },
            Self::R32Sfixed => VfFormatInfo {
                format: self,
                converted_type: Float,
                components: [Some(R), None, None, None],
            },
            Self::R10G10B10A2Snorm => VfFormatInfo {
                format: self,
                converted_type: Float,
                components: [Some(R), Some(G), Some(B), Some(A)],
            },
            Self::R10G10B10A2Uscaled => VfFormatInfo {
                format: self,
                converted_type: Float,
                components: [Some(R), Some(G), Some(B), Some(A)],
            },
            Self::R10G10B10A2Sscaled => VfFormatInfo {
                format: self,
                converted_type: Float,
                components: [Some(R), Some(G), Some(B), Some(A)],
            },
            Self::R10G10B10A2Sint => VfFormatInfo {
                format: self,
                converted_type: Sint,
                components: [Some(R), Some(G), Some(B), Some(A)],
            },
            Self::B10G10R10A2Snorm => VfFormatInfo {
                format: self,
                converted_type: Float,
                components: [Some(R), Some(G), Some(B), Some(A)],
            },
            Self::B10G10R10A2Uscaled => VfFormatInfo {
                format: self,
                converted_type: Float,
                components: [Some(R), Some(G), Some(B), Some(A)],
            },
            Self::B10G10R10A2Sscaled => VfFormatInfo {
                format: self,
                converted_type: Float,
                components: [Some(R), Some(G), Some(B), Some(A)],
            },
            Self::B10G10R10A2Uint => VfFormatInfo {
                format: self,
                converted_type: Uint,
                components: [Some(R), Some(G), Some(B), Some(A)],
            },
            Self::B10G10R10A2Sint => VfFormatInfo {
                format: self,
                converted_type: Sint,
                components: [Some(R), Some(G), Some(B), Some(A)],
            },
            Self::R64G64B64A64Passthru => VfFormatInfo {
                format: self,
                converted_type: VfConvertedType::None,
                components: [Some(R), Some(G), Some(B), Some(A)],
            },
            Self::R64G64B64Passthru => VfFormatInfo {
                format: self,
                converted_type: VfConvertedType::None,
                components: [Some(R), Some(G), Some(B), None],
            },
        }
    }
}
