// @generated by tools/intel_userland_oracle/emit_replay_artifact.py
use crate::intel::replay::{ReplayBoSpec, ReplayPatch, ReplayPresent, ReplaySubmit};
const ROTATING_TRIANGLE_SEQ_2936_PATCHES_H8: &[u8] = include_bytes!(
    "../../.codex_tmp/intel_userland_oracle/adapterlibgfx-rotating-visible-intel/dumps/002961_pre_exec_handle_8_off_0x62000_len_0x2000.bin"
);
const ROTATING_TRIANGLE_SEQ_2936_PATCHES_H11: &[u8] = include_bytes!(
    "../../.codex_tmp/intel_userland_oracle/adapterlibgfx-rotating-visible-intel/dumps/002959_pre_exec_handle_11_off_0x0_len_0x200000.bin"
);
const ROTATING_TRIANGLE_SEQ_2936_PATCHES_H1: &[u8] = include_bytes!(
    "../../.codex_tmp/intel_userland_oracle/adapterlibgfx-rotating-visible-intel/dumps/002957_pre_exec_handle_1_off_0x0_len_0x200000.bin"
);
const ROTATING_TRIANGLE_SEQ_2936_PATCHES_H3: &[u8] = include_bytes!(
    "../../.codex_tmp/intel_userland_oracle/adapterlibgfx-rotating-visible-intel/dumps/002955_pre_exec_handle_3_off_0x0_len_0x200000.bin"
);
const ROTATING_TRIANGLE_SEQ_2936_PATCHES_H6: &[u8] = include_bytes!(
    "../../.codex_tmp/intel_userland_oracle/adapterlibgfx-rotating-visible-intel/dumps/002953_pre_exec_handle_6_off_0x0_len_0x200000.bin"
);
const ROTATING_TRIANGLE_SEQ_2936_PATCHES_H4: &[u8] = include_bytes!(
    "../../.codex_tmp/intel_userland_oracle/adapterlibgfx-rotating-visible-intel/dumps/002951_pre_exec_handle_4_off_0x0_len_0x200000.bin"
);
const ROTATING_TRIANGLE_SEQ_2936_PATCHES_H13: &[u8] = include_bytes!(
    "../../.codex_tmp/intel_userland_oracle/adapterlibgfx-rotating-visible-intel/dumps/002949_pre_exec_handle_13_off_0x0_len_0x800000.bin"
);
const ROTATING_TRIANGLE_SEQ_2936_PATCHES_H5: &[u8] = include_bytes!(
    "../../.codex_tmp/intel_userland_oracle/adapterlibgfx-rotating-visible-intel/dumps/002947_pre_exec_handle_5_off_0x0_len_0x200000.bin"
);
const ROTATING_TRIANGLE_SEQ_2936_PATCHES_H2: &[u8] = include_bytes!(
    "../../.codex_tmp/intel_userland_oracle/adapterlibgfx-rotating-visible-intel/dumps/002945_pre_exec_handle_2_off_0x0_len_0x200000.bin"
);
const ROTATING_TRIANGLE_SEQ_2936_PATCHES_H14: &[u8] = include_bytes!(
    "../../.codex_tmp/intel_userland_oracle/adapterlibgfx-rotating-visible-intel/dumps/002943_pre_exec_handle_14_off_0x0_len_0x8000000.bin"
);
const ROTATING_TRIANGLE_SEQ_2936_PATCHES_H10: &[u8] = include_bytes!(
    "../../.codex_tmp/intel_userland_oracle/adapterlibgfx-rotating-visible-intel/dumps/002941_pre_exec_handle_10_off_0x0_len_0x1000.bin"
);
const ROTATING_TRIANGLE_SEQ_2936_PATCHES_H7: &[u8] = include_bytes!(
    "../../.codex_tmp/intel_userland_oracle/adapterlibgfx-rotating-visible-intel/dumps/002938_pre_exec_full_object_handle_7_off_0x0_len_0x200000.bin"
);
const ROTATING_TRIANGLE_SEQ_2845_PATCHES_H8: &[u8] = include_bytes!(
    "../../.codex_tmp/intel_userland_oracle/adapterlibgfx-rotating-visible-intel/dumps/002870_pre_exec_handle_8_off_0x62000_len_0x2000.bin"
);
const ROTATING_TRIANGLE_SEQ_2845_PATCHES_H11: &[u8] = include_bytes!(
    "../../.codex_tmp/intel_userland_oracle/adapterlibgfx-rotating-visible-intel/dumps/002868_pre_exec_handle_11_off_0x0_len_0x200000.bin"
);
const ROTATING_TRIANGLE_SEQ_2845_PATCHES_H1: &[u8] = include_bytes!(
    "../../.codex_tmp/intel_userland_oracle/adapterlibgfx-rotating-visible-intel/dumps/002866_pre_exec_handle_1_off_0x0_len_0x200000.bin"
);
const ROTATING_TRIANGLE_SEQ_2845_PATCHES_H3: &[u8] = include_bytes!(
    "../../.codex_tmp/intel_userland_oracle/adapterlibgfx-rotating-visible-intel/dumps/002864_pre_exec_handle_3_off_0x0_len_0x200000.bin"
);
const ROTATING_TRIANGLE_SEQ_2845_PATCHES_H6: &[u8] = include_bytes!(
    "../../.codex_tmp/intel_userland_oracle/adapterlibgfx-rotating-visible-intel/dumps/002862_pre_exec_handle_6_off_0x0_len_0x200000.bin"
);
const ROTATING_TRIANGLE_SEQ_2845_PATCHES_H4: &[u8] = include_bytes!(
    "../../.codex_tmp/intel_userland_oracle/adapterlibgfx-rotating-visible-intel/dumps/002860_pre_exec_handle_4_off_0x0_len_0x200000.bin"
);
const ROTATING_TRIANGLE_SEQ_2845_PATCHES_H13: &[u8] = include_bytes!(
    "../../.codex_tmp/intel_userland_oracle/adapterlibgfx-rotating-visible-intel/dumps/002858_pre_exec_handle_13_off_0x0_len_0x800000.bin"
);
const ROTATING_TRIANGLE_SEQ_2845_PATCHES_H5: &[u8] = include_bytes!(
    "../../.codex_tmp/intel_userland_oracle/adapterlibgfx-rotating-visible-intel/dumps/002856_pre_exec_handle_5_off_0x0_len_0x200000.bin"
);
const ROTATING_TRIANGLE_SEQ_2845_PATCHES_H2: &[u8] = include_bytes!(
    "../../.codex_tmp/intel_userland_oracle/adapterlibgfx-rotating-visible-intel/dumps/002854_pre_exec_handle_2_off_0x0_len_0x200000.bin"
);
const ROTATING_TRIANGLE_SEQ_2845_PATCHES_H14: &[u8] = include_bytes!(
    "../../.codex_tmp/intel_userland_oracle/adapterlibgfx-rotating-visible-intel/dumps/002852_pre_exec_handle_14_off_0x0_len_0x8000000.bin"
);
const ROTATING_TRIANGLE_SEQ_2845_PATCHES_H10: &[u8] = include_bytes!(
    "../../.codex_tmp/intel_userland_oracle/adapterlibgfx-rotating-visible-intel/dumps/002850_pre_exec_handle_10_off_0x0_len_0x1000.bin"
);
const ROTATING_TRIANGLE_SEQ_2845_PATCHES_H7: &[u8] = include_bytes!(
    "../../.codex_tmp/intel_userland_oracle/adapterlibgfx-rotating-visible-intel/dumps/002847_pre_exec_full_object_handle_7_off_0x0_len_0x200000.bin"
);
const ROTATING_TRIANGLE_SEQ_2582_PATCHES_H8: &[u8] = include_bytes!(
    "../../.codex_tmp/intel_userland_oracle/adapterlibgfx-rotating-visible-intel/dumps/002607_pre_exec_handle_8_off_0x42000_len_0x2000.bin"
);
const ROTATING_TRIANGLE_SEQ_2582_PATCHES_H11: &[u8] = include_bytes!(
    "../../.codex_tmp/intel_userland_oracle/adapterlibgfx-rotating-visible-intel/dumps/002605_pre_exec_handle_11_off_0x0_len_0x200000.bin"
);
const ROTATING_TRIANGLE_SEQ_2582_PATCHES_H1: &[u8] = include_bytes!(
    "../../.codex_tmp/intel_userland_oracle/adapterlibgfx-rotating-visible-intel/dumps/002603_pre_exec_handle_1_off_0x0_len_0x200000.bin"
);
const ROTATING_TRIANGLE_SEQ_2582_PATCHES_H3: &[u8] = include_bytes!(
    "../../.codex_tmp/intel_userland_oracle/adapterlibgfx-rotating-visible-intel/dumps/002601_pre_exec_handle_3_off_0x0_len_0x200000.bin"
);
const ROTATING_TRIANGLE_SEQ_2582_PATCHES_H6: &[u8] = include_bytes!(
    "../../.codex_tmp/intel_userland_oracle/adapterlibgfx-rotating-visible-intel/dumps/002599_pre_exec_handle_6_off_0x0_len_0x200000.bin"
);
const ROTATING_TRIANGLE_SEQ_2582_PATCHES_H4: &[u8] = include_bytes!(
    "../../.codex_tmp/intel_userland_oracle/adapterlibgfx-rotating-visible-intel/dumps/002597_pre_exec_handle_4_off_0x0_len_0x200000.bin"
);
const ROTATING_TRIANGLE_SEQ_2582_PATCHES_H13: &[u8] = include_bytes!(
    "../../.codex_tmp/intel_userland_oracle/adapterlibgfx-rotating-visible-intel/dumps/002595_pre_exec_handle_13_off_0x0_len_0x800000.bin"
);
const ROTATING_TRIANGLE_SEQ_2582_PATCHES_H5: &[u8] = include_bytes!(
    "../../.codex_tmp/intel_userland_oracle/adapterlibgfx-rotating-visible-intel/dumps/002593_pre_exec_handle_5_off_0x0_len_0x200000.bin"
);
const ROTATING_TRIANGLE_SEQ_2582_PATCHES_H2: &[u8] = include_bytes!(
    "../../.codex_tmp/intel_userland_oracle/adapterlibgfx-rotating-visible-intel/dumps/002591_pre_exec_handle_2_off_0x0_len_0x200000.bin"
);
const ROTATING_TRIANGLE_SEQ_2582_PATCHES_H14: &[u8] = include_bytes!(
    "../../.codex_tmp/intel_userland_oracle/adapterlibgfx-rotating-visible-intel/dumps/002589_pre_exec_handle_14_off_0x0_len_0x8000000.bin"
);
const ROTATING_TRIANGLE_SEQ_2582_PATCHES_H10: &[u8] = include_bytes!(
    "../../.codex_tmp/intel_userland_oracle/adapterlibgfx-rotating-visible-intel/dumps/002587_pre_exec_handle_10_off_0x0_len_0x1000.bin"
);
const ROTATING_TRIANGLE_SEQ_2582_PATCHES_H7: &[u8] = include_bytes!(
    "../../.codex_tmp/intel_userland_oracle/adapterlibgfx-rotating-visible-intel/dumps/002584_pre_exec_full_object_handle_7_off_0x0_len_0x200000.bin"
);
const ROTATING_TRIANGLE_BASE_H8: &[u8] = include_bytes!(
    "../../.codex_tmp/intel_userland_oracle/adapterlibgfx-rotating-visible-intel/dumps/002607_pre_exec_handle_8_off_0x42000_len_0x2000.bin"
);
const ROTATING_TRIANGLE_BASE_H11: &[u8] = include_bytes!(
    "../../.codex_tmp/intel_userland_oracle/adapterlibgfx-rotating-visible-intel/dumps/002605_pre_exec_handle_11_off_0x0_len_0x200000.bin"
);
const ROTATING_TRIANGLE_BASE_H1: &[u8] = include_bytes!(
    "../../.codex_tmp/intel_userland_oracle/adapterlibgfx-rotating-visible-intel/dumps/002603_pre_exec_handle_1_off_0x0_len_0x200000.bin"
);
const ROTATING_TRIANGLE_BASE_H3: &[u8] = include_bytes!(
    "../../.codex_tmp/intel_userland_oracle/adapterlibgfx-rotating-visible-intel/dumps/002601_pre_exec_handle_3_off_0x0_len_0x200000.bin"
);
const ROTATING_TRIANGLE_BASE_H6: &[u8] = include_bytes!(
    "../../.codex_tmp/intel_userland_oracle/adapterlibgfx-rotating-visible-intel/dumps/002599_pre_exec_handle_6_off_0x0_len_0x200000.bin"
);
const ROTATING_TRIANGLE_BASE_H4: &[u8] = include_bytes!(
    "../../.codex_tmp/intel_userland_oracle/adapterlibgfx-rotating-visible-intel/dumps/002597_pre_exec_handle_4_off_0x0_len_0x200000.bin"
);
const ROTATING_TRIANGLE_BASE_H13: &[u8] = include_bytes!(
    "../../.codex_tmp/intel_userland_oracle/adapterlibgfx-rotating-visible-intel/dumps/002595_pre_exec_handle_13_off_0x0_len_0x800000.bin"
);
const ROTATING_TRIANGLE_BASE_H5: &[u8] = include_bytes!(
    "../../.codex_tmp/intel_userland_oracle/adapterlibgfx-rotating-visible-intel/dumps/002593_pre_exec_handle_5_off_0x0_len_0x200000.bin"
);
const ROTATING_TRIANGLE_BASE_H2: &[u8] = include_bytes!(
    "../../.codex_tmp/intel_userland_oracle/adapterlibgfx-rotating-visible-intel/dumps/002591_pre_exec_handle_2_off_0x0_len_0x200000.bin"
);
const ROTATING_TRIANGLE_BASE_H14: &[u8] = include_bytes!(
    "../../.codex_tmp/intel_userland_oracle/adapterlibgfx-rotating-visible-intel/dumps/002589_pre_exec_handle_14_off_0x0_len_0x8000000.bin"
);
const ROTATING_TRIANGLE_BASE_H10: &[u8] = include_bytes!(
    "../../.codex_tmp/intel_userland_oracle/adapterlibgfx-rotating-visible-intel/dumps/002587_pre_exec_handle_10_off_0x0_len_0x1000.bin"
);
const ROTATING_TRIANGLE_BASE_H7: &[u8] = include_bytes!(
    "../../.codex_tmp/intel_userland_oracle/adapterlibgfx-rotating-visible-intel/dumps/002584_pre_exec_full_object_handle_7_off_0x0_len_0x200000.bin"
);

pub(crate) const ROTATING_TRIANGLE_BO_SPECS: &[ReplayBoSpec] = &[
    ReplayBoSpec {
        handle: 7,
        gpu_va: 0x00000004BFFFF000,
        size: 0x200000,
        flags: 0xD8,
    },
    ReplayBoSpec {
        handle: 10,
        gpu_va: 0xFFFFEFFEFF400000,
        size: 0x800000,
        flags: 0x58,
    },
    ReplayBoSpec {
        handle: 14,
        gpu_va: 0xFFFFEFFEF6C00000,
        size: 0x8000000,
        flags: 0x58,
    },
    ReplayBoSpec {
        handle: 2,
        gpu_va: 0x00000003C0000000,
        size: 0x200000,
        flags: 0xD8,
    },
    ReplayBoSpec {
        handle: 5,
        gpu_va: 0x00000000C0000000,
        size: 0x200000,
        flags: 0xD8,
    },
    ReplayBoSpec {
        handle: 13,
        gpu_va: 0xFFFFEFFEFEC00000,
        size: 0x800000,
        flags: 0x58,
    },
    ReplayBoSpec {
        handle: 4,
        gpu_va: 0x0000000140000000,
        size: 0x200000,
        flags: 0xD8,
    },
    ReplayBoSpec {
        handle: 6,
        gpu_va: 0x00000002C0000000,
        size: 0x200000,
        flags: 0xD8,
    },
    ReplayBoSpec {
        handle: 3,
        gpu_va: 0x0000000100000000,
        size: 0x200000,
        flags: 0xD8,
    },
    ReplayBoSpec {
        handle: 1,
        gpu_va: 0x0000000000200000,
        size: 0x200000,
        flags: 0xD8,
    },
    ReplayBoSpec {
        handle: 11,
        gpu_va: 0x0000000300000000,
        size: 0x200000,
        flags: 0xD8,
    },
    ReplayBoSpec {
        handle: 8,
        gpu_va: 0xFFFFEFFEFFE00000,
        size: 0x200000,
        flags: 0xD8,
    },
];

pub(crate) const ROTATING_TRIANGLE_BASE_PATCHES: &[ReplayPatch] = &[
    ReplayPatch {
        handle: 7,
        offset: 0x0,
        bytes: ROTATING_TRIANGLE_BASE_H7,
    },
    ReplayPatch {
        handle: 10,
        offset: 0x0,
        bytes: ROTATING_TRIANGLE_BASE_H10,
    },
    ReplayPatch {
        handle: 14,
        offset: 0x0,
        bytes: ROTATING_TRIANGLE_BASE_H14,
    },
    ReplayPatch {
        handle: 2,
        offset: 0x0,
        bytes: ROTATING_TRIANGLE_BASE_H2,
    },
    ReplayPatch {
        handle: 5,
        offset: 0x0,
        bytes: ROTATING_TRIANGLE_BASE_H5,
    },
    ReplayPatch {
        handle: 13,
        offset: 0x0,
        bytes: ROTATING_TRIANGLE_BASE_H13,
    },
    ReplayPatch {
        handle: 4,
        offset: 0x0,
        bytes: ROTATING_TRIANGLE_BASE_H4,
    },
    ReplayPatch {
        handle: 6,
        offset: 0x0,
        bytes: ROTATING_TRIANGLE_BASE_H6,
    },
    ReplayPatch {
        handle: 3,
        offset: 0x0,
        bytes: ROTATING_TRIANGLE_BASE_H3,
    },
    ReplayPatch {
        handle: 1,
        offset: 0x0,
        bytes: ROTATING_TRIANGLE_BASE_H1,
    },
    ReplayPatch {
        handle: 11,
        offset: 0x0,
        bytes: ROTATING_TRIANGLE_BASE_H11,
    },
    ReplayPatch {
        handle: 8,
        offset: 0x42000,
        bytes: ROTATING_TRIANGLE_BASE_H8,
    },
];

pub(crate) const ROTATING_TRIANGLE_SEQ_2582_PATCHES: &[ReplayPatch] = &[
    ReplayPatch {
        handle: 7,
        offset: 0x0,
        bytes: ROTATING_TRIANGLE_SEQ_2582_PATCHES_H7,
    },
    ReplayPatch {
        handle: 10,
        offset: 0x0,
        bytes: ROTATING_TRIANGLE_SEQ_2582_PATCHES_H10,
    },
    ReplayPatch {
        handle: 14,
        offset: 0x0,
        bytes: ROTATING_TRIANGLE_SEQ_2582_PATCHES_H14,
    },
    ReplayPatch {
        handle: 2,
        offset: 0x0,
        bytes: ROTATING_TRIANGLE_SEQ_2582_PATCHES_H2,
    },
    ReplayPatch {
        handle: 5,
        offset: 0x0,
        bytes: ROTATING_TRIANGLE_SEQ_2582_PATCHES_H5,
    },
    ReplayPatch {
        handle: 13,
        offset: 0x0,
        bytes: ROTATING_TRIANGLE_SEQ_2582_PATCHES_H13,
    },
    ReplayPatch {
        handle: 4,
        offset: 0x0,
        bytes: ROTATING_TRIANGLE_SEQ_2582_PATCHES_H4,
    },
    ReplayPatch {
        handle: 6,
        offset: 0x0,
        bytes: ROTATING_TRIANGLE_SEQ_2582_PATCHES_H6,
    },
    ReplayPatch {
        handle: 3,
        offset: 0x0,
        bytes: ROTATING_TRIANGLE_SEQ_2582_PATCHES_H3,
    },
    ReplayPatch {
        handle: 1,
        offset: 0x0,
        bytes: ROTATING_TRIANGLE_SEQ_2582_PATCHES_H1,
    },
    ReplayPatch {
        handle: 11,
        offset: 0x0,
        bytes: ROTATING_TRIANGLE_SEQ_2582_PATCHES_H11,
    },
    ReplayPatch {
        handle: 8,
        offset: 0x42000,
        bytes: ROTATING_TRIANGLE_SEQ_2582_PATCHES_H8,
    },
];

pub(crate) const ROTATING_TRIANGLE_SEQ_2845_PATCHES: &[ReplayPatch] = &[
    ReplayPatch {
        handle: 7,
        offset: 0x0,
        bytes: ROTATING_TRIANGLE_SEQ_2845_PATCHES_H7,
    },
    ReplayPatch {
        handle: 10,
        offset: 0x0,
        bytes: ROTATING_TRIANGLE_SEQ_2845_PATCHES_H10,
    },
    ReplayPatch {
        handle: 14,
        offset: 0x0,
        bytes: ROTATING_TRIANGLE_SEQ_2845_PATCHES_H14,
    },
    ReplayPatch {
        handle: 2,
        offset: 0x0,
        bytes: ROTATING_TRIANGLE_SEQ_2845_PATCHES_H2,
    },
    ReplayPatch {
        handle: 5,
        offset: 0x0,
        bytes: ROTATING_TRIANGLE_SEQ_2845_PATCHES_H5,
    },
    ReplayPatch {
        handle: 13,
        offset: 0x0,
        bytes: ROTATING_TRIANGLE_SEQ_2845_PATCHES_H13,
    },
    ReplayPatch {
        handle: 4,
        offset: 0x0,
        bytes: ROTATING_TRIANGLE_SEQ_2845_PATCHES_H4,
    },
    ReplayPatch {
        handle: 6,
        offset: 0x0,
        bytes: ROTATING_TRIANGLE_SEQ_2845_PATCHES_H6,
    },
    ReplayPatch {
        handle: 3,
        offset: 0x0,
        bytes: ROTATING_TRIANGLE_SEQ_2845_PATCHES_H3,
    },
    ReplayPatch {
        handle: 1,
        offset: 0x0,
        bytes: ROTATING_TRIANGLE_SEQ_2845_PATCHES_H1,
    },
    ReplayPatch {
        handle: 11,
        offset: 0x0,
        bytes: ROTATING_TRIANGLE_SEQ_2845_PATCHES_H11,
    },
    ReplayPatch {
        handle: 8,
        offset: 0x62000,
        bytes: ROTATING_TRIANGLE_SEQ_2845_PATCHES_H8,
    },
];

pub(crate) const ROTATING_TRIANGLE_SEQ_2936_PATCHES: &[ReplayPatch] = &[
    ReplayPatch {
        handle: 7,
        offset: 0x0,
        bytes: ROTATING_TRIANGLE_SEQ_2936_PATCHES_H7,
    },
    ReplayPatch {
        handle: 10,
        offset: 0x0,
        bytes: ROTATING_TRIANGLE_SEQ_2936_PATCHES_H10,
    },
    ReplayPatch {
        handle: 14,
        offset: 0x0,
        bytes: ROTATING_TRIANGLE_SEQ_2936_PATCHES_H14,
    },
    ReplayPatch {
        handle: 2,
        offset: 0x0,
        bytes: ROTATING_TRIANGLE_SEQ_2936_PATCHES_H2,
    },
    ReplayPatch {
        handle: 5,
        offset: 0x0,
        bytes: ROTATING_TRIANGLE_SEQ_2936_PATCHES_H5,
    },
    ReplayPatch {
        handle: 13,
        offset: 0x0,
        bytes: ROTATING_TRIANGLE_SEQ_2936_PATCHES_H13,
    },
    ReplayPatch {
        handle: 4,
        offset: 0x0,
        bytes: ROTATING_TRIANGLE_SEQ_2936_PATCHES_H4,
    },
    ReplayPatch {
        handle: 6,
        offset: 0x0,
        bytes: ROTATING_TRIANGLE_SEQ_2936_PATCHES_H6,
    },
    ReplayPatch {
        handle: 3,
        offset: 0x0,
        bytes: ROTATING_TRIANGLE_SEQ_2936_PATCHES_H3,
    },
    ReplayPatch {
        handle: 1,
        offset: 0x0,
        bytes: ROTATING_TRIANGLE_SEQ_2936_PATCHES_H1,
    },
    ReplayPatch {
        handle: 11,
        offset: 0x0,
        bytes: ROTATING_TRIANGLE_SEQ_2936_PATCHES_H11,
    },
    ReplayPatch {
        handle: 8,
        offset: 0x62000,
        bytes: ROTATING_TRIANGLE_SEQ_2936_PATCHES_H8,
    },
];

pub(crate) const ROTATING_TRIANGLE_SUBMITS: &[ReplaySubmit] = &[
    ReplaySubmit {
        seq: 2582,
        batch_gpu: 0x00000004C0021000,
        batch_start: 0x22000,
        flags: 0x201800,
        patches: ROTATING_TRIANGLE_SEQ_2582_PATCHES,
    },
    ReplaySubmit {
        seq: 2845,
        batch_gpu: 0x00000004C0061000,
        batch_start: 0x62000,
        flags: 0x201800,
        patches: ROTATING_TRIANGLE_SEQ_2845_PATCHES,
    },
    ReplaySubmit {
        seq: 2936,
        batch_gpu: 0x00000004C0021000,
        batch_start: 0x22000,
        flags: 0x201800,
        patches: ROTATING_TRIANGLE_SEQ_2936_PATCHES,
    },
];

pub(crate) const ROTATING_TRIANGLE_PRESENT: ReplayPresent = ReplayPresent {
    handle: 13,
    offset: 0,
    width: 512,
    height: 512,
    pitch_bytes: 2048,
};

// Note: batch_gpu is emitted as exec_object[0].gpu_va + batch_start.
// If ACTHD says the batch really lives in another BO, regenerate or edit this field.
