use alloc::vec::Vec;

// Generated by a build script into OUT_DIR.
// Contains XOR-obfuscated Limine binaries used by the installer.
#[allow(dead_code)]
mod generated {
    include!(concat!(env!("OUT_DIR"), "/install_payload.rs"));
}

fn decode_xor(data: &[u8], key: u8) -> Vec<u8> {
    let mut out = Vec::with_capacity(data.len());
    out.extend(data.iter().map(|b| b ^ key));
    out
}

pub fn limine_bios_sys() -> Vec<u8> {
    decode_xor(generated::LIMINE_BIOS_SYS_XOR, generated::INSTALL_XOR_KEY)
}

pub fn limine_bios_hdd_bin() -> Vec<u8> {
    decode_xor(generated::LIMINE_BIOS_HDD_BIN_XOR, generated::INSTALL_XOR_KEY)
}
