[package]
name = "v"
version = "0.1.0"
edition = "2024"
license = "MIT OR Apache-2.0"

[dependencies]
hashbrown = { version = "0.17", default-features = false, features = ["default-hasher", "serde"] }
infer = { path = "../../vendor/infer", default-features = false }
spin = "0.10"
serde = { workspace = true, features = ["alloc", "derive"] }
serde_json = { workspace = true, features = ["alloc"] }
trueos-math = { path = "../trueos-math", default-features = false }
trueos-fs = { path = "../trueos-fs" }
trueos-crypto = { path = "../trueos-crypto" }

[features]
default = []

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(target_os, values("trueos", "zkvm"))'] }
